### ISSUE TITLE
fixest tidier ignores `se=` argument

### ISSUE THREAD

**Issue by karldw** [tidymodels/broom#1001]
## The problem

I noticed that the fixest tidier is ignoring the `se=` argument. This is happening because the hacky test I wrote in `is_fixest_summary` returns TRUE for some non-summary cases (as of fixest 0.8.3 and broom 0.7.5). Because this test thinks the object is a summary (possibly with the user's preferred standard error or dof settings), broom doesn't pass along the `se` argument or any others except `conf.int` and `conf.level`.

I'll try to submit a PR to better distinguish summary fixest objects from non-summarized ones.

https://github.com/tidymodels/broom/blob/1d6897515ecac6f072afe9c67138477e57d8eab9/R/fixest-tidiers.R#L74-L81

## Reproducible example

``` r
library(broom)

res = fixest::feols(Sepal.Length ~ Sepal.Width + Petal.Length , cluster=~Species, data=iris)
# Wrong result here:
broom:::is_fixest_summary(res)
#> [1] TRUE
broom:::is_fixest_summary(summary(res))
#> [1] TRUE

identical(tidy(res), tidy(res, se="standard"))
#> [1] TRUE

res2 = fixest::feols(Sepal.Length ~ Sepal.Width + Petal.Length, data=iris)
# Right result here:
broom:::is_fixest_summary(res2)
#> [1] FALSE
```

In this example, the `tidy_summary_fixest` code should have raised an error about being passed extra arguments. I'm not sure why it didn't.

https://github.com/tidymodels/broom/blob/1d6897515ecac6f072afe9c67138477e57d8eab9/R/fixest-tidiers.R#L84-L92

**Comment by simonpcouch** [comment]
Thanks for bringing this up and for your thoroughness! Would be more than happy to review a PR addressing this. :-)
