### ISSUE TITLE
Change in next spatialreg will break broom

### ISSUE THREAD

**Issue by rsbivand** [tidymodels/broom#1003]
You did not respond helpfully to PR: #696 (my last replly to your rrequest for examples below), so I guess the forthcoming breaking change in **spatialreg** https://github.com/r-spatial/spatialreg/issues/18 will also not elicit a helpful response. `summary.sarlm()` has returned `$Coef`, which is being changed to `$coefficients`, so that `stats::ceof()` will return the fixed effects coefficient table. For a short time both `$Coef` and `$coefficients` will be returned, but from **spatialreg** > 1.1-7, no `$Coef` will be returned. The affected line is https://github.com/tidymodels/broom/blob/173f407bf1332525e4c3187f17b11b919ee1fada/R/spdep-tidiers.R#L51. Further, the `*.sarlm()` methods in **spdep** are deprecated, and will become defunct during this year.

A further note that the `"sarlm" class may also be deprecated, as the coefficient table should not be reported for any models including the spatially lagged response, but an effects or impacts table should be reported. This is ongoing work, which we'll work up as a PR when the time comes.

Thanks for getting back to me. I am not convinced by map/group arguments, and without a reprex say using one of the following standard tests would find it hard to think of a relevant context. By dropping names added for good reasons by function authors, potentially important information is lost, I think.

Some (legacy) examples of named estimate components of htest objects - most of these have meaningful names, often recording how the test was applied:

```
library(stats)
names(ansari.test(rnorm(10), rnorm(10, 0, 2), conf.int = TRUE)$estimate)
names(binom.test(c(682, 243), p = 3/4)$estimate)
names(cor.test(rnorm(5), rnorm(5), method = "kendall", alternative = "greater")$estimate)
TeaTasting <- matrix(c(3, 1, 1, 3),  nrow = 2, dimnames = list(Guess = c("Milk", "Tea"), Truth = c("Milk", "Tea")))
names(fisher.test(TeaTasting, alternative = "greater")$estimate)
Rabbits <- array(c(0, 0, 6, 5, 3, 0, 3, 6, 6, 2, 0, 4, 5, 6, 1, 0, 2, 5, 0, 0), dim = c(2, 2, 5),        dimnames = list(Delay = c("None", "1.5h"), Response = c("Cured", "Died"), Penicillin.Level = c("1/8", "1/4", "1/2", "1", "4")))
names(mantelhaen.test(Rabbits)$estimate)
names(poisson.test(137, 24.19893)$estimate)
smokers  <- c( 83, 90, 129, 70 )
patients <- c( 86, 93, 136, 82 )
names(prop.test(smokers, patients)$estimate)
names(t.test(extra ~ group, data = sleep)$estimate)
x <- rnorm(50, mean = 0, sd = 2)
y <- rnorm(30, mean = 1, sd = 1)
names(var.test(x, y)$estimate)
x <- c(1.83,  0.50,  1.62,  2.48, 1.68, 1.88, 1.55, 3.06, 1.30)
y <- c(0.878, 0.647, 0.598, 2.05, 1.06, 1.29, 1.06, 3.14, 1.29)
names(wilcox.test(x, y, paired = TRUE, alternative = "greater", conf.int=TRUE)$estimate)
```

_Originally posted by @rsbivand in https://github.com/tidymodels/broom/issues/696#issuecomment-519646700_

**Comment by simonpcouch** [comment]
Thanks for the issue!

re:

> You did not respond helpfully to PR: #696 (my last replly to your rrequest for examples below), so I guess the forthcoming breaking change in spatialreg r-spatial/spatialreg#18 will also not elicit a helpful response.

Your tone is inappropriate. Please don't speak to maintainers this way.

If yall decide to move forward with this breaking change in `spatialreg`, I'll be glad to review a PR making that adjustment to the relevant tidiers and push out a new release!

Regarding discussion in #696, I'll let Alex continue to be the maintainer in contact there. @alexpghayes, let me know if you'd appreciate a look from me there.

**Comment by rsbivand** [comment]
@simonpcouch Ok, thanks, the current status of **spatialreg** includes both `object$Coef` and `object$coefficients` as the coeefficient matrix, so is not yet breaking. When all the model functions deprecated in **spdep** are removed,  `object$Coef` will also be removed. If you act now, possibly **spdep** users who generate `sarlm` objects will hit problems, but they have been warned to switch to **spatialreg** already. I'll add to this issue when the time comes. I do hope that #696 can be resolved using informative names, as **broom** is not usable for me in teaching without this correction.

**Comment by simonpcouch** [comment]
The context is much appreciated! I'll keep an eye out for a ping on this issue to move forward with that switch.

**Comment by rsbivand** [comment]
@simonpcouch On reflection, the breakage can be avoided by reverting the change but using `coef.summary.*()` methods for each defined model output object. **brooom** can stay as it is, or move to `coef(s)` in the line indicated above rather than `s$Coef` once a new release of **spatialreg** is on CRAN.

**Comment by rsbivand** [comment]
Should I also consider adding spatial coefficients to the coefficient table? That should simplify your code. I'll get back if this happens. I also need to allow `spdep::sarlm` to stay fixed, but `spatialreg::sarlm` to diverge as class/method constructs - would it be easier if the **spatialreg** class name was package-specific?

**Comment by alexpghayes** [comment]
> would it be easier if the spatialreg class name was package-specific?

Yes please! It is very difficult for us to deal with two objects with the same `class` attribute but different fields/methods in `broom`.

**Comment by rsbivand** [comment]
@alexpghayes I just committed disambiguating changes to model output object class names in **spatialreg**, so that when the time comes (when model fitting functions in **spdep** are made defunct), the spdep file can replaced for model output objects by one for **spatialreg**, probably with the spatial coefficient row(s) in coef() of the model summary.

**Comment by simonpcouch** [comment]
This sounds good. Keep us up to date on the `spatialreg` release and we'll make adjustments then!
