### ISSUE TITLE
add new method for `bfsl`

### ISSUE THREAD

**Issue by japhir** [tidymodels/broom#1008]
The best fit straight-line package[bfsl](https://github.com/pasturm/bfsl) is great for fitting linear models that take into account uncertainty in both the X and Y direction.

However, it outputs a list object of class `bfsl` with a `print` and (base graphics) `plot` method. 

## Feature

It would be great if it could be integrated into tidymodels so that I can use ggplot2 for nicer plotting and incorporate it in my dataprocessing workflow.

**Comment by simonpcouch** [comment]
Thanks for the issue! It would be great if the maintainers of `bfsl` could take on writing and maintaining those tidiers, as I'm not familiar with the package--I wrote up some thoughts on best practices for how to do so here. :-) 

https://www.tidymodels.org/learn/develop/broom/
