### ISSUE TITLE
does gamlss belong in broom or broom.mixed?

### ISSUE THREAD

**Issue by bbolker** [tidymodels/broom#1009]
Sorry for raising this here and not in the RStudio community forum (as suggested for "questions"), but I'm guessing it's more appropriate here.  Feel free to close if not.

Apparently `gamlss` tidiers live in both `broom` and `broom.mixed`. Duplication seems bad. In which package do they really belong? I guess in `broom` by analogy with `mgcv::gam()`, which fits similar models ...?

**Comment by simonpcouch** [comment]
`gamlss` tidiers were soft-deprecated in `broom` 0.7.1 in favor of those in `broom.mixed`--more discussion [here](https://github.com/tidymodels/broom/issues/507).

Probably about time for a hard-deprecation from our end, though. On board?

**Comment by bbolker** [comment]
Yeah, I keep forgetting.

**Comment by simonpcouch** [comment]
Sweet, sounds good. :-)
