### ISSUE TITLE
Add `exponentiate=` argument to `tidy.negbin()` ?

### ISSUE THREAD

**Issue by ddsjoberg** [tidymodels/broom#1011]
Hello, hello!

I see that `MASS::glm.nb()` support was added in the recent release. Thank you!  

The tidying function was implemented without an `exponentiate=` argument, and I am writing to request it be added. 🙌🏼 

Another point I wanted to ask about was the handling of the unused `...` arguments. Are there plans to implement some checking of unused args, for example, using the ellipsis package? https://github.com/r-lib/ellipsis

I was using the tidier for negbin models with the exponentiate argument, not realizing initially that the argument was being ignored.

Thank you!
cc @larmarange

**Comment by alexpghayes** [comment]
Probably the fast way to make `exponentiate` happen is via a PR, which would be very welcome.

`ellipsis` is on the long term plan and has been for a while but is a little complicated to make happen, so probably won't be happening anytime soon. More specifically, the `ellipsis` checks should probably be made in the S3 generic definitions in `generics`. And once we add the dots checking there will be a fair amount of fixing to do / revdep breakage IIRC.

**Comment by ddsjoberg** [comment]
Thanks @alexpghayes for the quick response!

Just submitted my first broom PR. Hope it helps!
