### ISSUE TITLE
Showing observation or samples column in tidy.prcomp(prcomp.obj, matrix = "loadings") matrix?

### ISSUE THREAD

**Issue by dikiprawisuda** [tidymodels/broom#1014]
Hello everyone, 
I cross-posted this question from SO and Rstudio forum.
Is there a way to make a matrix that showed observation/samples relation to the features loadings?
For example, I am expecting something like the following fabricated data.

```r
library(tidyverse)
data("USArrests")

PCA <- prcomp(USArrests, scale. = T)

broom::tidy(PCA) %>% #from this matrix.
  slice(1:10) %>% #pick the first 10 vector
  mutate(value = pull(slice(broom::tidy(PCA, matrix = "loadings")[,"value"], 1:10))) #and then use it to replace this matrix's first column
```
Is this possible and correct?

Thank you.

**Comment by simonpcouch** [comment]
Hey, thanks for the issue! This question is better suited for SO/RStudio Community.🐞
