### ISSUE TITLE
new tidiers: `sampleSelection`

### ISSUE THREAD

**Issue by vincentarelbundock** [tidymodels/broom#1016]
The `sampleSelection` package implements a variety of selection models:

> Two-step and maximum likelihood estimation of Heckman-type sample selection models: standard sample selection models (Tobit-2), endogenous switching regression models (Tobit-5), sample selection models with binary dependent outcome variable, interval regression with sample selection (only ML estimation), and endogenous treatment effects models. These methods are described in the three vignettes that are included in this package and in econometric textbooks such as Greene (2011, Econometric Analysis, 7th edition, Pearson).

Here are minimal versions of a `glance` and `tidy` method to extract results from those models. I'm not super familiar with the package, so not sure this will work on models beyond the simple two-step model estimated here:

```r
library(sampleSelection)
library(wooldridge) # for mroz data
library(broom)

mod_selection <- selection(
  inlf ~ educ + kidslt6 + kidsge6, 
  wage ~ educ + exper + expersq,
  method = "2step",
  data = mroz)

tidy.selection <- function(x,
                           conf.int = FALSE,
                           conf.level = 0.95,
                           ...) {
  s <- summary(x, ...)
  ret <- broom:::as_tidy_tibble(s$estimate,
                                new_names = c("estimate", "std.error",
                                              "statistic", "p.value"))

  # selection models include an outcome and a selection equation
  ret$group <- NA_character_
  ret$group[s$param$index$betaS] <- "Selection"
  ret$group[s$param$index$betaO] <- "Outcome"

  if (isTRUE(conf.int)) {
    ci <- broom:::broom_confint_terms(x, level = conf.level)
    ret <- dplyr::left_join(ret, ci, by = "term")
  }
  ret
}

glance.selection <- function(x, ...) {
  broom:::as_glance_tibble(
    nobs = stats::nobs(x),
    method = x$method[1],
    rho = x$rho,
    sigma = x$sigma,
    na_types = "icrr")
}
```

**Comment by simonpcouch** [comment]
Do each of the model types outputted by this package share the `selection` class?

It looks like the packages wrapped by `sampleSelection` are [hosted on R-Forge](http://r-forge.r-project.org/projects/sampleselection/). 

With an eye for maintainability, it'd be great if the package authors could support these tidiers. :-)

**Comment by vincentarelbundock** [comment]
https://r-forge.r-project.org/tracker/index.php?func=detail&aid=6722&group_id=256&atid=1055
