### ISSUE TITLE
Add tidy() method for miceadds

### ISSUE THREAD

**Issue by kelseygonzalez** [tidymodels/broom#1021]
## Feature

To produce linear models with clustered robust standard errors, I use `miceadds::lm.cluster()`. However, `broom::tidy()` does not work on this package and produces the following error:
```
Error: No tidy method for objects of class lm.cluster
```

I have tried to find an alternative package that can produce clustered robust standard errors that works with broom without success. Therefore, I request that broom extends its functionality to work with the models in `miceadds`.

**Comment by kelseygonzalez** [comment]
Note: There is a hacky solution to do:
```
summary(model$lm_res) %>% tidy()
```

To get the correct output. It may be that `miceadds` needs to update their output format or it would be easy for `broom` to add functionality for `lm.cluster` object types.

**Comment by bgall** [comment]
This is probably quite easy and a solution would be stable, but low priority as the `lm.cluster` class is just an `lm` class with a different covariance matrix (see [here](https://rdrr.io/cran/miceadds/man/lm.cluster.html)). You could simply use `lm()`, swap out the covariance matrix with `multiwayvcov::vcovCL`, then pass the object to `broom` to produce identical results without all of the baggage and dependencies of `mice`. This is also trivial to vectorize across multiple, imputed datasets (e.g. using `lapply()`, `purrr::map()`, etc.).

**Comment by simonpcouch** [comment]
Thanks for the issue, @kelseygonzalez! This seems like it's worth supporting.

I'm not familiar with this model class, so I don't feel confident enough to implement these tidiers myself, but I'd be more than happy to review a PR if someone is willing to give these a go.🐁
