### ISSUE TITLE
Passing survey models to broom::glance() with lapply/purrr/anonymous functions produces errors

### ISSUE THREAD

**Issue by bgall** [tidymodels/broom#1022]
## The problem

Passing `broom::glance()` models from the `survey` package (e.g. `survey::svyglm`) produces an error (e.g. "object 'x' not found) when the `design` argument of the `survey` models is passed objects by piping or anonymous functions. This is particularly problematic because it means you cannot use `glance` with `lapply` or `purrr::map` in most cases. This appears to be an issue with `broom` rather than `survey` as `broom::tidy` works as expected but not `broom::glance`.

## Reproducible example

``` r
# Packages
library(dplyr)
library(purrr)
library(survey)
library(broom)

# Create example "imputed" data
df_list <- data.frame(z = rnorm(20),
                      y = rnorm(20)) %>%
  list() %>%
  rep(2)

# Turn data.frames into design objects
objs_survey <- df_list %>%
  purrr::map(function(x) {
    survey::svydesign(data = x,
                      ids = ~ 1,
                      weights = ~ 1)
  })

# Fit models
mods_survey <- objs_survey %>%
  purrr::map(function(x) {
    survey::svyglm(formula = y ~ z, design = x)
  })

# Works with tidy
mods_survey %>% purrr::map(function(x) {
  broom::tidy(x)
})
#> [[1]]
#> # A tibble: 2 x 5
#>   term        estimate std.error statistic p.value
#>   <chr>          <dbl>     <dbl>     <dbl>   <dbl>
#> 1 (Intercept)  -0.208      0.213    -0.975   0.343
#> 2 z            -0.0880     0.212    -0.415   0.683
#> 
#> [[2]]
#> # A tibble: 2 x 5
#>   term        estimate std.error statistic p.value
#>   <chr>          <dbl>     <dbl>     <dbl>   <dbl>
#> 1 (Intercept)  -0.208      0.213    -0.975   0.343
#> 2 z            -0.0880     0.212    -0.415   0.683

# But doesn't work with glance as
# there is an evaluation issue with
# glance looking for `x` instead of
# elements of mods_survey
mods_survey %>% purrr::map(function(x) {
  broom::glance(x)
})
#> Error in .svycheck(design): object 'x' not found

# At first it looked like a purrr issue
# but is reproducible via lapply() so it
# is not just purrr
lapply(mods_survey, function(x) {
  broom::glance(x)
})
#> Error in .svycheck(design): object 'x' not found

# The issue only appears when the survey
# model's design argument is passed an
# object indirectly (via pipe, lapply, etc.)

# Passing objects directly to design works
survey::svyglm(formula = y ~ z,
               design = objs_survey[[1]]) %>%
  broom::glance()
#> # A tibble: 1 x 6
#>   null.deviance df.null   AIC   BIC deviance df.residual
#>           <dbl>   <int> <dbl> <dbl>    <dbl>       <dbl>
#> 1          17.7      19  19.6  23.5     17.5          18

# Passing objects indirectly (via pipe or
# e.g. lapply/purrr) reproduces error
objs_survey[[1]] %>% survey::svyglm(formula = y ~ z,
                                    design = .) %>%
  broom::glance()
#> Error in .svycheck(design): object '.' not found
```

<sup>Created on 2021-05-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by simonpcouch** [comment]
Thanks for the issue!

I'm not sure I understand the notes in your reprex--I see this error regardless of whether I'm using a mapping function or not.

``` r
# packages
library(dplyr)
library(purrr)
library(survey)
library(broom)

# create example "imputed" data
df_list <- data.frame(z = rnorm(20),
                      y = rnorm(20)) %>%
  list() %>%
  rep(2)

# turn data.frames into design objects
objs_survey <- df_list %>%
  purrr::map(function(x) {
    survey::svydesign(data = x,
                      ids = ~ 1,
                      weights = ~ 1)
  })

# fit models
mods_survey <- objs_survey %>%
  purrr::map(function(x) {
    survey::svyglm(formula = y ~ z, design = x)
  })

# glance at each
mods_survey %>% purrr::map(function(x) {
  broom::glance(x)
})
#> Error in .svycheck(design): object 'x' not found

# glance at just one
mods_survey[[1]] %>% broom::glance()
#> Error in .svycheck(design): object 'x' not found

# or...
broom::glance(mods_survey[[1]])
#> Error in .svycheck(design): object 'x' not found
```

<sup>Created on 2021-05-19 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0.9001)</sup>

Do you see this same result? If so, I'm not sure this is related to lapply/purr mapping--please let me know if I'm missing something.

Seems worth troubleshooting regardless. :-)

**Comment by bgall** [comment]
Yes, both of our results are reproducible. Let me try to better highlight the distinction though.

In your approach, a list of data.frames (call it X) is passed to `map()` where each data.frame is then passed to `svydesign()`. In the below, the **first element of the resulting list of model objects** is then passed to `glance()`, throwing an error.

> `mods_survey[[1]] %>% broom::glance()` 

I find that if the **first element of X i**s passed directly to `svydesign() and the single, resulting model object is passed to glance, there is no error and the "correct" output is produced, as below:

> `survey::svyglm(formula = y ~ z,
>                design = objs_survey[[1]]) %>%
>   broom::glance()`

# Takeaway
The output of `svyglm()` appears to differ when an anonymous function is used to pass values to the `design` argument (your example above) and when those same values are passed directly (my example above). One the one hand, `svyglm()` produces the same model results (coefficients, etc.) without error for either approach and appears to work as expected in either case. On the other hand, `glance()` works in the above with my example and not in your example, suggesting it is changing either (a) what `glance()` is looking for or (b) whether objects contain what `glance()` is looking for. In this way, it looks like `survey` is doing what it should and `glance` is not looking in the right place or for the right thing.

**Comment by simonpcouch** [comment]
Apologies on the delay here! If the issue you're seeing here has persisted, I'd be glad to review a PR implementing a fix. :-)
