### ISSUE TITLE
Unintuitive/flipped sign of difference in means in tidy t-test tables

### ISSUE THREAD

**Issue by DerForscher107** [tidymodels/broom#1025]
The tidy t-test table produces an unintuitive sign for the difference in means between control and treatment groups. Specifically, the sign is flipped, i.e. positive when it should be negative and vice-versa.

This error can be reproduced by:
1. running t.test(x ~ t, data=dataset) where t is a dummy variable with 0=control and 1=treatment
2. applying broom::tidy() to the result
3. writing the tidy table into an XLSX file using write.xlsx()

**Comment by simonpcouch** [comment]
Thanks for the issue!

Can you please provide a minimal [reprex](https://github.com/tidyverse/reprex#what-is-a-reprex) (reproducible example)? A reprex will help me troubleshoot and fix your issue more quickly.🙂

**Comment by DerForscher107** [comment]
Hi Simon,

Thanks for the quick and kind reply.

I haven't worked with reprex() before and got different error messages, but below is the code including the necessary packages. I take R's inbuilt dataset "mtcars" as an example, where I treat "mpg" as the dependent variable and "vs" as the control/treatment dummy.

The resulting XLSX table is this:
![image](https://user-images.githubusercontent.com/84723600/119877642-92a84e00-bf29-11eb-920b-4cb6cba80e45.png)

As you see, the first column is the difference between the second and third columns, i.e. the difference between the treatment and control groups. The issue is just that the sign is flipped. I'd be grateful for a solution. Thanks in advance for your help!

---

**Reproduction code:**

install.packages("broom")
library("broom")

install.packages("openxlsx")
library("openxlsx")

ttest_result <- t.test(mpg ~ vs, data=mtcars)
tidy_ttest_result <- broom::tidy(ttest_result)
write.xlsx(tidy_ttest_result, "tidy_ttest_result.xlsx")

**Comment by simonpcouch** [comment]
I can see an argument for why one may find this unintuitive, but given that this has been longstanding functionality in the package and would likely affect many existing analyses, I don't anticipate we will make this change. Thank you for your issue, regardless. :-)
