### ISSUE TITLE
Failing CRAN checks due to `tidy.epi.2by2()` issues

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#1028]
@nt-williams it looks like the `epiR` package was just updated and the epiR.2by2() tidier is no longer working, which I see you initially implemented. I don't know how to fit it -- the `epi.2by2` object is rather complicated and I'm not sure what the tidier was doing before the recent changes.

We need to re-submit `broom` to CRAN by June 16 and fix the [failing package checks](https://cran.r-project.org/web/checks/check_results_broom.html).

Do you have a moment to fix the `tidy.epi.2by2()` function? If not I'll probably remove it from `broom` until someone with more experience with the `epiR` package can take a closer look. 

cc @simonpcouch

**Comment by nt-williams** [comment]
@alexpghayes thanks for bringing this to my attention. I took a look and think I can restore the existing functionality in a timely manner.

**Comment by simonpcouch** [comment]
Closed in #1029. :-)
