### ISSUE TITLE
tidy output for rma models (metafor meta-analysis package)

### ISSUE THREAD

**Issue by thoughtsnippet** [tidymodels/broom#103]
Hey, it would really be a huge timesaver in meta-analytic studies if broom could work with the outputs of metafor() package.

Cheers, Martin

**Comment by 1234Mannheim** [comment]
Does anybody now an table output package as texreg or stargazer which can handle the rma models from the metafor package? This would be so time-saving. Thanks a lot!  Jessica

**Comment by alexpghayes** [comment]
This has become #621.
