### ISSUE TITLE
In tidy.ergm(), summary.ergm()$coefs will be deprecated soon.

### ISSUE THREAD

**Issue by krivit** [tidymodels/broom#1034]
`ergm` maintainer here. Long story short, for reasons I give below, I am planning to deprecate `summary.ergm()$coefs` element, and `summary.ergm()$coefficients` (or `coef(sumamry.ergm())`) will return the coefficient `matrix`, not `data.frame`.

The good news is that this is actually consistent with `summary.lm()`, so it should simplify `broom` code, if anything.

## Explanation

Currently, `summary.ergm()` returns two coefficients tables in data frames, one in `$coefficients` and another in `$coefs`, the latter for backwards compatibility. `tidy.ergm()` uses the latter.

Recently, it transpired that whereas whereas `ergm()` can produce repeated parameter names, `data.frame` objects don't support repeated row names and can, in fact, mangle them badly under some circumstances. I am therefore having to transition to using matrices. Unfortunately, it looks like `tibble::rownames_to_column()` does not support matrix input, so this change would break the current implementation of `tidy.ergm()`.

Since I am breaking it anyway, I want to make everything more consistent with `summary.lm()` output, and so my plan is:

1. `summary.ergm()$coefficients` will be a matrix in the next release (just submitted to CRAN). This does not affect broom.
2. `summary.ergm()$coefs` remain a data frame to keep `broom` and other packages going, but will be deprecated and removed in the future.

The good news is that the extraction code used in `tidy.lm()` should work seamlessly, since it also uses the matrix in the `$coefficients` element.

I apologise for the inconvenience, and would be happy to help make the adjustments needed.

**Comment by simonpcouch** [comment]
Thanks for the heads up and clear explanation! Will make this adjustment in the upcoming release.
