### ISSUE TITLE
Feature Request/Question: Should augment_columns() be exported?

### ISSUE THREAD

**Issue by jthomasmock** [tidymodels/broom#1044]
## Proposal: Remove `augment_columns()` from exported functions.

Hi team!

I naively assumed that `augment_columns()` was an appropriate user-level function as it is exported. It looks like it is actually just a utility function (within the `utilities.R` file) and is instead used "under the hood" by `augment()`.

Given that `augment()` is the appropriate top-level function, I'm proposing removing `augment_columns()` from exports OR if needed as an export for other downstream packages, at least indicating in the user documentation for `augment_columns()` that it is a developer-focused function, and that `augment()` is preferred over `augment_columns()` for package users.

Many thanks to clarification with @alexpghayes and @bwiernik in a [Twitter Thread](https://twitter.com/bmwiernik/status/1428728330061295617?s=20)

**Comment by simonpcouch** [comment]
Thanks for the thoughtful issue! 

`augment_columns` is one of the last functions intended for developer/internal usage that's still exported (many were deprecated in 0.7.0), as it broke a good few dependencies when deprecated. I agree that the documentation should be clearer here, though--will push some changes here in a bit. :-)
