### ISSUE TITLE
Error with ```augment.mlogit()```

### ISSUE THREAD

**Issue by jamesrrae** [tidymodels/broom#1045]
## The problem

I'm getting an error when even using the [example code](https://rdrr.io/cran/broom/man/augment.mlogit.html) for ```augment.mlogit``` with the broom package. Reproducible example below.

## Reproducible example

```r
# Add broom
library(broom)

## Not run: 
library(mlogit)
#> Loading required package: dfidx
#> 
#> Attaching package: 'dfidx'
#> The following object is masked from 'package:stats':
#> 
#>     filter
data("Fishing", package = "mlogit")
Fish <- dfidx(Fishing, varying = 2:9, shape = "wide", choice = "mode")
m <- mlogit(mode ~ price + catch | income, data = Fish)

tidy(m)
#> # A tibble: 8 x 5
#>   term                  estimate std.error statistic  p.value
#>   <chr>                    <dbl>     <dbl>     <dbl>    <dbl>
#> 1 (Intercept):boat     0.527     0.223         2.37  1.79e- 2
#> 2 (Intercept):charter  1.69      0.224         7.56  3.95e-14
#> 3 (Intercept):pier     0.778     0.220         3.53  4.18e- 4
#> 4 price               -0.0251    0.00173     -14.5   0.      
#> 5 catch                0.358     0.110         3.26  1.12e- 3
#> 6 income:boat          0.0000894 0.0000501     1.79  7.40e- 2
#> 7 income:charter      -0.0000333 0.0000503    -0.661 5.08e- 1
#> 8 income:pier         -0.000128  0.0000506    -2.52  1.18e- 2
augment(m)
#> Error: Problem with `mutate()` input `id`.
#> x object of type 'closure' is not subsettable
#> ℹ Input `id` is `idx$id1`.
glance(m)
#> # A tibble: 1 x 6
#>   logLik  rho2 rho20   AIC   BIC  nobs
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <int>
#> 1 -1215. 0.189 0.258 2446.    NA  1182

## End(Not run)
```

**Comment by simonpcouch** [comment]
Thanks for the issue! I'm seeing the same error. I would guess it's due to the changes mentioned [here](https://github.com/ycroissant/mlogit/blame/master/NEWS.md#L10-L13).

Given the [comment](https://github.com/tidymodels/broom/blob/afe793eaf455ec47f73da23042a4bafd33425946/R/mlogit-tidiers.R#L65-L68) in the `augment.mlogit` source, I want to defer to the author of these tidiers before giving a go at a fix myself. 

@gregmacfarlane, would you be willing to give this a look? It seems the structure of those index columns has changed.

**Comment by gregmacfarlane** [comment]
I am willing to look at this, but probably can't do so for a few days.

**Comment by simonpcouch** [comment]
Great, no worries. Much appreciated!

**Comment by simonpcouch** [comment]
Dropping a note @gregmacfarlane in case this has fallen off your radar. All is well if you can't make it to this—I'll put some time in here if so.

**Comment by gregmacfarlane** [comment]
Going to fix this today, hopefully

**Comment by gregmacfarlane** [comment]
Well, that was easier than expected.

**Comment by simonpcouch** [comment]
Much, much appreciated!
