### ISSUE TITLE
cmdscale support by tidy.list and glance.list

### ISSUE THREAD

**Issue by corybrunson** [tidymodels/broom#1049]
## Context

I occasionally work with multidimensional scaling results from `stats::cmdscale()`. By default, a matrix of point coordinates is returned, which can be `as_tibble()`ed.

However, if any of the parameters `eig`, `add`, and `x.ret` is set to `TRUE`, or if `list. = TRUE`, then a list is returned with a fixed set of names, regardless of which parameters were set to `TRUE` (so that some named elements may be `NULL`). For example:

``` r
loc <- cmdscale(eurodist, add = TRUE)
names(loc)
#> [1] "points" "eig"    "x"      "ac"     "GOF"
loc <- cmdscale(eurodist, eig = TRUE, add = TRUE, x.ret = TRUE)
names(loc)
#> [1] "points" "eig"    "x"      "ac"     "GOF"
loc <- cmdscale(eurodist, eig = FALSE, add = FALSE, x.ret = FALSE, list. = TRUE)
names(loc)
#> [1] "points" "eig"    "x"      "ac"     "GOF"
```

<sup>Created on 2021-09-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

## Feature

This consistent naming convention means that `broom:::tidy.list()` and `broom:::glance.list()` should be able to recognize any `cmdscale()` output _other than_ the default coordinate matrix, with helper functions `tidy_cmdscale()` and `glance_cmdscale()`.

I would expect `glance_cmdscale()` to return the additive constant `loc$ac` and the two goodness-of-fit statistics `loc$GOF` as well as the number of points in the input object and the dimension of the representation space, which can be inferred from `loc$points` (number of rows and number of columns).

The coordinates themselves (`loc$points`) are the primary statistical result, so i would expect `tidy_cmdscale()` to return them as a tibble. Analogous to `tidy_svd()`, it might also make sense to accept a `matrix` parameter that defaults to `"points"` but can also be set to `"x"` to retrieve the doubly-centered symmetric matrix entries, pivoted to long form and using only the upper or lower triangle, or to `"eig"` to retrieve the eigenvalues, with summary statistics like those returned by `tidy_svd(matrix = "d")`.

If the team agrees, then i would be glad to draft an implementation and submit a pull request!

**Comment by simonpcouch** [comment]
Thanks for the issue, @corybrunson! 

I'm generally looking not to add any new tidiers to the package, as my ability to maintain them well decreases as the package gets larger. I'm also not familiar enough with this method to feel confident maintaining these well, and a bit concerned about the lack of type-stability of `cmdscale` and its effect on our ability to tidy its output. So, for now, I'll close this issue.

That said, if it becomes clear that this has been long-awaited functionality for a good few folks, I'd be willing to review a PR.

Again, the thoughtful issue is much appreciated. :-)

**Comment by corybrunson** [comment]
@simonpcouch thanks very much for the explanation! I plan to write up a version for my own use, and i'll be glad to relocate it here in case the broader community expresses a need for it.
