### ISSUE TITLE
Should broom have a verb to extract coefficients?

### ISSUE THREAD

**Issue by hadley** [tidymodels/broom#105]
i.e. to create a tidy data frame where there is one column for each coefficient. This certainly seems like what you often want when working with linear models

**Comment by dgrtwo** [comment]
I don't think I understand: in functions like `tidy.lm` we end up with one row per coefficient. Would we transpose that to get one column per coefficient?

Or were you suggesting one-row-per something else?

**Comment by hadley** [comment]
Yes one row per model with one column per coefficient. Maybe that suggests it should be an option to augment?

**Comment by dgrtwo** [comment]
You mean glance? (Wrt one row per model)

Normally I would do this with tidyr like:

tidy(mod) %>%
  select(term, estimate)  %>%
  spread(term, estimate)

But I can see it being worked optionally into glance as a shortcut. Do you have an example of a visualization or analysis where it could be useful? Not sure I immediately see it

**Comment by hadley** [comment]
Ooops, yes, `glance()`.

Generally, I think it's more natural to do:

```R
df %>% ggplot(aes(coefficient1)) + geom_histogram()
```

than

```R
df %>% filter(coefficient == 1) %>% ggplot(aes(value)) + geom_histogram()
```

Plus you also often want to do scatterplots of coefficients to see how they're related.

**Comment by kmace** [comment]
I'd like this feature too. Extracting a coefficient is difficult when using nested data.

```
joined_res %>% 
  group_by(Strain) %>% nest() %>% 
  mutate(fit = map(data, ~lm(log2FoldChange~wt_l2FC, data = .x)),
         coef = map(fit, tidy),
         glance = map(fit, glance),
         data_aug = map(fit, augment),
         slope = map_dbl(coef, ~ filter(., term == 'wt_l2FC') %>% pull(estimate)))
```

**Comment by alexpghayes** [comment]
Since `tidy` gets you most of the way there, what about a helper to call on tidied output?

``` r
library(broom)
library(tibble)

coef_helper <- function(td) as_tibble(t(deframe(td)))

fit <- lm(mpg ~ ., mtcars)
td <- tidy(fit)

coef_helper(td)
#> # A tibble: 1 x 11
#>   `(Intercept)`    cyl   disp      hp  drat    wt  qsec    vs    am  gear
#>           <dbl>  <dbl>  <dbl>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1          12.3 -0.111 0.0133 -0.0215 0.787 -3.72 0.821 0.318  2.52 0.655
#> # ... with 1 more variable: carb <dbl>
```

Created on 2018-07-13 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

I'm thinking a helper rather than a new verb/generic because if we introduce a new verb it'll basically be a replacement for `coef`. If we do that it should part of a larger project that we do all at once to get it right (I'm convinced, or am at least naively optimistic, that some part of `tidymodels` will eventually grow into a `stats`/`lm` rewrite).
