### ISSUE TITLE
.resid for augment.mlogit?

### ISSUE THREAD

**Issue by jamesrrae** [tidymodels/broom#1055]
This is related to a previously raised issue (#1045). The changed prevented the error that I initially flagged, but I'm still not getting back `.resid` from augmented mlogit models. 

I'm probably missing something obvious, but when I look at the [mlogit tidiers](https://github.com/tidymodels/broom/blob/master/R/mlogit-tidiers.R) I don't see `.resid` anywhere. Could that be part of my problem?

**Comment by gregmacfarlane** [comment]
Residuals for a multinomial logit model are kind of a weird thing, so I don't use them very much. Sorry for leaving them out, but they were easy enough to put in.
