### ISSUE TITLE
Compute p-values for svyolr objects with variables containing more than two levels

### ISSUE THREAD

**Issue by gjones1219** [tidymodels/broom#1061]
### Tips for a helpful feature request: 

 * See our [contributing guidelines](https://github.com/tidymodels/tidymodels/blob/master/.github/CONTRIBUTING.md) and [development guide](https://www.tidymodels.org/contribute/) for more on design goals and how to contribute.

 * Please include a **minimal reproducible example,** a reprex, to demonstrate your feature idea when appropriate. If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/tidyverse/reprex#what-is-a-reprex)" and following the advice there. A reproducible example can be effective at demonstrating the case for a new feature. 

 * We don't want you to use confidential data; you can use a dataset from [modeldata](https://modeldata.tidymodels.org/reference/index.html), blind the data, or simulate other data to demonstrate your bug. The functions [`caret::twoClassSim()`](https://www.rdocumentation.org/packages/caret/versions/6.0-84/topics/SLC14_1) or [`caret::SLC14_1()`](https://www.rdocumentation.org/packages/caret/versions/6.0-84/topics/SLC14_1) might be good tools to simulate data for you. 

 * Unless the feature is explicitly about parallel processing, please run sequentially. _Even if_ it is about parallel processing, please make sure that it runs sequentially first.

 * Use `set.seed()` to ensure any randomness in your code is reproducible.

 * Please check <https://stackoverflow.com/> or <https://community.rstudio.com/> to see if someone has already asked the same question (see: [Yihui's Rule](https://yihui.name/en/2017/08/so-gh-email/)). 

 * You might need to install these packages to create a reproducible example or share session info:

```r
install.packages(c("reprex", "sessioninfo"), repos = "http://cran.r-project.org")
```

When you are ready to file the feature ✨ request, please delete everything above this line:
< -- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->

## Feature

In situations when ...

Hello! I am requesting that you all change the tidy function so that you can compute p values with models containing variables that have more than two levels. Currently, tidy does not allow one to compute p values for svyolr objects with variables containing more than two levels. Given that this criterion (models containing variables with more than two levels) excludes most models, it renders this functionality virtually useless. I would like to see this functionality added, as I need this in a tidy object to be able to make tables!

A suggestion, before I show the code below: maybe make the calculation of p-values based on something other than dropterm from the MASS package. There are other, less computationally intensive ways to calculate p-values for ordinal logistic regression models that see to be in practice -- maybe you base the functionality on that so that the p.value function in tidy works. 

Lastly, demonstrating my issues  below, with even the simplest of datasets/models:

library(survey)
#> Loading required package: grid
#> Loading required package: Matrix
#> Loading required package: survival
#> 
#> Attaching package: 'survey'
#> The following object is masked from 'package:graphics':
#> 
#>     dotchart
library(gtsummary)
#> #BlackLivesMatter

# Load example data
data(api)

# Create a survey design object
dclus1 <- svydesign(id=~dnum, weights=~pw, data=apiclus1, fpc=~fpc)

# Add an ordinal variable to the data
dclus1 <- update(dclus1, mealcat=cut(meals,c(0,25,50,75,100)))

# Fit an ordinal regression model
m <- svyolr(formula = mealcat ~ avg.ed + stype,
            design = dclus1)

#make p-value table
summary_table_m<- coef(summary(m))
pval <- pnorm(abs(summary_table_m[, "t value"]),lower.tail = FALSE)* 2
MwithP.values <- cbind(summary_table_m, "p.value" = round(pval,3))

#try to turn into a tidy object
MwithP.values<- broom::tidy(MwithP.values)
#> Warning: 'tidy.numeric' is deprecated.
#> See help("Deprecated")
#> Warning: `data_frame()` is deprecated as of tibble 1.1.0.
#> Please use `tibble()` instead.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_warnings()` to see where this warning was generated.
  #get error: 'tidy.numeric' is deprecated

ErrorTablewithMmodel <-
  tbl_regression(
    m,
    exponentiate = TRUE,  include = c(
      "avg.ed", "stype"
    ))  %>%  modify_table_body(
      mutate,
      est_ci = 
        dplyr::case_when(
          p.value < 0.001 ~ stringr::str_glue("{style_sigfig(estimate)}*** ({ci})"),
          p.value < 0.01 ~ stringr::str_glue("{style_sigfig(estimate)}** ({ci})"),
          p.value < 0.05 ~ stringr::str_glue("{style_sigfig(estimate)}* ({ci})"),
          !is.na(estimate) ~ stringr::str_glue("{style_sigfig(estimate)} ({ci})")
        )) %>%
  # add column header for new column
  modify_header(est_ci ~ "**aOR (95% CI)**") %>%
  # hide columns no longer needed
  modify_column_hide(column = c(estimate, ci, p.value)) %>%
  # add footnote about p-value stars
  modify_footnote(est_ci ~ "aOR = adjusted odds ratio; CI = confidence interval; * p<0.05; ** p<0.01; *** p<0.001") %>%
  modify_table_header(column = label, label = c("**Lifetime Use**"))
#> Error: Problem with `mutate()` input `est_ci`.
#> x object 'p.value' not found
#> ℹ Input `est_ci` is `dplyr::case_when(...)`.
    #get error: x obkect 'p.value' is not found
Created on 2021-10-30 by the reprex package (v0.3.0)

#simpler code for p-values of an svyolr object
summary_table_m<- coef(summary(m))
pval <- pnorm(abs(summary_table_m[, "t value"]),lower.tail = FALSE)* 2
MwithP.values <- cbind(summary_table_m, "p.value" = round(pval,3))

**Comment by simonpcouch** [comment]
Thanks for the issue! Here's what I see with an adaptation of your example code:

``` r
library(survey)
#> Loading required package: grid
#> Loading required package: Matrix
#> Loading required package: survival
#> 
#> Attaching package: 'survey'
#> The following object is masked from 'package:graphics':
#> 
#>     dotchart
library(broom)

data(api)

dclus1 <- svydesign(id=~dnum, weights=~pw, data=apiclus1, fpc=~fpc)

dclus1 <- update(dclus1, mealcat=cut(meals,c(0,25,50,75,100)))

m <- svyolr(formula = mealcat ~ avg.ed + stype,
            design = dclus1)

tidy(m)
#> # A tibble: 6 × 5
#>   term             estimate std.error statistic coef.type  
#>   <chr>               <dbl>     <dbl>     <dbl> <chr>      
#> 1 avg.ed             -2.81      1.16      -2.41 coefficient
#> 2 stypeH             -1.47      0.732     -2.01 coefficient
#> 3 stypeM             -0.661     0.328     -2.02 coefficient
#> 4 (0,25]|(25,50]     -9.64      3.76      -2.56 scale      
#> 5 (25,50]|(50,75]    -7.43      3.19      -2.33 scale      
#> 6 (50,75]|(75,100]   -5.82      2.98      -1.96 scale
```

<sup>Created on 2021-11-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Does this address your problem? If not, could you supply a reprex adding only what is necessary to replicate your issue?

**Comment by simonpcouch** [comment]
The steps of subsetting and `cbind`ing your summary table are likely introducing your trouble here. broom looks to object classes to figure out how to tidy an object, and tidying arbitrary data tables like that from `MwithP.values` is not well-defined.
