### ISSUE TITLE
`tidy.rma()` assuming that `ddf` is a scalar

### ISSUE THREAD

**Issue by wviechtb** [tidymodels/broom#1064]
The `tidy.rma()` function assumes that `x$ddf` is a scalar. See here:

https://github.com/tidymodels/broom/blob/4516a805430fae78fd70a6c0277b92fcce767ba9/R/rma-tidiers.R#L69

That may not be true. Consider the following example:
```
library(metafor)
library(broom)

dat <- dat.bangertdrowns2004

res <- rma(yi, vi, mods = ~ length + wic, data=dat)
tidy(res)

res <- rma(yi, vi, mods = ~ length + wic, data=dat, test="knha")
tidy(res)

res <- rma.mv(yi, vi, mods = ~ length + wic, random = ~ 1 | id, data=dat)
tidy(res)
```
No problems. But:
```
res <- rma.mv(yi, vi, mods = ~ length + wic, random = ~ 1 | id, data=dat, test="t")
tidy(res)
```
results in the warning:
```
Warning message:
In if (x$ddf > 0) qt(level/2, df = x$ddf, lower.tail = FALSE) else NA :
  the condition has length > 1 and only the first element will be used
```
because `ddf` is not a scalar:
```
res$ddf
```
yields:
```
intrcpt  length     wic
     41      41      41
```

The simple fix is simply to remove the `if()` check, that is, change the line to:
```
crit <- qt(level/2, df=x$ddf, lower.tail=FALSE)
```
I don't see how a `ddf` value could be negative anyway (given how the dfs are computed inside metafor).

**Comment by simonpcouch** [comment]
Just pushed a fix! Much appreciated. :)
