### ISSUE TITLE
Mismatch between p-values and confidence intervals in tidy.glm()

### ISSUE THREAD

**Issue by DanChaltiel** [tidymodels/broom#1074]
Hi,

There is sometimes a mismatch between the p-values and the confidence intervals in `tidy.glm()` (cf. https://github.com/tidymodels/broom/issues/989 locked).

Indeed, the default confidence interval are profile likelihood CIs, which are linked to the likelihood ratio test ( cf. https://stats.stackexchange.com/a/144608/81974), while the default p-value comes from a Wald test.

As a result, the output of `tidy.glm()` contains sometimes p-values and CI that don't match.

Here is a reproducible example of such a case:
``` r
library(tidyverse)
set.seed(579745)
N = 20
df = tibble(x1=rnorm(N), x2=rbinom(N, 1, 0.5))
m0 = glm(x2~x1, family=binomial(link="logit"), data=df)
m = broom::tidy(m0, conf.int=TRUE) %>% 
  tail(1)
m$p.value>0.05 #test is not significant
#> [1] TRUE
m$conf.low<0 | m$conf.high>0 #0 is not inside the confidence interval
#> [1] TRUE

# Corrections ------

##Using a LRT pvalue
drop1(m0, "x1", test = "LRT")["Pr(>Chi)"]#test becomes significant
#>        Pr(>Chi)  
#> <none>           
#> x1      0.04037 *
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

##Using a Wald confidence interval
confint.default(m0, "x1") #0 is now inside the confidence interval
#>      2.5 %   97.5 %
#> x1 -2.2448 0.110109
```

<sup>Created on 2022-01-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Obviously, I cherry-picked this seed (using a while loop), but it happens a lot on some of my datasets (I could not really get what condition triggers this though).

As `{broom}` is a broadly used package (and it is well deserved), I think this is a major problem, although rare, as it can lead to misunderstandings, especially on p-values believers (and they are legions).

Since I believe that the LRT is only applicable to whole variables and not levels of categorical, I think that Wald confidence intervals should become the default behavior in `tidy.glm()` when and if the feature is added.

(If there was actually a way to calculate a LRT on levels of categorical variables, then maybe default should be a LRT p-value with profile likelihood CIs)

**Comment by bbolker** [comment]
LRTs can be calculated on levels of categorical variables, but it's a bit ugly.  You would have to construct a model that zeroed out a single column of the model matrix, re-fit, and compare ...

**Comment by alexpghayes** [comment]
Thoughts:

- In some sense the correct behavior is just to match `glm` and `lm` behavior
- `lm` and `glm` behavior is slightly sub-standard here
- `broom` emphatically does not implement new estimators from scratch

I think the right approach here is some sort of optional argument `conf.method` accepting params:

- `"default"` -- matches `lm`/`glm` results
- `"wald"`
- `"likelihood"`

And then updating the documentation for `conf.int` in `lm` and `glm` tidiers.

**Comment by simonpcouch** [comment]
With an eye for discussion in https://github.com/tidymodels/broom/pull/1060, going to go ahead and close.
