### ISSUE TITLE
Add tidiers for vegan objects

### ISSUE THREAD

**Issue by colinbrislawn** [tidymodels/broom#1075]
## Feature

Add tidiers for objects from the [vegan](https://github.com/vegandevs/vegan) package for community ecology. This reopens old issue #23

Example usage:
```R
adonis(dist.jaccard ~ group, data = df.samples.groups) %>% tidy()
```

Current workaround to get a data.frame from an `vegan::adonis()` output.

```R
(adonis(dist.jaccard ~ group, data = df.samples.groups))$aov.tab %>% data.frame()
```

I can put together a real example using `reprex` to help this get started. Feel free to close this and reopen #23 if that's best

**Comment by simonpcouch** [comment]
Thanks for the issue! Apologies for the delay here.

As of the 1.0.0 release of the package, we're [not accepting new tidiers to broom](https://broom.tidymodels.org/articles/maintenance.html), instead asking that they are implemented/maintained in the model-supplying package (i.e. vegan). 

[This vignette](https://cran.r-project.org/web/packages/broom/vignettes/adding-tidiers.html) points to some resources we've put together to help with implementing new tidiers in model-supplying packages.

**Comment by colinbrislawn** [comment]
Congrats on version 1.0.0! I'll move this issue over to the Vegan package.
