### ISSUE TITLE
Bug in tests: dplyr::last_col() used incorrectly

### ISSUE THREAD

**Issue by MichaelChirico** [tidymodels/broom#1077]
https://github.com/tidymodels/broom/blob/f3b8ac1730e3e33eb39eaf54ab1b4d4e0547afc4/tests/testthat/test-cmprsk.R#L39-L52

Fails if `_R_CHECK_LENGTH_1_LOGIC2_=true` is set:

```
Sys.setenv("_R_CHECK_LENGTH_1_LOGIC2_" = "true")
  expect_equal(
    summary(fit, conf.int = 0.99)$conf.int %>% 
      log() %>%
      unname() %>%
      as.data.frame() %>% 
      dplyr::select(dplyr::last_col(1:0)) %>%
      unclass() %>%
      unname(),
    td3 %>% 
      dplyr::select(conf.low, conf.high)  %>%
      unclass() %>%
      unname(),
  )
# Error: 'length(x) = 2 > 1' in coercion to 'logical(1)'
```

The issue is `dplyr::last_col(1:0)`. The function is only designed to handle scalar offsets.

I'm not sure the intention of the test, so filing an issue instead of a PR.

**Comment by simonpcouch** [comment]
Thanks for the issue! This seems worth addressing. I'm taking some time away at the moment, but will look into the blames here and make adjustments as needed sooner than later.🙂

**Comment by simonpcouch** [comment]
This will be fixed in the next release of broom! Looks like the off-label usage here resulted in selecting off the last two columns. Thanks for the holler.
