### ISSUE TITLE
'tidy_wide' For when you need more than glance but still want a 1 line output

### ISSUE THREAD

**Issue by RichardJActon** [tidymodels/broom#1091]
I frequently find myself in a situation where I am looking for more details that I get from glance but I still want a result that occupies a single line in a tibble. 
I almost always find myself copying this function into projects where I'm using broom with simple linear models i R. I don't know if this is a common thing that others encounter but if so then maybe convenience functions to make 'wide' outputs from glance & tidy with consistent column names might be a useful addition to broom?

```
#' tidy_wide
#'
#' used the broom packages tidy and glance functions to summaries the model
#' reformatting the output of tidy to provide just the estimates and p-values
#' for all coefficients in a wide, single row, format.
#'
#' @param model a model object
#'
#' @export
tidy_wide <- function(model) {
	g <- broom::glance(model)
	colnames(g) <- gsub("\\.", "_", colnames(g)) # NO dots in names! 
        # (my preference not strictly necessary)
	dplyr::bind_cols(
		g,
		broom::tidy(model) %>%
			dplyr::select(term, estimate, p_value = `p.value`) %>%
                        # I find `intercept` is an easier to handle column name the `(Intercept)`
			dplyr::mutate(
				term = ifelse(term == "(Intercept)", "intercept", term)
			) %>%
			tidyr::pivot_wider(
				names_from = "term", values_from = c("estimate", "p_value")
			)
	)
}
```

**Comment by simonpcouch** [comment]
Thanks for the issue! Given where this package is at in its lifecycle, I'm not sure introducing another generic is the right move for the package.

I'm glad that you've shared this publicly, though—hopefully others will find this useful.
