### ISSUE TITLE
Computing p-values for svyolr objects

### ISSUE THREAD

**Issue by gjones1219** [tidymodels/broom#1107]
Hello! I have written on this issue before, but am coming back to it because I do not think it was addressed before. You responded to my comment previously, and I am appreciative and apologize for not responding until now, but I do not think the functionality I was looking for was added.

I am writing to see if it would be possible for you all to assess p-values for svyolr objects. This functionality seems to be missing from the package, and would be invaluable for significance testing for ordinal logistic regression models. Attaching reproducible code for your review:

#######

library(broom)
library(survey)

data(api)
dclus1<-svydesign(id=~dnum, weights=~pw, data=apiclus1, fpc=~fpc)
dclus1<-update(dclus1, mealcat=cut(meals,c(0,25,50,75,100)))

m<-svyolr(mealcat~avg.ed+mobility+stype, design=dclus1)
m

broom::tidy(m, conf.int = FALSE,
            conf.level = 0.95,
            exponentiate = FALSE,
            p.values = TRUE)

#Usually provides an error message saying this doesn't run.

Thank you, and please let me know if I can further clarify this request!

Thanks,
gjones1219

**Comment by gjones1219** [comment]
Sorry about that! Here you go!

library(broom)
library(survey)
#> Loading required package: grid
#> Loading required package: Matrix
#> Loading required package: survival
#> 
#> Attaching package: 'survey'
#> The following object is masked from 'package:graphics':
#> 
#>     dotchart
library(reprex)


data(api)
dclus1<-svydesign(id=~dnum, weights=~pw, data=apiclus1, fpc=~fpc)
dclus1<-update(dclus1, mealcat=cut(meals,c(0,25,50,75,100)))

m<-svyolr(mealcat~avg.ed+mobility+stype, design=dclus1)
m
#> Call:
#> svyolr(mealcat ~ avg.ed + mobility + stype, design = dclus1)
#> 
#> Coefficients:
#>     avg.ed   mobility     stypeH     stypeM 
#> -2.6999217  0.0325042 -1.7574715 -0.6191463 
#> 
#> Intercepts:
#>   (0,25]|(25,50]  (25,50]|(50,75] (50,75]|(75,100] 
#>        -8.857919        -6.586464        -4.924938

broom::tidy(m, conf.int = FALSE,
            conf.level = 0.95,
            exponentiate = FALSE,
            p.values = TRUE)
#> Error in UseMethod("extractAIC"): no applicable method for 'extractAIC' applied to an object of class "svyolr"
Created on 2022-06-08 by the [reprex package](https://reprex.tidyverse.org/) (v2.0.1)

**Comment by simonpcouch** [comment]
Thanks! A slightly more minimal reprex:

``` r
library(broom)
library(survey)
#> Loading required package: grid
#> Loading required package: Matrix
#> Loading required package: survival
#> 
#> Attaching package: 'survey'
#> The following object is masked from 'package:graphics':
#> 
#>     dotchart

data(api)
dclus1 <- svydesign(id = ~dnum, weights = ~pw, data = apiclus1, fpc = ~fpc)
dclus1 <- update(dclus1, mealcat = cut(meals, c(0, 25, 50, 75, 100)))

m <- svyolr(mealcat ~ avg.ed + mobility + stype, design = dclus1)

tidy(m, p.values = TRUE)
#> Error in UseMethod("extractAIC"): no applicable method for 'extractAIC' applied to an object of class "svyolr"
```

<sup>Created on 2022-06-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The `tidy.svyolr()` tidier is a light wrapper around `tidy.polr()`. However, the implementation for p-value calculation in `tidy.polr()` is both computationally intensive and specific to that model, so the `p.values` argument to `tidy.svyolr()` is now ignored and will raise a warning when passed. 

I appreciate you noting this!

**Comment by gjones1219** [comment]
Hi Simon,

Thanks for responding however I am not sure I understand your answer. Also, I have the latest version of broom (0.8.0, I believe; please let me know if there might be a newer one) but do not see the tidy.svyolr() or tidy.poly() functions. Can you please advise here? Thanks!

Grant

**Comment by simonpcouch** [comment]
Sure thing—`tidy.svyolr` and `tidy.poly` are _S3 methods_. You can read about those methods with `?tidy.svyolr` or `?tidy.poly`, and learn more about them [here](https://adv-r.hadley.nz/s3.html). :)
