### ISSUE TITLE
Internal documentation typo

### ISSUE THREAD

**Issue by johanneskoch94** [tidymodels/broom#1111]
https://github.com/tidymodels/broom/blob/1cc3a172ef9ea2334b13db9abf480f78b1388fd1/R/utilities.R#L224-L227

Just a small typo: the fixed effect panel model, for which `stats::predict()` returns incorrect values, is called by `plm(..., model="within")` - not `plm(..., model="pooling")`

**Comment by simonpcouch** [comment]
Thanks for pointing this out! Will correct this the next time I triage broom issues.
