### ISSUE TITLE
Export tidier for `cmprsk::cuminc()` ?

### ISSUE THREAD

**Issue by ddsjoberg** [tidymodels/broom#1117]
A `tidy()` method for `cmprsk::cuminc()` (competing risks cumulative incidence) objects would be super useful. I gather you're not looking for more tidiers in broom, BUT I think there are a few reasons why I think it makes sense to add _this_ tidier to {broom}.
- {broom} already houses the tidy method for `cmprsk::crr()`, a similar function from the same package.
- It would be strange to house tidiers for similar methods from the same package in different spaces.
- The {cmprsk} package has been on CRAN since 2001 and is incredibly stable: I would expect maintenance of this new tidier to be minimal/non-existant. 
- Supporting `cmprsk::cuminc()` is analogous to supporting `survival::survfit()` (where `cmprsk::crr()` is similar to `survival::coxph()`, both already supported in broom)
- I am happy to add the tidier and maintain as needed 💯 

Here's what I think the output would look like

``` r
p <- cmprsk::cuminc(...)

tidy(p)
#> # A tibble: 228 × 12
#>     time outcome  strata estim…¹ std.e…² conf.low conf.…³ n.risk n.event n.cen…⁴
#>    <dbl> <chr>    <fct>    <dbl>   <dbl>    <dbl>   <dbl>  <int>   <int>   <int>
#>  1  0    death f… Drug A  0       0      NA       NA          98       0       0
#>  2  3.53 death f… Drug A  0       0      NA       NA          98       0       0
#>  3  7.27 death f… Drug A  0.0102  0.0102  8.84e-4  0.0503     97       1       0
#>  4  7.38 death f… Drug A  0.0204  0.0144  3.90e-3  0.0652     96       1       0
#>  5  8.37 death f… Drug A  0.0204  0.0144  3.90e-3  0.0652     95       0       0
#>  6 10.1  death f… Drug A  0.0204  0.0144  3.90e-3  0.0652     94       0       0
#>  7 10.3  death f… Drug A  0.0204  0.0144  3.90e-3  0.0652     93       0       0
#>  8 10.5  death f… Drug A  0.0204  0.0144  3.90e-3  0.0652     92       0       0
#>  9 11.4  death f… Drug A  0.0306  0.0175  8.17e-3  0.0798     91       1       0
#> 10 11.8  death f… Drug A  0.0306  0.0175  8.17e-3  0.0798     90       0       0
#> # … with 218 more rows, 2 more variables: cum.event <int>, cum.censor <int>,
#> #   and abbreviated variable names ¹​estimate, ²​std.error, ³​conf.high, ⁴​n.censor
#> # ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names
```

<sup>Created on 2022-08-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Thank you 🍁

**Comment by simonpcouch** [comment]
Thanks for the issue!

As you note, as of of the 1.0.0 release of the package, we're [not accepting new tidiers to broom](https://broom.tidymodels.org/articles/maintenance.html), instead asking that they are implemented/maintained in the model-supplying package (i.e. cmprsk). You make some good arguments as to why this ought to live in broom, but—we've struggled with maintaining this boundary consistently for some time, and I think the package will indeed be better off if we stick to those guidelines.

Thanks again for the thoughtful description, and your attention to this package's dev over the last couple years is much appreciated.🧹

**Comment by ddsjoberg** [comment]
Thanks @simonpcouch ! I understand where you're coming from. 

Unfortunately, a legacy package like cmprsk with no dependencies would not accept a tidier, and there is no place for this tidier to live.

If you change your mind, let me know :)
