### ISSUE TITLE
Support for mlm models: `glance.mlm()`

### ISSUE THREAD

**Issue by friendly** [tidymodels/broom#1119]
This is a follow-up to #903, where I asked for support for `car::Anova()` and other aspects related to multivariate linear models.
My intent is that linear models with multiple responses should be treated in broom as first class citizens .

Here, I'd like to propose a `glance.mlm()` method, which would do the same as `glance.lm()`, but give a separate row for each response variable.

Currently, I get:

    > library(broom)
    > iris.mod <- lm(cbind(Sepal.Length, Sepal.Width, Petal.Length, Petal.Width) ~ Species, data=iris)
    > glance(iris.mod)
    Error in eval_tidy(xs[[j]], mask) : object 'r.squared' not found
    In addition: Warning message:
    The `glance()` method for objects of class `mlm` is not maintained by the broom team, and is only supported through the `lm` tidier method. Please be cautious in interpreting and reporting broom output.

I've written a candidate `glance.mlm()` method, presently in my `heplots` package, but not yet incorporated into the package.
See the devel version at: https://github.com/friendly/heplots, where it is now in the `extra/` folder.

    #' Glance at an mlm object
    #' 
    #' This function takes an "mlm" object, fit by \code{\link[stats](lm)} with a multivariate response.
    #' The goal is to return something analogous to \code{\link[broom](glance.lm)} for a univariate response linear model.
    #' 
    #' In the multivariate case, it returns a \code{\link[tibble](tibble)} with one row for each
    #' response variable, containing goodness of fit measures, F-tests and p-values.
    #' 
    #' @param x An \code{mlm} object created by \code{\link[stats]{lm}}, i.e., with a multivariate response.
    #' @param ... Additional arguments. Not used.
    #' @method glance mlm
    #' @return A \code{\link[tibble]{tibble}} with one row for each response variable and the columns:
    #' \describe{
    #'   \item{\code{r.squared}}{R squared statistic, or the percent of variation explained by the model.}
    #'   \item{\code{adj.r.squared}}{Adjusted R squared statistic, which is like the R squared statistic except taking degrees of freedom into account.}
    #'   \item{\code{sigma}}{Estimated standard error of the residuals}
    #'   \item{\code{fstatitic}}{Overall F statistic for the model}
    #'   \item{\code{numdf}}{Numerator degrees of freedom for the overall test}
    #'   \item{\code{dendf}}{Denominator degrees of freedom for the overall test}
    #'   \item{\code{p.value}}{P-value corresponding to the F statistic}
    #'   \item{\code{nobs}}{Number of observations used}
    #' }
    #' @importFrom magittr extract
    #' @importFrom purrr map_dfr map
    #' @importFrom tibble as_tibble
    #' @export
    #' @examples 
    #' iris.mod <- lm(cbind(Sepal.Length, Sepal.Width, Petal.Length, Petal.Width) ~ Species, data=iris)
    #' glance(iris.mod)

    glance.mlm <- function(x, ...) {
    #  warn_on_subclass(x, "glance")
      int_only <- nrow(coefficients(x)) == 1

      sumry <- summary(x)
      response <- sub("Response ", "", names(sumry))
      # basic model summary statistics
      stats <- purrr::map_dfr(sumry, magrittr::extract, c("r.squared", "adj.r.squared", "sigma"))

      # get the F statistic & df for each response
      fstats <- purrr::map(sumry, magrittr::extract, c("fstatistic"))
      fstats <- t(as.data.frame(fstats))
      colnames(fstats)[1] <- "fstatistic"
      row.names(fstats) <- NULL

      # handle intercept-only case
      p.value = if (!int_only) {
        pf(fstats[,"fstatistic"], fstats[,"numdf"], 
           fstats[,"dendf"], lower.tail = FALSE)
        }
        else NA_real_
      if(int_only) {
        fstats[,"numdf"] <- NA_real_
        fstats[,"dendf"] <- NA_real_
      }

      nobs <- nobs(x)
      
      # join results together
      res <- cbind(response, stats, fstats, p.value, nobs)
      tibble::as_tibble(res)
    }

Testing this, I get what I am looking for:

    > glance(iris.mod)
    # A tibble: 4 x 9
      response     r.squared adj.r.squared sigma fstatistic numdf dendf  p.value  nobs
      <chr>            <dbl>         <dbl> <dbl>      <dbl> <dbl> <dbl>    <dbl> <int>
    1 Sepal.Length     0.619         0.614 0.515      119.      2   147 1.67e-31   150
    2 Sepal.Width      0.401         0.393 0.340       49.2     2   147 4.49e-17   150
    3 Petal.Length     0.941         0.941 0.430     1180.      2   147 2.86e-91   150
    4 Petal.Width      0.929         0.928 0.205      960.      2   147 4.17e-85   150

I'd appreciate comments on this this draft of the function.

It would be better for this method to be included in `broom` rather than in my `heplots` package.

**Comment by simonpcouch** [comment]
Thanks for the issue!

As of the 1.0.0 release of the package, we're [not accepting new tidiers to broom](https://broom.tidymodels.org/articles/maintenance.html), so your proposed function unfortunately won't make it to broom itself.

If you find the function you've drafted helpful for your use case, you can of course use it as you please, though the output of `glance()` methods as defined in this package is a **1-row** tibble. We've implemented a `type` argument in some `tidy()` methods, where the `response` column as shown would be named `term`, that would accommodate output like you've shown in `tidy.mlm`, though that's no longer in the scope of development on this package.

**Comment by friendly** [comment]
`tidy.mlm()` already does the right thing, with rows combining `response` and `term`.  The natural extension of a `glance` method would have one row **for each response**.  I urge you to re-consider, but for now I'll just put it in my package.

    > tidy(iris.mod)
    # A tibble: 12 x 6
       response     term              estimate std.error statistic   p.value
       <chr>        <chr>                <dbl>     <dbl>     <dbl>     <dbl>
     1 Sepal.Length (Intercept)          5.01     0.0728     68.8  1.13e-113
     2 Sepal.Length Speciesversicolor    0.930    0.103       9.03 8.77e- 16
     3 Sepal.Length Speciesvirginica     1.58     0.103      15.4  2.21e- 32
     4 Sepal.Width  (Intercept)          3.43     0.0480     71.4  5.71e-116
     5 Sepal.Width  Speciesversicolor   -0.658    0.0679     -9.69 1.83e- 17
     6 Sepal.Width  Speciesvirginica    -0.454    0.0679     -6.68 4.54e- 10
     7 Petal.Length (Intercept)          1.46     0.0609     24.0  9.30e- 53
     8 Petal.Length Speciesversicolor    2.80     0.0861     32.5  5.25e- 69
     9 Petal.Length Speciesvirginica     4.09     0.0861     47.5  4.11e- 91
    10 Petal.Width  (Intercept)          0.246    0.0289      8.50 1.96e- 14
    11 Petal.Width  Speciesversicolor    1.08     0.0409     26.4  1.25e- 57
    12 Petal.Width  Speciesvirginica     1.78     0.0409     43.5  7.95e- 86
