### ISSUE TITLE
Option to calculate confidence intervals as 1.96*SE

### ISSUE THREAD

**Issue by lukepilling** [tidymodels/broom#1125]
First, wonderful package, very useful and flexible. However, I regularly find that when `conf.int=TRUE` the `tidy()` function can take many minutes to return the summary table. At first I was confused by this, until seeing in the `utilities.R` file the relevant function (`broom_confint()`) makes use of `confint()`, which takes time due to bootstrapping. When the sample size and/or number of exposures becomes large, this results in slow computation. 

However I expect that in the majority of cases providing 95% Confidence Intervals calculated by returning the estimate +/- 1.96*SE would be appropriate. (Or another level if requested) Could this be implemented?

I include here a reprex demonstrating that the tidy (`confint`) method is very slow compared to "just" returning the manual (1.96*SE) CIs, and the results are not meaningfully different.

Many thanks,
Luke

```r
library(tidyverse)
library(broom)
library(rbenchmark)

set.seed(123)

## create continuous exposure and outcome (highly correlated)
x = runif(10000, 1, 5)
y = x + rnorm(10000)

## create categorical (quantiles) version of `x` -- to later demonstrate it takes longer with more exposures
x_qt10 = as.factor(findInterval(x, quantile(x, probs = seq(0.1, 1, 0.1), na.rm=TRUE), rightmost.closed=TRUE) + 1)

## combine
df = tibble(x,y,x_qt10)

##
##
## model of continuous x on y
fit_lm1 = glm(y ~ x, data = df)

## calculate CIs. Compare `tidy` method to `manual`
benchmark("tidy CIs"    = { fit_lm1_tidy1 = tidy(fit_lm1, conf.int=TRUE) },
          "manual CIs"  = { fit_lm1_tidy2 = tidy(fit_lm1) %>% mutate(lci=estimate-(1.96*std.error), uci=estimate+(1.96*std.error)) })
#>         test replications elapsed relative user.self sys.self user.child sys.child
#> 2 manual CIs          100    0.39    1.000      0.39     0.00         NA        NA
#> 1   tidy CIs          100   10.44   26.769     10.41     0.03         NA        NA

## compare CIs from broom/confint to those calculated "manually"
data.frame(tidy_lci=fit_lm1_tidy1$conf.low, tidy_uci=fit_lm1_tidy1$conf.high, manual_lci=fit_lm1_tidy2$lci, manual_uci=fit_lm1_tidy2$uci)
#>      tidy_lci   tidy_uci  manual_lci manual_uci
#> 1 -0.02244986 0.08722226 -0.02245087 0.08722327
#> 2  0.97271488 1.00696027  0.97271456 1.00696058

##
##
## model of 10 quantiles on y
fit_lm2 = glm(y ~ x_qt10, data = df)

## calculate CIs. Compare `tidy` method to `manual`
benchmark("tidy CIs"    = { fit_lm2_tidy1 = tidy(fit_lm2, conf.int=TRUE) },
          "manual CIs"  = { fit_lm2_tidy2 = tidy(fit_lm2) %>% mutate(lci=estimate-(1.96*std.error), uci=estimate+(1.96*std.error)) })
#>         test replications elapsed relative user.self sys.self user.child sys.child
#> 2 manual CIs          100    0.41    1.000      0.41     0.00         NA        NA
#> 1   tidy CIs          100  106.22  259.073    105.71     0.25         NA        NA

## compare CIs from broom/confint to those calculated "manually"
data.frame(tidy_lci=fit_lm2_tidy1$conf.low, tidy_uci=fit_lm2_tidy1$conf.high, manual_lci=fit_lm2_tidy2$lci, manual_uci=fit_lm2_tidy2$uci)
#>     tidy_lci tidy_uci manual_lci manual_uci
#> 1  1.1795716 1.304530  1.1795704  1.3045313
#> 2  0.2768399 0.453558  0.2768383  0.4535597
#> 3  0.6776729 0.854391  0.6776713  0.8543926
#> 4  1.0788242 1.255542  1.0788225  1.2555439
#> 5  1.4379012 1.614619  1.4378996  1.6146209
#> 6  1.8634412 2.040159  1.8634396  2.0401610
#> 7  2.2922514 2.468969  2.2922497  2.4689711
#> 8  2.5767003 2.753418  2.5766987  2.7534200
#> 9  3.0297996 3.206518  3.0297980  3.2065193
#> 10 3.4727892 3.649507  3.4727876  3.6495090
```

**Comment by simonpcouch** [comment]
Thanks for the issue! Related to <https://github.com/tidymodels/broom/issues/989> and friends. Will close in favor of those.

A few comments related to this issue specifically, for those who may come across in the future:

> …makes use of `confint()`, which takes time due to bootstrapping

`confint.glm` calculates confidence intervals via profile likelihood by default. You’re correct that some other `confint` methods dispatched to via broom make use of bootstrapping, though.

Also, this behavior and speedup isn’t consistent across `confint` methods. In this example, with Gaussian family, we can just equivalently use `lm`, whose `confint` method (from stats rather than MASS) is often a good bit more efficient:

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(broom)
library(rbenchmark)

set.seed(123)

x <- runif(10000, 1, 5)
y <- x + rnorm(10000)
df <- data.frame(x = x, y = y)
fit_lm_2 <- lm(y ~ x, data = df)

benchmark("tidy CIs"   = {tidy(fit_lm_2, conf.int=TRUE)},
          "manual CIs" = {tidy(fit_lm_2) %>% mutate(lci = estimate - (1.96 * std.error), uci = estimate + (1.96 * std.error))})
#>         test replications elapsed relative user.self sys.self user.child
#> 2 manual CIs          100   0.235    1.000      0.23    0.005          0
#> 1   tidy CIs          100   0.321    1.366      0.31    0.010          0
#>   sys.child
#> 2         0
#> 1         0

x_2 <- cut(x, 10)

fit_lm_3 <- lm(y ~ x_2, data = df)

benchmark("tidy CIs"   = {tidy(fit_lm_3, conf.int=TRUE)},
          "manual CIs" = {tidy(fit_lm_3) %>% mutate(lci = estimate - (1.96 * std.error), uci = estimate + (1.96 * std.error))})
#>         test replications elapsed relative user.self sys.self user.child
#> 2 manual CIs          100   0.234    1.000     0.230    0.004          0
#> 1   tidy CIs          100   0.298    1.274     0.291    0.007          0
#>   sys.child
#> 2         0
#> 1         0
```

> the results are not meaningfully different

“Meaningfully different” is context-dependent. The similarities you see in CIs in this case can be quite irregular for some other methods. The `confint` generic exists—and we make use of it—because authors of model-supplying packages are best-equipped to make relevant considerations for computing confidence intervals in a principled way. 

<sup>Created on 2022-11-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by lukepilling** [comment]
Many thanks for taking the time to reply and explain this. 

It absolutely makes sense to use `confit` as the default so that CIs are calculated as you say. I use `glm()` for logit analysis also, so although `lm()` is nice for linear, the logistic CIs still take a long time and are not meaningfully different (whatever that means 😉). 

I think for me I will make a little wrapper function to get the results from `tidy()` and add the CIs based on est+/-1.96*SE
