### ISSUE TITLE
migrate (and enhance) zeroinfl and hurdle methods from poissonreg package?

### ISSUE THREAD

**Issue by bbolker** [tidymodels/broom#1132]
The [poissonreg package](https://github.com/tidymodels/poissonreg) (which is already under the `tidymodels` umbrella) has tidiers for `hurdle` and `zeroinfl` models from the `pscl` package.  These are relatively hard to discover: could they (with permission from the `poissonreg` maintainer) be migrated into `broom`?

In the process it would be good to

- implement a `conf.int` argument 
- implement an `exponentiate` argument (makes sense for both the conditional and zero components, i.e. differences in log-counts/log-fold changes → ratios or fold changes vs. log-odds to odds ratios)

right now these are both silently ignored.

Might submit a PR if encouraged.

**Comment by hfrick** [comment]
Hi Ben, I maintain poissonreg and think broom is a good place for those tidiers to live in. I spoke with Simon and I'll make PRs moving them here (as they currently are) - he'll be the point of contact for any changes to them 👍

**Comment by bbolker** [comment]
Thanks!  I'll leave this open for the enhancement requests (working `conf.int` and `exponentiate` arguments, warning/error when ignoring arguments in `...`)

**Comment by simonpcouch** [comment]
Thanks for the issue, @bbolker! After some further internal discussion, we've decided to leave those tidiers where they're at—feel free to PR those improvements to poissonreg, if you're so inclined.🙂

Generally, in tidymodels, we define methods for objects in the package where the object is defined. In light of your issue, we considered that tidiers for objects defined in non-tidymodels packages that don't define their own tidiers should live in broom. We ultimately decided not to enforce this, as:

* Managing dependencies/namespaces during the transition is a bit gnarly (see #1133), 
* Migrating tidiers here from parsnip extensions where they're needed makes those extensions more indirect-dependency-heavy, and
* We're working on a tool that makes it more easy to find tidiers. broom.mixed, as well as all broom and generics reverse dependencies, will be indexed and searchable in that tool, so hopefully this will ease the process of locating needed tidiers if they don't live in broom or the model-supplying package.
