### ISSUE TITLE
Time to replace retiring spatial packages

### ISSUE THREAD

**Issue by rsbivand** [tidymodels/broom#1142]
**broom** suggests **maptools**, which will be archived in October. This currently harms **tipsae**, which uses `broom::tidy()` on an **sp** object, and reaches https://github.com/tidymodels/broom/blob/d999a2b5e2492fc915642fb8759725f16e53bf09/R/sp-tidiers.R#L31. When **maptools** is not available, **tipsae** fails. The function being used is similar to `sf::aggregate()`. 

For more general details, see: rgdal, rgeos and maptools will retire during 2023. As is explained in this presentation: https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf, package maintainers should aim to have replaced probably redundant dependencies on these packages by June 2023 (before the northern hemisphere tutorial season), and certainly by October 2023 when the packages will be archived. The presentation was recorded: https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1. Further details in blogs: https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html, and in tabulations on https://github.com/r-spatial/evolution.

**Comment by simonpcouch** [comment]
Thanks for the thorough description! Will make this happen before the next release.

**Comment by simonpcouch** [comment]
The next release will go out with the changes in [0f5cf41](https://github.com/tidymodels/broom/commit/0f5cf411d18098604eb9c0995899c49a653dc468).

A few months later, we'll follow up with a hard-deprecation of the `region` argument to that tidier to remove the dependency on maptools (and rgeos). Depending on how revdeps look, we'll either move forward with the deprecation of sp tidiers then or give those tidiers a few extra months.
