### ISSUE TITLE
Remove single row summary restriction in `glance()`

### ISSUE THREAD

**Issue by mccarthy-m-g** [tidymodels/broom#1149]
## Problem

`glance()` currently restricts summary statistics to be reported in a single row. For example, the description of `?generics::glance` states that it is used to 'Construct a single row summary "glance" of a model, fit, or other object'.

For many models, returning a single row of summary statistics with `glance()` is natural. However, for some models, there is no natural way to return their summary statistics in a single row. As a consequence, `glance()` explicitly lacks support for these models. For example, in the reprex below Model 1 works but Model 2 returns an error:

``` r
library(survival)
library(broom)

# Model 1, where a one line summary is natural
veterans_fit_1 <- survfit(Surv(time, status) ~ 1, data = veteran)
glance(veterans_fit_1)
#> # A tibble: 1 × 10
#>   records n.max n.start events rmean rmean.std.er…¹ median conf.…² conf.…³  nobs
#>     <dbl> <dbl>   <dbl>  <dbl> <dbl>          <dbl>  <dbl>   <dbl>   <dbl> <int>
#> 1     137   137     137    128  133.           15.3     80      52     105   137
#> # … with abbreviated variable names ¹​rmean.std.error, ²​conf.low, ³​conf.high

# Model 2, where a multi-line summary is natural
veterans_fit_2 <- survfit(Surv(time, status) ~ trt, data = veteran)
glance(veterans_fit_2)
#> Error in glance.survfit(veterans_fit_2): Cannot construct a glance of a multi-strata survfit object.
```

<sup>Created on 2023-03-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

## Request

Rather than defining `glance()` as a method that 'Construct[s] a single row summary "glance" of a model, fit, or other object', I propose that that this restriction is loosened to something along the lines of:

> Construct a tidy summary "glance" of a model, fit, or other object.

In Model 2 above, a tidy summary would be a natural extension to the single row summary we get for Model 1:

``` r
library(survival)
library(purrr)
library(broom)

veterans_fit_2 <- survfit(Surv(time, status) ~ trt, data = veteran)

# Construct a tidy summary, which is a natural extension of the single line
# summary for this class of model
veterans_fit_2_glance <- map_df(
  c("trt=1" = 1, "trt=2" = 2),
  function(.x) glance(update(veterans_fit_2, subset = (trt == .x))),
  .id = "strata"
)

veterans_fit_2_glance
#> # A tibble: 2 × 11
#>   strata records n.max n.start events rmean rmean…¹ median conf.…² conf.…³  nobs
#>   <chr>    <dbl> <dbl>   <dbl>  <dbl> <dbl>   <dbl>  <dbl>   <dbl>   <dbl> <int>
#> 1 trt=1       69    69      69     64  124.    14.8  103        59     132    69
#> 2 trt=2       68    68      68     64  142.    26.8   52.5      44      95    68
#> # … with abbreviated variable names ¹​rmean.std.error, ²​conf.low, ³​conf.high
```

<sup>Created on 2023-03-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The need for tidy summaries extends to other classes of models too; for example, @friendly made a similar request in https://github.com/tidymodels/broom/issues/1119#issuecomment-1258661042:

> The natural extension of a glance method [for linear models with multiple responses] would have one row for each response.

## Benefit

Removing the single row summary restriction in `glance()` means that it can be used with more models, allowing users more consistent workflows when doing statistics in the tidyverse. This is also nice for teaching and tutorials, as it avoids situations where you recommend using `glance()` for Model 1, but for Model 2 either recommend the approach I used above or to use base R methods.

The main benefit to keeping the restriction is that it restricts the amount of code that needs to be maintained in broom, since tidy summaries in `glance()` would likely require new additions to the internals of multiple model classes the package supports (I'm not sure how many models or how much new code would come of this change). But otherwise I'm not sure why the restriction exists (is it for historical reasons?).

**Comment by friendly** [comment]
I totally agree. Other use cases for an extended glance, as I mentioned in #1119 are multivariate response models, where we want a glance at each of the univariate models.

Yet another use case is models for polytomous responses, eg, `nnet:multinom()` where the model for an $m$ category response entails a set of $m-1$ submodels.

**Comment by simonpcouch** [comment]
Thanks for the issue! Wanted to let this issue sit for a bit in case others wanted to chime on. My [response to the previous issue](https://github.com/tidymodels/broom/issues/1119#issuecomment-1258563072) you've linked to applies here; we won't be extending the meaning of the core verbs at this point in the package's lifecycle.

> The main benefit to keeping the restriction is that it restricts the amount of code that needs to be maintained in broom, since tidy summaries in glance() would likely require new additions to the internals of multiple model classes the package supports (I'm not sure how many models or how much new code would come of this change). But otherwise I'm not sure why the restriction exists (is it for historical reasons?).

The benefits of type-stability generally apply to those of using `glance()`—consistency, programmability, teachability, maintainability.

I would note that this logic isn't hard-coded in the generic itself, but in the `glance.survfit()` method. There is no "restriction" on external developers writing glance methods via the `generics::glance()` generic. In this case, the "multi-strata survfit object" error specifically has been around [since these tidiers were first merged 9 years ago](https://github.com/tidymodels/broom/commit/9f9aba7d4669f902f0bd79bb8bd475be7eb14f5a).

**Comment by mccarthy-m-g** [comment]
Thanks for responding! It would be great if you could leave this open for further discussion and consideration.

Alternatively, @hadley, would you be open to discussing this in the `generics` repository since that's at the root of this issue?

## Re: `generics::glance()`

I'm aware there's no code restriction preventing developers from using the `generics::glance()` generic to return multiple rows (or anything else for that matter). The "restriction" is normative and reinforced through the documentation of `?generics::glance`, which states that it is used to "Construct a single row summary "glance" of a model, fit, or other object" and that "glance methods always return either a one-row data frame (except on NULL, which returns an empty data frame)". 

The purpose of my original comment was to question this norm, as I think it actively gets in the way of things like consistency, programmability, and teachability by restricting where `glance()` can be used by developers if they want to use it in the normative way. Yes, it's possible to use the glance generic in non-normative ways (e.g., by returning multi-row model summaries), but I don't think it's great practice to write class-specific methods that clash with the documentation of their generic.

A more desirable solution would be to make `generics::glance()`'s documentation inclusive for multi-row summaries, so that it's possible to write glance methods for models where a multi-row summary is natural without clashing with the documentation of the generic.

## Re: `broom`

I understand that, e.g., the `glance.survfit()` makes the conscious decision not to support multi-strata models, but I do not understand how this improves consistency, programmability, or teachability in a way that's desirable for users of the package.

From the reprex in my original comment, we see that `glance()` throws an error when you update the original model to include a categorical predictor (whereas `summary()` would work for both models). As a user, this means I need to either implement my own solution or use another package that supports multi-strata models. To me this is a detriment to consistency and programmability as a user because I now need a second approach to accomplish the same task, which means I can't approach these models in a consistent way (even though it would be natural to do so if it weren't for the arbitrary restriction in `glance()`). It also makes teaching and learning more difficult, as it forces you into a situation where:

- As a teacher you now need to explain to learners that they either have to roll their own solution (which adds additional complexity to the problem) or use another package to accomplish the same task, but only for this subset of models
- As a learner you now need to learn additional workarounds because `broom` only supports some `survfit` models 

So instead of using `glance()` on both models (which would be consistent, programmatically simple, and easy to teach/learn), you need to do something like this:

``` r
library(survival)
library(dplyr)
library(purrr)
library(broom)

# No strata
veterans_fit <- survfit(Surv(time, status) ~ 1, data = veteran)

veterans_fit
#> Call: survfit(formula = Surv(time, status) ~ 1, data = veteran)
#> 
#>        n events median 0.95LCL 0.95UCL
#> [1,] 137    128     80      52     105

veterans_fit |>
  glance() |>
  mutate(strata = NA, .before = everything())
#> # A tibble: 1 × 11
#>   strata records n.max n.start events rmean rmean…¹ median conf.…² conf.…³  nobs
#>   <lgl>    <dbl> <dbl>   <dbl>  <dbl> <dbl>   <dbl>  <dbl>   <dbl>   <dbl> <int>
#> 1 NA         137   137     137    128  133.    15.3     80      52     105   137
#> # … with abbreviated variable names ¹​rmean.std.error, ²​conf.low, ³​conf.high

# Multi-strata
veterans_fit_ms <- survfit(Surv(time, status) ~ trt, data = veteran)

veterans_fit_ms
#> Call: survfit(formula = Surv(time, status) ~ trt, data = veteran)
#> 
#>        n events median 0.95LCL 0.95UCL
#> trt=1 69     64  103.0      59     132
#> trt=2 68     64   52.5      44      95

veterans_fit_ms_glance <- map_df(
  c("trt=1" = 1, "trt=2" = 2),
  function(.x) glance(update(veterans_fit_ms, subset = (trt == .x))),
  .id = "strata"
)

veterans_fit_ms_glance
#> # A tibble: 2 × 11
#>   strata records n.max n.start events rmean rmean…¹ median conf.…² conf.…³  nobs
#>   <chr>    <dbl> <dbl>   <dbl>  <dbl> <dbl>   <dbl>  <dbl>   <dbl>   <dbl> <int>
#> 1 trt=1       69    69      69     64  124.    14.8  103        59     132    69
#> 2 trt=2       68    68      68     64  142.    26.8   52.5      44      95    68
#> # … with abbreviated variable names ¹​rmean.std.error, ²​conf.low, ³​conf.high
```

<sup>Created on 2023-06-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

It's not terribly hard to do this, but it creates additional friction that doesn't need to be there.

If instead someone wanted to implement a `glance.survfit()` method that supports multi-strata models in a package they could, but then there's going to be a namespace conflict between this package and `broom`, duplicated efforts, etc. This feels like additional friction that doesn't necessarily need to be there.

I recognize the importance of keeping `broom` maintainable, but I feel that in this case it comes at the cost of the user experience in an undesirable way.
