### ISSUE TITLE
Different tidy output for an object of class summary.glht when the package jtools is loaded

### ISSUE THREAD

**Issue by awcm0n** [tidymodels/broom#1161]
An object of class `summary.glht` submitted to `tidy()` produces a tibble with different column names if the package `jtools` is loaded:

Without `jtools`:
```
> broom::tidy(o)
# A tibble: 4 × 6
  contrast      null.value estimate std.error statistic adj.p.value
  <chr>         <dbl>    <dbl>     <dbl>     <dbl>      <dbl>
1 mar_jun_2020      0  0.00496   0.00531     0.935 0.350     
2 jul_dec_2020      0 -0.0144    0.00315    -4.56  0.00000508
3 mar_junXnojob     0  0.0470    0.0405      1.16  0.246     
4 jul_decXnojob     0  0.0506    0.0226      2.24  0.0254  
```

With `jtools`:
```
> library(jtools)
> broom::tidy(o)
# A tibble: 4 × 6
  lhs             rhs estimate std.error statistic    p.value
  <chr>              <dbl>    <dbl>     <dbl>     <dbl>       <dbl>
1 mar_jun_2020           0  0.00496   0.00531     0.935  0.350     
2 jul_dec_2020           0 -0.0144    0.00315    -4.56   0.00000508
3 mar_junXnojob          0  0.0470    0.0405      1.16   0.246     
4 jul_decXnojob          0  0.0506    0.0226      2.24   0.0254    
```
```
> packageVersion("broom")
[1] ‘1.0.4’
> packageVersion("jtools")
[1] ‘2.2.1’
```
Issue also reported at [jacob-long/jtools](https://github.com/jacob-long/jtools/issues/139)

**Comment by simonpcouch** [comment]
Thanks for the issue!

There's not much I can do here from broom's perspective—jtools re-exports our generic and [defines a duplicated method](https://github.com/jacob-long/jtools/blob/54810edc7e579527e966aa8097c93fac8fef4bc7/R/internal.R#L445), which will take precedence in dispatch. [This commit message](https://github.com/jacob-long/jtools/commit/fca8c2ad02121f31a5a41c85da43cf02ef7ba4ee) speaks to some of their logic; they write 

> `broom`'s `tidy()` method does not provide confidence intervals for `glht` objects

which is no longer the case, via https://github.com/tidymodels/broom/issues/1103.
