### ISSUE TITLE
re-upping discussion of tidiers for rms-package objects

### ISSUE THREAD

**Issue by bbolker** [tidymodels/broom#1166]
There seems to be at least some ongoing interest in/demand for tidiers for objects from the `rms` package. (It's awfully hard to gauge interest; many users who don't find a solution will go try something else rather than posting an issue.)

- I made a *minimal* `tidy.ols` [here](https://stackoverflow.com/questions/76664284/r-use-of-rms-ols-function-with-multiple-objects-and-confidence-intervals/76664408)
- long thread, closed due to inactivity: https://github.com/tidymodels/broom/issues/30 (last comment Jan 2021)
- pull request locked in 2021 after last activity in 2019: https://github.com/tidymodels/broom/pull/326

**Comment by simonpcouch** [comment]
Thanks for bringing this content together. I agree that it's hard to gauge interest, though it seems like this is a discussion that has some enduring attention.

With an eye for the [maintenance guidelines](https://broom.tidymodels.org/articles/maintenance.html#guidelines) of the package, we won't be merging in support for these model objects. I appreciate you bringing this up, though.
