### ISSUE TITLE
Include `conf.level` in `tidy.htest()` results

### ISSUE THREAD

**Issue by ddsjoberg** [tidymodels/broom#1168]
The current `tidy.htest()` method returns the upper and lower confidence limits. But it doesn't return the confidence level, and without the confidence level, the confidence limits cannot be interpretted.

Can we add `conf.level` to the tidier tibble? The confidence level is returned as an attribute to the limits. The example below shows  the confidence level can be added with one small change shown below.

Thanks! 🍁 

PS I am happy to prepare the PR and perform the checks, including the revdeps

``` r
# simple t-test
x <- stats::t.test(mtcars$mpg ~ mtcars$am)

# current tidy() results for htest object (a t.test is used for illustration)
broom::tidy(x)
#> # A tibble: 1 × 10
#>   estimate estimate1 estimate2 statistic p.value parameter conf.low conf.high
#>      <dbl>     <dbl>     <dbl>     <dbl>   <dbl>     <dbl>    <dbl>     <dbl>
#> 1    -7.24      17.1      24.4     -3.77 0.00137      18.3    -11.3     -3.21
#> # ℹ 2 more variables: method <chr>, alternative <chr>

# we get confidence limits, but the confidence level is lost
x$conf.int
#> [1] -11.280194  -3.209684
#> attr(,"conf.level")
#> [1] 0.95

# a very abbreviated version of the tider, adding one line to include the conf.level
ret <- x[c("statistic", "p.value", "parameter")]
if (!is.null(x$conf.int)) {
  ret <- c(ret, 
           conf.low = x$conf.int[1], 
           conf.high = x$conf.int[2],
           conf.level = attr(x$conf.int, 'conf.level')) # add conf.level to returned stats vector (THIS IS THE ONE SMALL CHANGE)
}

tibble::as_tibble(ret) 
#> # A tibble: 1 × 6
#>   statistic p.value parameter conf.low conf.high conf.level
#>       <dbl>   <dbl>     <dbl>    <dbl>     <dbl>      <dbl>
#> 1     -3.77 0.00137      18.3    -11.3     -3.21       0.95
```

<sup>Created on 2023-08-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by simonpcouch** [comment]
Thank you for the thorough issue description!

While there are exceptions, it's generally not been precedent in the package to include argument values in output. Given where the package is at in its lifecycle, I think we'll continue with the existing behavior.

**Comment by ddsjoberg** [comment]
Thanks for the response @simonpcouch !

In probably the most common case here (the t-test), the tidy method returns an `"alternative"` column, which is just the `t.test(alternative=)` argument.
