### ISSUE TITLE
Issue in the documentation of tidy.geeglm

### ISSUE THREAD

**Issue by Generalized** [tidymodels/broom#1170]
https://broom.tidymodels.org/reference/tidy.geeglm.html
In the last last lines the output cannot be obtained due to errors:

![obraz](https://github.com/tidymodels/broom/assets/60151643/364532de-2e69-4448-8210-ea6973b6f3a8)

**Comment by hfrick** [comment]
Thanks for the report @Generalized !

**Comment by simonpcouch** [comment]
Much appreciated!
