### ISSUE TITLE
Regression Model Accuracy Metrics for Objects of class oohbchoice

### ISSUE THREAD

**Issue by donaldkip77** [tidymodels/broom#1178]
I was trying to get regression model metrics for my model could you please help especially Adjusted R Squared
library(DCchoice)
library(broom)
Error: No glance method for objects of class oohbchoice
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("Icens"

oohb1 <- oohbchoice(R1 + R2 ~ 1 | log(BL) + log(BH), data = oohbsyn)
oohb2 <- oohbchoice(R1 + R2 ~ age + gender | log(BL) + log(BH), data = oohbsyn)
summary(oohb2)
glance(oohb2)

Error: No glance method for objects of class oohbchoice

**Comment by simonpcouch** [comment]
Thanks for the issue, @donaldkip77! The error message:

> Error: No glance method for objects of class oohbchoice

tells us that objects from the DCchoice package are not supported by the broom package.

You will need to look into methods from the DCchoice package, or elsewhere, to calculate the statistics you need. [Posit Community](https://community.rstudio.com/) is a great place to ask questions like this one!
