### ISSUE TITLE
No tidy method for objects of class npregression

### ISSUE THREAD

**Issue by cretecht** [tidymodels/broom#1185]
I'm running [specr](https://github.com/masurp/specr) and [np](https://github.com/JeffreyRacine/R-Package-np), here's the code: 

```
kde.reg <- function(formula, data){
  bw <- npregbw(formula=as.formula(formula),
                data = data,
                nmulti = 5,
                ckertype = "epanechnikov", ukertype = "liracine",
                regtype="lc", bwmethod="cv.aic")
  npreg(bw)
}

test_specs <- setup(data = test_df,
                    y = c("y1", "y2"),
                    x = c("x1", "x2", "x3"),
                    model = "kde.reg"
                    )

summary(test_specs, rows = 50)
test_results <- specr(test_specs)
```

I encounter the tidy error because specr calls tidy at some point. The traceback call has `tidy.default(x, conf.int = TRUE)`, then the error follows it. Is there some way to resolve this issue?

**Comment by simonpcouch** [comment]
Thanks for the issue! This issue sounds like it would be better addressed in the specr package; I'd recommend opening an issue there.
