### ISSUE TITLE
Error: No tidy method for objects of class npregression

### ISSUE THREAD

**Issue by cretecht** [tidymodels/broom#1189]
I'm trying to apply a nonparametric smoothing model via the np package and extract/store the model's parameters using `tidy()`. Similarly, `glance()` or `augment()` may be applicable in such a situation. I'm encountering the error in the title. I'm not certain if a new feature request is needed or if this is simply a bug. Below is the code I'm using

```r

set.seed(7898)

params <- function(x) { # function to tibble to model parameters and statistics
  fit <- broom::tidy(x) # extract model parameters
  fit$res <- list(x)  # Store model object
  return(fit)
}
x1 <- rcauchy(50, location = 0, scale = 1)
x2 <- rcauchy(50, location = 1, scale = 0.7)
x3 <- rcauchy(50, location = -1, scale = 0.5)

Y <- rcauchy(50, location = 0, scale = 0.3)

D <- cbind(Y, x1, x2, x3) %>% 
  as.data.frame()

# np function that computes kernel density bandwidth 
kde_bw <- npregbw(formula = Y ~ x1 + x2 + x3,
                   data = D, nmulti = 5, 
                   ckertype = "epanechnikov",
                   regtype="ll", bwmethod="cv.aic")
# define a kernel density regression model
kde_reg <- npreg(kde_bw)

# extract the parameters
kde_params <- params(kde_reg)

```

This is a simplification of my problem since I have real data and more variables, but it recreates the error. I've provided a snippet of the traceback below. I can't think of any way to get around this issue other than hardcoding the extraction, but I'm wondering if there's a simpler solution?

![tidy_error_traceback](https://github.com/tidymodels/broom/assets/143825575/41a6b23f-2037-4389-93ef-2f9c671b38ed)

**Comment by simonpcouch** [comment]
Thanks for the issue! broom indeed doesn't support these model objects.

As of the 1.0.0 release of the package, we're [not accepting new tidiers to broom](https://broom.tidymodels.org/articles/maintenance.html), instead asking that they are implemented/maintained in the model-supplying package (i.e. npreg). 

[This vignette](https://cran.r-project.org/web/packages/broom/vignettes/adding-tidiers.html) points to some resources we've put together to help with implementing new tidiers in model-supplying packages.
