### ISSUE TITLE
Compatibility with stargazer or xtable

### ISSUE THREAD

**Issue by matthieugomez** [tidymodels/broom#12]
I think an interesting direction would be for xtable / stargazer to support the output of `tidy` and `glance`. For now, these packages don't use multiple dispatch and they support a relatively small set of statistical commands. But `tidy` and `glance` correspond exactly to the kind of operations needed to print consistently results from different models. 

If this is implemented, for a given S3 object, writing a `tidy` and `glance` method would then directly make it compatible with xtable/stargazer.

I think the only element missing to print a table from `tidy` and `glance` is the name of the dependent variable.

**Comment by grantmcdermott** [comment]
@matthieugomez 
I recently ran into a similar issue as you described above. (i.e. Running into memory problems when trying to export multiple regression objects via stargazer.) In my case, a fairly elegant solution is to first convert the *lm object into a "coeftest" class using the lmtest package as I describe [here](http://stackoverflow.com/a/40029509/4115816).

@dgrtwo 
A related issue that I noticed as a result: `broom`'s tidy function can take quite a while to run on large *lm objects. However, `lmtest`'s coeftest function works virtually instantaneously. The good news is that, broom accepts coeftest objects, so I can still benefit the increased speed by using:

`my_lm_object %>% lm::testcoeftest %>% broom::tidy()`.

A minor downside to this approach is that the coeftest object doesn't preserve confidence intervals (although these can obviously be calculated easily by hand if you know the sample size / degrees of freedom). However, perhaps you can still use the testcoef code to speed things up?
