### ISSUE TITLE
Could glance and tidy etc output variable names in snakecase? 

### ISSUE THREAD

**Issue by davidhodge931** [tidymodels/broom#1213]
The tidyverse encourages use of snakecase column-names.

Could glance and tidy etc output variable names in snakecase?  

<img width="464" alt="image" src="https://github.com/user-attachments/assets/644a25cc-a562-47fa-98a3-b79bc6a0119b">

**Comment by simonpcouch** [comment]
Thanks for the issue!

While I'd also prefer that broom have consistently used snake case, at this point in the package's lifecycle, making such a change would cause too significant a disruption to users.
