### ISSUE TITLE
Suggest using getRversion() check in skip()

### ISSUE THREAD

**Issue by MichaelChirico** [tidymodels/broom#1232]
https://github.com/tidymodels/broom/blob/e480deb74c8ea172e1d5e69630971c4b59bb43dd/tests/testthat/test-joineRML.R#L4

I came across this while testing in my old version of R, it strikes me as a bit unusual. It produces messy reports like this:

```
• paste0(R.Version()[c("major", "minor")], collapse = ".") < "4.4.0" is TRUE
  (1): test-stats-anova.R:132:1
```

c.f. a similar helper we have in {lintr}:

https://github.com/r-lib/lintr/blob/4de229f55e9387379beb42f61c235266bbc68dcd/tests/testthat/helper.R#L55-L59

Happy to file a PR if you're interested; starting with the bug first since I'm in a bit of a rush at the moment :)

**Comment by simonpcouch** [comment]
Thanks!
