### ISSUE TITLE
Include methods for the `train` class from caret

### ISSUE THREAD

**Issue by lmullen** [tidymodels/broom#128]
It looks like there are not currently methods for `tidy()` and friends for the results of the `train()` function from the `caret` package. 

I'd like to add these, but I'll have to use caret more to make sure I do it properly.

**Comment by dgrtwo** [comment]
This is something I've wanted to do for a long time!! I also need a bit more practice but I do have some ideas. Expect it before too long.

**Comment by ian-flores** [comment]
@lmullen @dgrtwo Has there been work done in this direction? I'm interested in helping if possible.
