### ISSUE TITLE
preliminary VGAM::vglm tidier

### ISSUE THREAD

**Issue by bbolker** [tidymodels/broom#135]
I should probably test this more extensively/put it in a pull request/etc., but since I just hacked it up quickly I'm just going to post it here before it gets lost in the shuffle.  There are probably a lot of bells and whistles that would be worth considering.

```
tidy.vglm <- function(x, conf.int=FALSE, conf.level=0.95) {
    co <- as.data.frame(coef(summary(x)))
    names(co) <- c("estimate","std.error","statistic","p.value")
    if (conf.int) {
        qq <- qnorm((1+conf.level)/2)
        co <- transform(co,
                        conf.low=estimate-qq*std.error,
                        conf.high=estimate+qq*std.error)
    }
    co <- data.frame(term=rownames(co),co)
    rownames(co) <- NULL
    return(co)
}
```

By the way, it _might_ (???) be worth considering something like that as a barebones `tidy.default` method -- i.e. many packages adopt the convention that `coef(summary(object))` is a coefficient table ...

**Comment by CelMcC** [comment]
That is perfect thank you so much!
