### ISSUE TITLE
Tidy Multivariate Models such as PLS and PCR

### ISSUE THREAD

**Issue by therimalaya** [tidymodels/broom#148]
I have to work regularly with PLS and PCR and other Multivariate models. I usually have to calculate RMSEP, MSEP, R2pred, loading weight, loadings, coefficients, number of component producing minimum error. Most often, I have to do cross-validation and extract similar statistic from each of the cross-validated models.

Please add `mvr` class in broom!

**Comment by kyusque** [comment]
@alexpghayes @therimalaya 
Hi,
I also work with PLS and PCR on my research, and I would like to solve this issue.
But, this is the first time for me to contribute an R package. 
Would you tell me how to contribute to this package?
A work in progress repository is here.
https://github.com/kyusque/broom

**Comment by alexpghayes** [comment]
Have you seen https://broom.tidyverse.org/articles/adding-tidiers.html? That's a good place to start!

**Comment by kyusque** [comment]
Thank you for the advice and I tried to conform to the document.

`devtools::spell_check()` and `goodpractice::gp()` were passed.
But `devtools::check()` returned the following warnings.
```
❯ checking Rd cross-references ... WARNING
  Packages unavailable to check Rd xrefs: ‘drc’, ‘lfe’, ‘robust’, ‘joineRML’, ‘plm’, ‘poLCA’, ‘speedglm’, ‘gam’, ‘biglm’, ‘binGroup’, ‘ergm’, ‘tseries’, ‘geepack’, ‘gmm’, ‘lavaan’, ‘lmodel2’, ‘muhaz’, ‘orcutt’, ‘survey’, ‘akima’, ‘Kendall’, ‘btergm’, ‘multcomp’, ‘emmeans’, ‘lsmeans’, ‘epiR’, ‘gamlss’, ‘psych’, ‘ks’, ‘mediation’, ‘bbmle’, ‘leaps’, ‘AUC’, ‘systemfit’
  Missing link or links in documentation object 'augment.mvr.Rd':
    ‘[pls:cpplsr]{pls::cpplsr()}’
    ‘[pls:::predict.mvr]{pls::::predict.mvr()}’
  
  Missing link or links in documentation object 'glance.mvr.Rd':
    ‘[pls:cpplsr]{pls::cpplsr()}’
  
  Missing link or links in documentation object 'tidy.mvr.Rd':
    ‘[pls:cpplsr]{pls::cpplsr()}’ ‘i’
  
  See section 'Cross-references' in the 'Writing R Extensions' manual.
```
And, accidentally `broom` added in Import section  in DESCRIPTION file.
https://github.com/kyusque/broom/commit/8c416f06933f143e39a6cdb3c43533f9f27a35e6

I couldn't understand why it happened even I have read the section 'Cross-references' in the 'Writing R Extensions' manual.

Would you give me some advice to solve them?
And, should I send a pull request to have a discussion on code (Is this expression correct?)?

**Comment by uribo** [comment]
Hi, @kyusque 

`pls :: cpplsr` is exported but used as an alias for mvr.
You can try, `[pls::cpplsr()][pls::mvr()]` and other places.

https://github.com/bhmevik/pls/blob/master/man/mvr.Rd#L2-L6

**Comment by kyusque** [comment]
@uribo Thank you for the advice.
I have finally solved that problem:smile:
I will send a pull-request.

**Comment by gtalckmin** [comment]
Hi, how can I have access to this functionality? At the moment broom cannot run nor tidy or broom functions on mvr objects.
> tidy_CP1<- tidy(CP1)
Error: No tidy method for objects of class mvr
> tidy_CP1<- glance(CP1)
Error: No glance method for objects of class mvr
