### ISSUE TITLE
Clarity regarding GLM

### ISSUE THREAD

**Issue by jonocarroll** [tidymodels/broom#158]
This took me far too long to solve, so some additional notes might be useful to others.

It seems there's no specific method for `augment`ing GLMs, and as such they fall back to `augment.lm`, since 

> glm returns an object of class inheriting from "glm" which inherits from the class "lm".

This isn't particularly clear if one tries searching for `augment.glm`. The context for this is that I was trying to find out which residuals are being calculated as the `.resid` column, which differs for `lm` and `glm`; these are (by default) deviance residuals for `glm` and working residuals for `lm`. The README claims that for `augment`:

> .resid: residuals: the actual y values minus the fitted values

which isn't the case for `glm`.

After hunting through the source, I eventually found that I needed to specify `type.residuals` in the call to `augment`. This took some time though, as `augment.lm` doesn't show up as an exported function (can't use it by name) for whatever reason, so I couldn't even check the raw code for it quickly. `?augment` does link to `augment.lm` which is where I did find the required argument.

Could I suggest at least adding an alias for `augment.glm` that points to `augment.lm`? Or better yet, its own `tidy.glm` help page with useful examples?

Potential examples:

```
mtcarsglm <- glm(cyl ~ mpg, data = mtcars, family = poisson())

summary(mtcarsglm)
#> Deviance Residuals: 
#>   Min       1Q   Median       3Q      Max  
#> -0.7316  -0.2582   0.1041   0.2098   0.6794  

fivenum(residuals(mtcarsglm, type = "deviance"))
#> Volvo 142E    Porsche 914-2        Mazda RX4      AMC Javelin Pontiac Firebird 
#> -0.7316372       -0.2674050        0.1041252        0.2190416        0.6793560 

fivenum(augment(mtcarsglm)$.resid)  ## **default**
#> -0.7316372 -0.2674050  0.1041252  0.2190416  0.6793560

fivenum(residuals(mtcarsglm, type = "working"))
#> Volvo 142E    Porsche 914-2        Mazda RX4      AMC Javelin Pontiac Firebird 
#> -0.29164500      -0.11270417       0.04374193       0.08164739       0.28428369 

fivenum(augment(mtcarsglm, type.residuals = "working")$.resid)
#> [1] -0.29164500 -0.11270417  0.04374193  0.08164739  0.28428369

```

**Comment by vjd** [comment]
Thanks. This help clarify the not too obvious defaults for augment when using different models. I thought this may be helpful for folks coming new into the `broom` package - The  default for `predict.type`  is the logit scale when we augment a `glm` model. If we use the `type.predict="response"` in the augment functions we get `.fitted` values in the probability scale.

**Comment by alexpghayes** [comment]
Now that `augment.glm` has it's own documentation, that would be a natural place to put this.

**Comment by alexpghayes** [comment]
Just took a look at the existing `augment.glm()` documentation and its seem like it makes this all clear. Closing for now, please let me know if the documentation needs additional improvements.
