### ISSUE TITLE
tidy segmented model

### ISSUE THREAD

**Issue by dschneiderch** [tidymodels/broom#173]
tidy() for a segmented object always returns 0 for the estimate and 1 for p value, as far as I can tell. Interestingly, std.error is not 0.
shouldn't the estimate be the breakpoint and the pvalue from davies.test() of the linear (non-segmented model)?
One thing I'm unsure about is which breakpoint to report, that from segmented() or that from davies.test(). They report slightly different breakpoint estimates. 

davies.test() requires the original linear model rather than the segmented model, is why estimate and pvalue are 0 from tidy()? in this case, NA would be better I think.

```
library(segmented)
library(broom)
linmdl=lm(snw~sca,data=robdata)
ss=segmented(linmdl,~sca,psi=.1)
davies.test(linmdl,~sca)
tidy(ss)
```

some example data:
```
structure(list(snw = c(1.3379867094972, 0.732666495037936, 0.576903227087757, 
0.144938045383969, 0.0628010823651208, 0.00453322001892654, 1.15372637435442, 
1.38712582663615, 1.17866505632708, 0.982191140775396, 0.956481184860154, 
0.783034855873891, 0.554488835472683, 0.304550401827063, 0.177324502497286, 
0.0898379755490509, 0.281017699834271, 0.381077539188414, 0.25228770558561, 
0.122760780431337, 0.581122881761823, 0.212218758067146, 0.334626086593144, 
0.0858645853494403, 0.0327680112921047, 0.000676543292026933, 
1.0527051537889, 0.62614124724974, 0.360061995530027, 0.196180357035871, 
0.0596823902053918, 0.0109758173684739, 0.00177871950733928), 
    sca = c(0.854385917448981, 0.760400039679319, 0.671509347185023, 
    0.244613983352722, 0.145578010442875, 0.0228516805093382, 
    0.897329762194627, 0.957173389605822, 0.927648369089811, 
    0.836818800782765, 0.909098287476666, 0.799042285528772, 
    0.681429176924672, 0.454192931670409, 0.308876444011579, 
    0.193644094544995, 0.524867209551894, 0.65655745835926, 0.475971466962458, 
    0.290705119533948, 0.92523153784415, 0.428554680806933, 0.845485124764404, 
    0.18902686470254, 0.0907934961989016, 0.0033817601385169, 
    0.781006231456682, 0.696660624588552, 0.496902307713118, 
    0.333766198631063, 0.142746349953557, 0.0257013770527284, 
    0.00419338257176095)), .Names = c("snw", "sca"), row.names = c(NA, 
-33L), class = "data.frame")
```

**Comment by dgrtwo** [comment]
Interesting question. There is no method specific to `segmented` objects- instead, what is being called is `tidy.lm` (since segmented objects are also `lm` objects). Thus, it is just a tidied version of:

    summary(ss)$coefficients

From a bit of examination it looks like you should not pay any attention to the psi estimate or p-value in here, only to the `davies.test` one.

I'll try to return to this at some point to get `segmented` objects a better tidying method!

**Comment by dschneiderch** [comment]
Actually, based on the documentation for `davies.test` you should not use it for psi estimate because it tests 10 equally distributed values of psi for significance. `segmented` converges to a psi value so the pvalue should be from `davies.test` and the psi value from `segmented`.
