### ISSUE TITLE
Feature request: tidy() for rma objects (metafor package)

### ISSUE THREAD

**Issue by thoughtsnippet** [tidymodels/broom#204]

**Comment by talgalili** [comment]
It is available in this fork:
https://github.com/talgalili/broom/commit/a4f243d346a5d888d7d6b569e8f105befaa95123
Specifically, here is the R code:
https://github.com/talgalili/broom/blob/master/R/metafor_tidiers.R

I hope David would get to add it.

Cheers,
Tal

**Comment by alexpghayes** [comment]
Would love to add these. Can you make a PR?

**Comment by IndrajeetPatil** [comment]
Duplicate of #621
