### ISSUE TITLE
Feature request: tidy() for (g)lmrob objects (robustbase package)

### ISSUE THREAD

**Issue by rentrop** [tidymodels/broom#205]
After tidiers for lmRob and glmRob objects from the `robust` package it would be awesome to also see tidiers for the `lmrob` and `glmrob` objects from the `robustbase` package

**Comment by robustbayesian** [comment]
I second this, if the package is still being developed.

**Comment by alexpghayes** [comment]
It looks like we gained tidiers for `robust` at some point (`?robust_tidiers`). Request for tidiers for `robustbase` noted.

**Comment by mattle24** [comment]
I'd like to add the tidiers for `robustbase (g)lmrob` objects if no one is currently working on that. I think creating these tidiers relates to https://github.com/tidymodels/broom/issues/505 and https://github.com/tidymodels/broom/issues/506, so I'm linking those issues.

**Comment by alexpghayes** [comment]
Go for it!

**Comment by alexpghayes** [comment]
Closed in #595! Thank you @mattle24!
