### ISSUE TITLE
augment fails for weighted regression with some observations having weight = 0

### ISSUE THREAD

**Issue by rebeccaferrell** [tidymodels/broom#232]
Reprex in which the first 25 out of 100 observations have weight zero for the regression.

```
library(tidyverse)
library(broom)

n <- 100
set.seed(1)

dumb_data <- data_frame(
    x = 1:n,
    y = 1:n + rnorm(n),
    weights = c(rep(0, n/4), rep(0.5, n/4), rep(1, n/4), rep(1.5, n/4))
)

fit <- lm(y ~ x, data = dumb_data, weights = weights)

fit %>% augment() 
```

```
Error in `$<-.data.frame`(`*tmp*`, ".hat", value = c(0.0409852490954634,  : 
  replacement has 75 rows, data has 100
```
I can trace the error back to this portion of the `augment_columns` code in `utilities.R`:

        infl <- influence0(x, do.coef = FALSE)
        if (!is.null(infl)) {
            if(is_mgcv(x)){
                ret$.hat <- infl
                ret$.sigma <- NA
            }else{
            ret$.hat <- infl$hat
            ret$.sigma <- infl$sigma
            }
        }

`stats::influence` excludes observations with weight = 0, so only 75 observations returned instead of 100 leading to the error. This behavior is documented in `stats::influence`:

> Note that cases with `weights == 0` are *dropped* (contrary to the situation in S).

**Comment by TripLLL** [comment]
I am having the same problem. Have you found a solution yet?
