### ISSUE TITLE
Simplifying Extensions of `broom`

### ISSUE THREAD

**Issue by nutterb** [tidymodels/broom#256]
Given the discussion around placing mixed model tidiers in a separate package (see [here](https://github.com/tidyverse/broom/issues/223), and [here](https://github.com/tidyverse/broom/issues/96#issuecomment-232103247)), I had made a proposal to make a lightweight `broom.base` that minimizes dependencies and makes it easier for other package maintainers to import/export the tidy method within their own packages.

I've put together a [version of `broom.base`](https://github.com/nutterb/broom.base) that has the following dependencies

```
Imports:
Suggests:
    dplyr,
    knitr,
    ggplot2,
    testthat
```

Some notes on this process

* Probably the most offensive, I pulled out `rowwise_df_tidiers`.  I did this to cut out the dependency on `dplyr`.  That's probably counter intuitive for a package in the tidyverse, but I was going pretty extreme on the lightweight.  
* To avoid a dependency on `purrr`, I copied the deprecated form of `dplyr::failwith` as an unexported function.  That will need to be credited properly (it was easier to use the `dplyr` version than to work out the symbols in the `purrr` version).
* I removed the dependency on `psych`, which means I had to look up how to calculate skew and kurtosis.  I drew inspiration for these using `moments::skew` and `moments::kurtosis`.  These should probably be credited as well.
* I believe it would be possible to remove `dplyr` from the `Suggests`.  It could be done by either rewriting the tests to use `data.frame`, or to use `tibble` instead.
* There is an issue to [use `tibble` instead of `data.frame`](https://github.com/tidyverse/broom/issues/150).  This could be added to `Imports:` and implemented. The only dependencies of `tibble` and `plyr` combined are `Rcpp` and `rlang`, which is still pretty light weight.
* To implement this `broom` would need some work to make `broom.base` a dependency.
* In a couple of tidiers, such as `tidy.list`, I had to remove `tidy_xyz`, `tidy.orkutt`, etc...things that depended on other packages.  The `broom` package might need to overwrite `tidy.list` to support these objects.

so the major questions are 

1. Is this something you would be interested in pursuing?
2. If so, where have I gone to far?  Are there dependencies you'd prefer to keep? 

A note of trivia: 

Installing `broom` with `dependencies = c("Depends", "Imports", "LinkingTo")`  isn't terrible and installs a total of 21 packages.

Installing `broom` with `dependencies = c("Depends", "Imports", "LinkingTo", "Suggests")` installs 1003 packages.

**Comment by dgrtwo** [comment]
I like this a lot! I'm going to have to come back to this after I've fixed up the existing issues in the project and gotten broom 0.4.3 on CRAN.

* One of my next steps before broom 0.5.0 is to convert all tidiers to return `tbl_df`s instead of data frames. I think a `tibble` is probably a good idea for a broom.base dependency.
* You're right to cut out `rowwise_df_tidiers`, I've actually been planning to deprecate them for a while. One reason I've hesitated is that my [broom paper on Arxiv](https://arxiv.org/abs/1412.3565) uses them (I should just rewrite/update it).

**Comment by nutterb** [comment]
Knowing that you're interested at least let's me know I'm not completely wasting my time by preparing a draft. I'll keep an eye on what changes you're making in this current sprint and try to copy them over to my repo when you're done. I'll also work on getting the output to be `tbl_df` objects. 

The only other question I'll ask right now is how `base` you want this to be. Right now, my implementation sticks with just the packages in Base R, and doesn't include any of the recommended packages (ie, `survival`). Should it include the recommended packages?

**Comment by topepo** [comment]
If you want to go "full tibble", it might be better to keep `dplyr` since it reexports [a bunch of `tibble` functions](https://github.com/tidyverse/dplyr/blob/master/NAMESPACE).

**Comment by nutterb** [comment]
I spent some time working on this and now have a mostly completed package that returns `tbl_df` objects. The only major issue with it is that I can an error for a failing test on `check` that I'm not getting when I run it interactively. This brings me to a couple of questions

1. Where do you want this to live?
2. Should this include recommended package tidiers (such as `survival`)?
3. Should I delay developing now, or should I start identifying issues and pull requests that could be handled in `broom.base`? That really turns this into a question of how soon you want to make this avaliable to other developers, but since `broom.mixed` and `broomstick` are already underway, it may be beneficial to start this transition sooner rather than later.
