### ISSUE TITLE
Use lintr to enforce tidyverse code style

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#316]

**Comment by alexpghayes** [comment]
Also clean up with `goodpractice`

**Comment by alexpghayes** [comment]
And use markdown in the documentation. Is there a package to automate the switch?

**Comment by alexpghayes** [comment]
Yes. `roxygen2md`. Still need to turn lists into rmarkdown though.

- [ ] Finish transition to `rmarkdown` for code documentation
- [ ] Pass `goodpractice`
- [ ] Enable `lintr` test

**Comment by IndrajeetPatil** [comment]
Fixed in https://github.com/tidymodels/broom/pull/636
