### ISSUE TITLE
augment.smooth.spline doesn't accept new data in the data argument

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#318]
```r

library(broom)

s <- smooth.spline(x = iris[1:100, 1], y = iris[1:100, 2])
augment(s)
#>       x   y w  .fitted        .resid
#> 1   5.1 3.5 1 3.264390  0.2356098689
#> 2   4.9 3.0 1 3.223535 -0.2235354967
#> 3   4.7 3.2 1 3.160689  0.0393109018
#> 4   4.6 3.1 1 3.123296 -0.0232957948
#> 5   5.0 3.6 1 3.248622  0.3513780529
#> 6   5.4 3.9 1 3.200056  0.6999442750
#> 7   4.6 3.4 1 3.123296  0.2767042052
#> 8   5.0 3.4 1 3.248622  0.1513780529
#> 9   4.4 2.9 1 3.040790 -0.1407901307
#> 10  4.9 3.1 1 3.223535 -0.1235354967
#> 11  5.4 3.7 1 3.200056  0.4999442750
#> 12  4.8 3.4 1 3.194007  0.2059930490
#> 13  4.8 3.0 1 3.194007 -0.1940069510
#> 14  4.3 3.0 1 2.999143  0.0008571424
#> 15  5.8 4.0 1 2.991681  1.0083193621
#> 16  5.7 4.4 1 3.040734  1.3592659188
#> 17  5.4 3.9 1 3.200056  0.6999442750
#> 18  5.1 3.5 1 3.264390  0.2356098689
#> 19  5.7 3.8 1 3.040734  0.7592659188
#> 20  5.1 3.8 1 3.264390  0.5356098689
#> 21  5.4 3.4 1 3.200056  0.1999442750
#> 22  5.1 3.7 1 3.264390  0.4356098689
#> 23  4.6 3.6 1 3.123296  0.4767042052
#> 24  5.1 3.3 1 3.264390  0.0356098689
#> 25  4.8 3.4 1 3.194007  0.2059930490
#> 26  5.0 3.0 1 3.248622 -0.2486219471
#> 27  5.0 3.4 1 3.248622  0.1513780529
#> 28  5.2 3.5 1 3.262479  0.2375214242
#> 29  5.2 3.4 1 3.262479  0.1375214242
#> 30  4.7 3.2 1 3.160689  0.0393109018
#> 31  4.8 3.1 1 3.194007 -0.0940069510
#> 32  5.4 3.4 1 3.200056  0.1999442750
#> 33  5.2 4.1 1 3.262479  0.8375214242
#> 34  5.5 4.2 1 3.146887  1.0531126570
#> 35  4.9 3.1 1 3.223535 -0.1235354967
#> 36  5.0 3.2 1 3.248622 -0.0486219471
#> 37  5.5 3.5 1 3.146887  0.3531126570
#> 38  4.9 3.6 1 3.223535  0.3764645033
#> 39  4.4 3.0 1 3.040790 -0.0407901307
#> 40  5.1 3.4 1 3.264390  0.1356098689
#> 41  5.0 3.5 1 3.248622  0.2513780529
#> 42  4.5 2.3 1 3.082423 -0.7824229689
#> 43  4.4 3.2 1 3.040790  0.1592098693
#> 44  5.0 3.5 1 3.248622  0.2513780529
#> 45  5.1 3.8 1 3.264390  0.5356098689
#> 46  4.8 3.0 1 3.194007 -0.1940069510
#> 47  5.1 3.8 1 3.264390  0.5356098689
#> 48  4.6 3.2 1 3.123296  0.0767042052
#> 49  5.3 3.7 1 3.240452  0.4595482576
#> 50  5.0 3.3 1 3.248622  0.0513780529
#> 51  7.0 3.2 1 3.048649  0.1513512168
#> 52  6.4 3.2 1 2.870929  0.3290705158
#> 53  6.9 3.1 1 3.013227  0.0867725595
#> 54  5.5 2.3 1 3.146887 -0.8468873430
#> 55  6.5 2.8 1 2.889903 -0.0899032325
#> 56  5.7 2.8 1 3.040734 -0.2407340812
#> 57  6.3 3.3 1 2.861136  0.4388635545
#> 58  4.9 2.4 1 3.223535 -0.8235354967
#> 59  6.6 2.9 1 2.915663 -0.0156628697
#> 60  5.2 2.7 1 3.262479 -0.5624785758
#> 61  5.0 2.0 1 3.248622 -1.2486219471
#> 62  5.9 3.0 1 2.946557  0.0534434183
#> 63  6.0 2.2 1 2.908092 -0.7080923600
#> 64  6.1 2.9 1 2.879716  0.0202839786
#> 65  5.6 2.9 1 3.092206 -0.1922064063
#> 66  6.7 3.1 1 2.945869  0.1541309981
#> 67  5.6 3.0 1 3.092206 -0.0922064063
#> 68  5.8 2.7 1 2.991681 -0.2916806379
#> 69  6.2 2.2 1 2.863643 -0.6636428680
#> 70  5.6 2.5 1 3.092206 -0.5922064063
#> 71  5.9 3.2 1 2.946557  0.2534434183
#> 72  6.1 2.8 1 2.879716 -0.0797160214
#> 73  6.3 2.5 1 2.861136 -0.3611364455
#> 74  6.1 2.8 1 2.879716 -0.0797160214
#> 75  6.4 2.9 1 2.870929  0.0290705158
#> 76  6.6 3.0 1 2.915663  0.0843371303
#> 77  6.8 2.8 1 2.978642 -0.1786416375
#> 78  6.7 3.0 1 2.945869  0.0541309981
#> 79  6.0 2.9 1 2.908092 -0.0080923600
#> 80  5.7 2.6 1 3.040734 -0.4407340812
#> 81  5.5 2.4 1 3.146887 -0.7468873430
#> 82  5.5 2.4 1 3.146887 -0.7468873430
#> 83  5.8 2.7 1 2.991681 -0.2916806379
#> 84  6.0 2.7 1 2.908092 -0.2080923600
#> 85  5.4 3.0 1 3.200056 -0.2000557250
#> 86  6.0 3.4 1 2.908092  0.4919076400
#> 87  6.7 3.1 1 2.945869  0.1541309981
#> 88  6.3 2.3 1 2.861136 -0.5611364455
#> 89  5.6 3.0 1 3.092206 -0.0922064063
#> 90  5.5 2.5 1 3.146887 -0.6468873430
#> 91  5.5 2.6 1 3.146887 -0.5468873430
#> 92  6.1 3.0 1 2.879716  0.1202839786
#> 93  5.8 2.6 1 2.991681 -0.3916806379
#> 94  5.0 2.3 1 3.248622 -0.9486219471
#> 95  5.6 2.7 1 3.092206 -0.3922064063
#> 96  5.7 3.0 1 3.040734 -0.0407340812
#> 97  5.7 2.9 1 3.040734 -0.1407340812
#> 98  6.2 2.9 1 2.863643  0.0363571320
#> 99  5.1 2.5 1 3.264390 -0.7643901311
#> 100 5.7 2.8 1 3.040734 -0.2407340812
augment(s, data = iris[101:150, 2])
#> Error in `$<-.data.frame`(`*tmp*`, .fitted, value = c(3.26439013107167, : replacement has 100 rows, data has 50
```

**Comment by tristanfabregas** [comment]
I encounter the same kind of problem with the grouped data.
Here is a reproducible example:

`rm(list=ls(all=TRUE))

library(tidyverse)
library(broom)

# first shuffle around the rows of iris
set.seed(1234)
myiris <- iris[sample(nrow(iris), replace = F),]

# first data - first 25 rows for running the models on
origiris <- 
  myiris[1:25,] %>% 
  nest(-Species) %>% 
  rename(origdata = data)

# second data - last 50 rows for predicting on
prediris <- 
  myiris[101:150,] %>% 
  nest(-Species) %>% 
  rename(preddata = data)


# estimate models on the first 25 rows
# a separate model is estimated for each species
iris_mod <- 
  origiris %>% 
  mutate(mod = map(origdata, ~ smooth.spline(.$Sepal.Length, .$Petal.Length, df = 4), data = .))


# get fitted values for the first dataset (origdata)
origiris_aug <-  
  iris_mod %>% 
  mutate(origpred = map(mod, augment)) %>% 
  unnest(origpred) %>% 
  as.tibble()


# get fitted values for the second dataset (preddata)
# each model is fitted to the appropriate species' nested dataframe

prediris_aug <- 
  iris_mod %>% 
  inner_join(prediris, by = "Species") %>% 
  map2_df(.x = iris_mod$mod, .y = prediris$preddata, .f = ~augment(.x, newdata = .y)) %>% 
  as.tibble()

prediris_aug
`

prediri_aug is a 25 by 5 tibble instead of 50 by 5

In the original [post](https://stackoverflow.com/questions/45857247/r-predict-new-values-for-groups) it work perfectly using MASS::rlm

Thnak you for your help

**Comment by alexpghayes** [comment]
The specification for `augment` has become more strict since I first created this issue.

Now data passed to the `data` argument **must** be the data that a model was original fit on. To argument with a new data set, the user **must** pass the new dataset to the `newdata` argument.

We're in the process of writing more informative errors to make this clearer.

At the moment the `smooth.spline` function does not have a `newdata` argument, indicating that it does not support the behavior you'd like above.

**Comment by ShreyasSingh** [comment]
@alexpghayes  I would like to pick this up!Do we need to add `newdata` as argument for smooth.spline ?

**Comment by alexpghayes** [comment]
Yep! I'd recommend starting by reading the documentation of `predict.smooth.spline`.

We'll want to add a `.fitted` column to the `newdata` based on these predictions. No need for a `.resid` column. You'll want to make sure that:

- if `newdata` is passed, it takes precedence over the data `argument`
- rows with missing data get predictions of `NA`

These should all get caught by running the `check_augment_function()` test.

Let me know if you'd like advice at any point in the process.

**Comment by alexpghayes** [comment]
Hey so I've been looking into this more over at https://github.com/alexpghayes/safepredict/blob/master/R/stats-smoothspline.R, and `smooth.spline()` only accepts vectors as a data argument. If you want to have a go, please do.

I'm sort of torn about supporting such a partially-implemented function at the moment, to be honest. @dgrtwo what do you think about throwing an error (or maybe a warning) and telling people to use `mgcv` or `gam` instead?
