### ISSUE TITLE
Overhaul README and update vignettes

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#335]

**Comment by alexpghayes** [comment]
Also go through all of the examples and make sure that they are easy to copy paste and there are some for every function.

**Comment by alexpghayes** [comment]
Make sure vignettes have clear focuses:

- broom: an extended introduction going into more details about conventions, etc
- kmeans: distinguish between tidy, glance and augment. also: what is tidy data?
- broom and dplyr: the recommend nest-map-unnest workflow
- bootstrapping: working with the tidymodels universe and working with models fit on resampled datasets
- available tidiers: can i tidy my model? also: where does my tidier live if not in broom?
- adding tidiers: how do i write my own tidier?
- glossary: what information can i get about model X?

**Comment by simonpcouch** [comment]
Vignettes structure has changed quite a bit since this issue was opened and were workshopped in the move to tidymodels.org, and README was workshopped quite a bit throughout the summer. Open to a new issue re: examples for every tidier if this feels within the scope of broom maintenance.
