### ISSUE TITLE
Get Travis to build for R 3.1, 3.2 and 3.3

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#370]
Following up on #146 and #360, we still need to get Travis to build for R 3.1, 3.2, 3.3.

**Comment by IndrajeetPatil** [comment]
Already included-

https://github.com/tidymodels/broom/blob/d4b9cfad3b486db0817fb73d0e726c55c2393493/.travis.yml#L2-L11

**Comment by alexpghayes** [comment]
I give up on 3.1, 3.2, 3.3.
