### ISSUE TITLE
Laundry list of tidy argument / behavioral consistency items

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#393]
Based on looking at the non-standard arguments to `tidy` methods.

- [x] `tidy.boot`: document that `conf.method` is passed to `boot::boot.ci(..., type = conf.method)`
- [ ] `tidy.brmsfit`. Rename `intervals = conf.int`, `prob = conf.level`, decide what to do with `parameters`
- [x] `tidy.felm` example returns NaN rather than NA. Remove `fe.error`, only use `fe`. Possibly rename to `include_fe`
- [ ] Document that undefined / unknown values should **always** be `NA`. Test for `Inf` and `NaN`.
- [ ] New tidier vignette: written documentation should default argument values
- [ ] New tidier vignette: document behavior when `data`/`newdata`/neither is provided
- [ ] `tidy.gam`: `parametric` currently a switch. should parametric always be returned, with non-parametric return optionally? Or should they both always be returned (leaning toward this). Ask Gavin.
- [ ] `tidy.kmeans`: rename `col.names` arg
- [x] `tidy.manova` doc: specify what `test` gets passed to. perhaps rename `test` to `method`, which is used elsewhere
- [ ] `tidy.prcomp` doc: rename `matrix` arg?
- [x] harmonize `diag` and `diagonal` across `tidy.dist` and `tidy.rcorr`
- [ ] `tidy.rjags`: `pars` consistency with other parameter type arguments. rename `estimate.method`?
- [ ] `tidy.rq/tidy.rqs`: rename `se.type` since everywhere else it's `std.error`. Remove `alpha` arg and use `conf.level` instead, inverting or whatever is necessary to translate between scales
- [ ] `tidy.stanfit`: remove `droppars`, redundant with `pars`. rename `rhat, ess` to `include_rhat, include_ess`? or just include these by default. I'm a fan of `tidy` giving you lots of stuff that you can then `select(-stuff)` away immediately after if you don't want it.
- [ ] `tidy.stanreg`: Decide on `parameters`, see below. Rename `intervals = conf.int`, `prob = conf.level`. #291.
- [x] `tidy.TukeyHSD`: remove `separate.levels` argument and allow user to call `dplyr::separate` later if they want. This is consistent with the `multcomp::glht` tidier behavior.

## Parameter selection in bayesian and hierarchical models

Currently arguments `pars`, `parameters`, `droppars` accept:

- a categorical choice defining which type of tidier to return
- a regex for a parameter names
- raw parameter names, etc

Regex/raw parameter names are ugly and make the user do the work. We should either do the work for the user with a `tidyselect`-like interface, or only offer basic options, such as selecting between hierarchical and non-hierarchical paramers, etc.

**Comment by alexpghayes** [comment]
- [ ] Add `conf.int` argument to `tidy.btergm`
- [ ] Add `conf.int` argument to `tidy.cch`
- [ ] Add `conf.int` argument to `tidy.survreg`
- [ ] Make sure `conf.level` arguments default to `0.95`

**Comment by vincentarelbundock** [comment]
https://github.com/tidymodels/broom/pull/970 fixes the consistency issues listed in your last comment.

`grep` tells me that all `conf.level` in function definitions are set to 0.95, and with my fixes, all `conf.int` arguments in function definitions are set to FALSE.

`broom.mixed` solves most of the unchecked boxes in the first comment.
