### ISSUE TITLE
Protect against matrix columns

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#405]
For `broom 0.5.0` we've moved to `tibble` output for all tidiers. Since `tibbles` are stricter than `data.frame`s, this currently introduces some bugs, in particular in instances where `data.frame` is happy to treat a `matrix` as multiple columns of a `data.frame`.

This is likely to affect users primarily in two ways:

1. Specifying model covariates as a matrix object will now error:

```r
library(broom)
library(quantreg)
#> Loading required package: SparseM
#> 
#> Attaching package: 'SparseM'
#> The following object is masked from 'package:base':
#> 
#>     backsolve

fit <- rq(stack.loss ~ stack.x, tau = .5)
augment(fit)
#> Error: Column `stack.x` must be a 1d atomic vector or a list

class(stack.x)
#> [1] "matrix"
```

2. Using `survival::Surv` or `survival::strata` objects. This mostly comes up when augmenting `coxph` or `survreg` models when no `data` or `newdata` is passed. Currently this throws an informative error, although previously it just worked:

```r
library(survival)

fit <- coxph(Surv(time, status) ~ age + sex, lung)
broom::augment(fit)
#> Error: Must specify either `data` or `newdata` argument.
```

Luckily, matrix-column support is coming (tidyverse/dplyr#3630) and we'll be able to support this again in the future.

In the meantime we should throw an informative error for (1) above and discuss this in `NEWS`.

**Comment by alexpghayes** [comment]
I started to partially address this in `validate_augment_input` a while back:

```r
> validate_augment_input(fit, model.frame(fit))
Error in value[[3L]](cond) : 
  `data` is malformed: must be coercable to a tibble.
Did you pass `data` the data originally used to fit your model?
```

The hint could use some work.

But I don't think `validate_augment_input` will be ready for `broom 0.5.0` because the `augment` spec is fairly complicated and `validate_augment_input` is too strict to introduce with just a couple days to spare.

**Comment by hturner** [comment]
A glm with the binomial response specified as a matrix is another case where this comes up.

**Comment by romainfrancois** [comment]
dev `dplyr` gives : 

``` r
library(dplyr, warn.conflicts = FALSE)
library(broom)
library(quantreg)
#> Loading required package: SparseM
#> 
#> Attaching package: 'SparseM'
#> The following object is masked from 'package:base':
#> 
#>     backsolve

fit <- rq(stack.loss ~ stack.x, tau = .5)
ag <- augment(fit)
ag$stack.x
#>       Air.Flow Water.Temp Acid.Conc.
#>  [1,]       80         27         89
#>  [2,]       80         27         88
#>  [3,]       75         25         90
#>  [4,]       62         24         87
#>  [5,]       62         22         87
#>  [6,]       62         23         87
#>  [7,]       62         24         93
#>  [8,]       62         24         93
#>  [9,]       58         23         87
#> [10,]       58         18         80
#> [11,]       58         18         89
#> [12,]       58         17         88
#> [13,]       58         18         82
#> [14,]       58         19         93
#> [15,]       50         18         89
#> [16,]       50         18         86
#> [17,]       50         19         72
#> [18,]       50         19         79
#> [19,]       50         20         80
#> [20,]       56         20         82
#> [21,]       70         20         91


library(survival)
#> 
#> Attaching package: 'survival'
#> The following object is masked from 'package:quantreg':
#> 
#>     untangle.specials

fit <- coxph(Surv(time, status) ~ age + sex, lung)
augment(fit)
#> Error: Must specify either `data` or `newdata` argument.
```

<sup>Created on 2019-11-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>
