### ISSUE TITLE
Documentation approach

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#419]
Many of the tidiers return the same type of information about different model types. For example, a bajillion `glance` methods return a tibble with an `AIC` column.

Ideally, I'd like to document what the `AIC` column represents in a single place, so that all those glance methods benefit from the same documentation and there's no need to copy-paste any changes to the description.

Currently, most methods document the return value with something like:

```r
#' @rdname betareg_tidiers
#'
#' @return `glance` returns a one-row tibble with columns:
#'   \item{pseudo.r.squared}{the deviance of the null model}
#'   \item{logLik}{the data's log-likelihood under the model}
#'   \item{AIC}{the Akaike Information Criterion}
#'   \item{BIC}{the Bayesian Information Criterion}
#'   \item{df.residual}{residual degrees of freedom}
#'   \item{df.null}{degrees of freedom under the null}
#'
#' @seealso [glance()]
#' @export
glance.betareg <- function(x, ...) {
  ...
}
```

I'd like to replace this with something along the lines of

```r
#' @rdname betareg_tidiers
#'
#' @template glance_boilerplate
#' @return A one-row tibble with columns:
#'   -`pseudo.r.squared`
#'   -`logLik`
#'   -`AIC`
#'   -`BIC`
#'   -`df.residual`
#'   -`df.null`
#'
#' @seealso [output_column_glossary()], [glance()]
#' @export
glance.betareg <- function(x, ...) {
  ...
}
```

where somewhere in the boilerplate describes how to use `filter(column_glossary, used_by == "betareg")` to get see the descriptions of the return columns.

@dgrtwo thoughts?

**Comment by alexpghayes** [comment]
Update for anyone following along: the new plan is to document output columns names in `glance.yaml`, `tidy.yaml`, etc. These YAML files will then get translated into a tibble `column_glossary` that we will export as a data object. We will then use roxygen templates to pull the relevant columns from the `column_glossary` object and populate the documentation. I've started work on this in the `column_glossary` branch on my fork.

**Comment by alexpghayes** [comment]
I'm now convinced that `@evalRd` is the wrong approach. Consider

```r
#' @evalRd return_tidy("component", regression = TRUE)
#'
#' @details The tibble has one row for each term in the regression. The
#'   `component` column indicates whether a particular
#'   term was used to model either the `"mean"` or `"precision"`. Here the
#'   precision is the inverse of the variance, often referred to as `phi`.
#'   At least one term will have been used to model the precision `phi`.
tidy.ivreg <- ...
```

This (on my local branch) produces documentation for the standard regression terms, and also for the `"component"` column. The issue is that `tidy.kmeans` also uses the `component` column, and describes it as: `Cluster id as a factor. For a model ‘k' clusters, these will be 'as.factor(1:k)', or 'as.factor(0:k)' if there’s a noise term.`

The results of the `@evalRd` call don't show up at all if the documentation has any `@return` tag, so the options here are:

1. Deal with inconsistent column names immediately upon transitioning to `@evalRd`. This is an unrealistically large task at the moment.
2. Document the `component` column in `@details` or elsewhere. I'm opposed to this.

So I don't think `@evalRd` is flexible enough to standardize the `@return` documentation.

**Comment by dgrtwo** [comment]
How about named arguments in the ... of `return_tidy` can define additional columns and their documentation?

#' @evalRd return_tidy("component", regression = TRUE,
#'                     p.value = "The p-value",
#'                     AIC = "blablabla")

 This would also give the option of overriding one from e.g. the regression group.

**Comment by simonpcouch** [comment]
This has been addressed, as far as I'm aware!
