### ISSUE TITLE
Check `exponentiate` behavior in tidy methods

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#422]
i.e. how to report the std.error column, and also make sure to update the confidence interval

**Comment by vincentarelbundock** [comment]
A comment about this was made in the `mice` repository: https://github.com/amices/mice/pull/276#issuecomment-716111053

Currently, confidence intervals get exponentiated, but *not* the standard errors:

``` r
library(broom)
mod <- glm(vs ~ mpg + drat, mtcars, family=binomial)

tidy(mod, conf.int=TRUE)
#> # A tibble: 3 x 7
#>   term        estimate std.error statistic p.value conf.low conf.high
#>   <chr>          <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>
#> 1 (Intercept)   -7.76      4.00     -1.94   0.0525  -17.0      -0.804
#> 2 mpg            0.477     0.200     2.38   0.0173    0.165     0.980
#> 3 drat          -0.562     1.33     -0.422  0.673    -3.44      1.97

tidy(mod, exponentiate=TRUE, conf.int=TRUE)
#> # A tibble: 3 x 7
#>   term        estimate std.error statistic p.value     conf.low conf.high
#>   <chr>          <dbl>     <dbl>     <dbl>   <dbl>        <dbl>     <dbl>
#> 1 (Intercept) 0.000428     4.00     -1.94   0.0525 0.0000000413     0.448
#> 2 mpg         1.61         0.200     2.38   0.0173 1.18             2.67 
#> 3 drat        0.570        1.33     -0.422  0.673  0.0322           7.18
```

**Comment by alexpghayes** [comment]
I believe this is the correct behavior: quantiles (and thereby confidence intervals) are invariant under monotonic transformation (`exp()`) but variances are not. I agree that it is confusing to see the original scale standard-error alongside the exponentiated estimate and CI, but my impression is that the best option here is to improve the document better. Happy to consider alternative proposals.

**Comment by vincentarelbundock** [comment]
Circling back to this, but I recently tried Stata 14 and it looks like in the logistic regresion case at least, it does: `exp(b)*se`. I don't see a justification in the version of the docs under my eyes, so I'm not advocating this in particular. Just leaving here for future reference.

**Comment by tzoltak** [comment]
Proper transformation is `exp(b)*se` just as @vincentarelbundock has said. Justification is as follows:

1. Exponentiation is nonlinear, so the best we may do is to use linear approximation. It will be reasonable for either rather small `abs(b)` (exponential function is not so curvy around 0) or small `se`.
2. Linear approximation of the transformation using a smooth function is multiplication by derivative of this function at the point of transformation.
3. Derivative of `exp(x)` is `exp(x)` itself. Consequently we should multiply `se` by `exp(b)`.

**Comment by tzoltak** [comment]
To be precise: linear approximation is not literally the best we can do, but it's the best we can do reasonably easy (and what is generally used to do in such cases).
