### ISSUE TITLE
Check if tidy.density works for multivariate densities

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#438]
Write up an example and document how this works.

**Comment by alexpghayes** [comment]
Awesome! This issue is mostly because I haven't spent time looking into `stat::density()` yet. In particular, I'd like to know what the `x` and `y` vectors in the `density` output mean where the input is multivariate (i.e. a matrix). Then we should document this in `tidy.density()`. Does that make sense?

**Comment by pjpaulpj** [comment]
That makes sense. 

After reading the [documentation](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/density.html) for `stat::density()` , the following is my sense of what is happening (all quotes are from the documentation):

1. When supplied an `mXn` matrix `stat::density` first flattens the matrix into a row vector. So, a 3X4 matrix is flattened into a row vector with 12 elements. 
This is my inference from a couple of tests. The documentation is not explicit about this flattening stating only the following "x(input): the data from which the estimate is to be computed. For the default method a numeric vector: long vectors are not supported."


2. After this flattening, the `stat::density` function "disperses the mass of the empirical distribution function over a regular grid of at least 512 points and then uses the fast Fourier transform to convolve this approximation with a discretized version of the kernel and then uses linear approximation to evaluate the density at the specified points." 

3. The `x` vector in the output contains the grid points that are used to calculate the empirical distribution function as mentioned above. The `y` vector contains the associated probability density corresponding to each grid point. As mentioned above, at least 512 grid points are used to calculate the empirical distribution, this explains why in the resultant object, x and y are at least 512 elements long. 
The original values in the input vector/ matrix, need not be present in the output vector `x`.

4. Here's a small illustration of what I've written above. 

```
# Form two matrices with the same elements, but different row-column configurations 
test_mat1 <- matrix(c(1,2,3, 11,12,13), nrow = 2, ncol = 3, byrow = TRUE)
test_mat2 <- matrix(c(1,2,3, 11,12,13),  ncol = 1)

# Compute the density function on the above two matrices
d1 <- density(test_mat1)
d2 <- density(test_mat2)

# Check if the grid-points of the density distribution, and the associated densities are identical
identical(d1$x, d2$x)
identical(d1$y, d2$y)

# Check if input elements are present in the output vector
test_mat1 %in% d1$x
test_mat2 %in% d1$x
```

4. "The print method reports summary values on the x and y components." Would we like to replicate this behaviour?

**Comment by alexpghayes** [comment]
Well... wow. That wasn't what I was expecting. Thanks for digging into this.

So `stats::density()` only does univariate density estimation, but `density()` is a generic.

I think the current behavior of `tidy.density()` makes sense, but we should add a note in the documentation that multivariate data gets flattened into univariate data. I'm worried someone might assume `density()` works with matrices and would get confused by:

```r
d <- density(iris[, 1:4])
tidy(d)
```

Would you make a pull request adding a line or two of [documentation](http://r-pkgs.had.co.nz/man.html) about this? `tidy.density()` lives in `R/stats-tidiers.R` I believe.

**Comment by pjpaulpj** [comment]
Will make the pull-request and add documentation in a couple of days (2-3 days max).

**Comment by pjpaulpj** [comment]
I've added documentation via pull-request [here](https://github.com/tidymodels/broom/pull/456).
