### ISSUE TITLE
Unprotect examples

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#439]
i.e. don't wrap them in `if (require(...)) {}` blocks, so

```r
#' @examples 
#' if (require(package)) {
#'   # example here
#' }
```

becomes 

```r
#' @examples 
#'
#' # example here
#'
```

**Comment by pkq** [comment]
I'd be happy to make these changes. 😄 A couple questions:
1. Should instances of `requireNamespace()` get removed as well?
1. Should I add the corresponding `library()` calls?

**Comment by alexpghayes** [comment]
Awesome!

1. Yes.
2. Yes.

You can make sure that the examples work appropriately by running `devtools::check()`. Let me know if you need any pointers along the way!
