### ISSUE TITLE
Announcement: standardizing column names. Seeking feedback.

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#452]
Recently I've been looking at the column names in tidy output and I've found a large number of inconsistencies. We'd like to resolve some of these inconsistencies.

Over the next couple days I'll be opening issue threads for `tidy()`, `glance()` and `augment()` column names. In each thread, we'll entertain proposals for renaming output columns. To submit a proposal, please add a comment to the issue thread in the format:

> Current: `converged` / `convergence` / `isConv`
> Proposal: `converged`
> Other notes/comments: `converged` should always be either `TRUE` or `FALSE`.
> Methods affected:
>   - factanal
>   - lavaan
>   - rlm
>   - glance_optim
>   - nls

More importantly, please provide feedback on proposals. We'll be paying attention to thumbs up and thumbs down reactions as well as written comments. In particular, if you are a package maintainer, please point out changes that would be especially inconvenient/breaking.

The goal is bring as much standardization as possible with as few breaking changes as possible. The `lm` tidiers, for example, will not change since that would break too much existing code.

## Legacy columns names

We're also playing with idea of legacy column names -- column names that we'll keep around for backward compatibility, but that will not be acceptable for new tidiers. As an example, we might decide that to use `p_value` as the canonical name for columns containing p-values. New tidiers would be required to use `p_value` but existing tidiers could still use `p.value`.

## How will column name requirements be enforced

Column names from `tidy()`, `glance()` and `augment()` output are currently tested against glossaries (whitelists) of allowed names. These glossaries are the YAML files and are available [here](https://github.com/alexpghayes/modeltests/tree/master/data-raw). They are currently fairly messy and redundant.

**Comment by alexpghayes** [comment]
General principles for good column names:

- Use singular rather than plural: `cutoff` is better than `cutoffs`
- Use full words: `adjusted` is better than `adj`
- Use underscores to separate words: `my_column` is better than `my.column` and `mycolumn`

**Comment by alexpghayes** [comment]
Some concepts that show up over and over again that we should decide on standard language for:
- proportions
- cumulative measures
- penalty / smooth parameter
- how many of a thing there are: num/count/total/etc etc etc chaos
- clusters / classes and numeric responses
- variances of X

**Comment by alexpghayes** [comment]
More things to decide on standard language for:

- statistics
- p-values

**Comment by alexpghayes** [comment]
Is it better to use a general column name (`statistic`) or a column name specific to the context (`hotelling_t`)?

**Comment by kevinykuo** [comment]
+1 for standardizing on `lower_snake_case` going forward, and potentially enforcing it for all tidiers given enough notice.

**Comment by billdenney** [comment]
For the note:

> Other notes/comments: `converged` should always be either `TRUE` or `FALSE`.

Intermediate convergence states exist like false convergence or convergence with a rank-degenerate model.  How should those be managed?

**Comment by alexpghayes** [comment]
Yeah it seems like a character outcome would be better. Suggestions for categories? Should we include tolerance criterion information? Not sure how to do this and would love recommendations.

**Comment by billdenney** [comment]
I like character outcomes better.  And, I'd think that "Yes" and "No" would be the clear answers.  For intermediate results, I think that they would be system-dependent and require knowledge of the specific model type.
