### ISSUE TITLE
Column names: tidy()

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#455]
This issue thread is for proposals for column names changes. Please read #452 before commenting.

**Comment by alexpghayes** [comment]
Existing column names (this is fairly complete, but not perfect -- it was scraped from the `\value{}` section of `.Rd` files)

- column: '...'
  description: The initial columns correspond to the grouping factors on the right
    hand side of the model formula.
  used_by: survdiff
- column: cumulative
  description: Cumulative percentage of variation explained.
  used_by:
  - tidy_irlba
  - tidy_svd
  - prcomp
- column: PC
  description: An integer vector indicating the principal component.
  used_by:
  - tidy_irlba
  - tidy_svd
  - prcomp
- column: percent
  description: Percentage of variation explained.
  used_by:
  - tidy_irlba
  - tidy_svd
  - prcomp
- column: row
  description: Needs custom description
  used_by:
  - tidy_irlba
  - tidy_svd
  - prcomp
- column: std.dev
  description: Standard deviation explained by this PC.
  used_by:
  - tidy_irlba
  - tidy_svd
  - prcomp
- column: value
  description: Needs custom desciption.
  used_by:
  - tidy_irlba
  - tidy_svd
  - prcomp
- column: acf
  description: calculated correlation
  used_by: acf
- column: adj.p.value
  description: P-value adjusted for multiple comparisons
  used_by: TukeyHSD
- column: alternative
  description: Alternative hypothesis (character).
  used_by:
  - binWidth
  - htest
- column: bias
  description: Bias of the statistic.
  used_by: boot
- column: ci.width
  description: Expected width of confidence interval.
  used_by: binWidth
- column: class
  description: The class under consideration.
  used_by:
  - confusionMatrix
  - poLCA
- column: cluster
  description: A factor describing the cluster from 1:k
  used_by: kmeans
- column: column1
  description: Name or index of the first column being described
  used_by: rcorr
- column: column2
  description: Name or index of the second column being described
  used_by: rcorr
- column: comparison
  description: Levels being compared, separated by -
  used_by: TukeyHSD
- column: component
  description: Cluster id as a factor. For a model `k` clusters, these will be `as.factor(1:k)`,
    or `as.factor(0:k)` if there's a noise term.
  used_by: Mclust
- column: conf.high
  description: The upper end of a confidence interval for the term under consideration.
    Included only if `conf.int = TRUE`.
  used_by:
  - Arima
  - betareg
  - biglm
  - btergm
  - cch
  - confusionMatrix
  - cv.glmnet
  - felm
  - glm
  - glmRob
  - gmm
  - htest
  - ivreg
  - kappa
  - lavaan
  - lm
  - lmodel2
  - lmRob
  - mjoint
  - nlrq
  - nls
  - plm
  - rlm
  - rq
  - rqs
  - speedlm
  - survfit
  - survreg
  - TukeyHSD
- column: conf.low
  description: The lower end of a confidence interval for the term under consideration.
    Included only if `conf.int = TRUE`.
  used_by:
  - Arima
  - betareg
  - biglm
  - btergm
  - cch
  - confusionMatrix
  - cv.glmnet
  - felm
  - glm
  - glmRob
  - gmm
  - htest
  - ivreg
  - kappa
  - lavaan
  - lm
  - lmodel2
  - lmRob
  - mjoint
  - nlrq
  - nls
  - plm
  - rlm
  - rq
  - rqs
  - speedlm
  - survfit
  - survreg
  - TukeyHSD
- column: cutoff
  description: The cutoff used for classification. Observations with predicted probabilities
    above this value were assigned class 1, and observations with predicted probabilities
    below this value were assigned class 0.
  used_by: roc
- column: denominator
  description: The denominator, which is tau=kendall_score/denominator.
  used_by: Kendall
- column: dev.ratio
  description: fraction of null deviance explained at each value of lambda
  used_by: glmnet
- column: df
  description: Degrees of freedom used by this term in the model.
  used_by:
  - anova
  - aov
  - aovlist
- column: distance
  description: Distance between items
  used_by: dist
- column: estimate
  description: Estimated value of the term under consideration. Needs additional custom info.
  used_by:
  - aareg
  - Arima
  - betareg
  - biglm
  - btergm
  - cch
  - coeftest
  - confusionMatrix
  - coxph
  - cv.glmnet
  - ergm
  - felm
  - fitdistr
  - gamlss
  - garch
  - glm
  - glmnet
  - glmRob
  - gmm
  - htest
  - ivreg
  - kappa
  - lavaan
  - lm
  - lmodel2
  - lmRob
  - mjoint
  - muhaz
  - multinom
  - nlrq
  - nls
  - plm
  - poLCA
  - rcorr
  - ridgelm
  - rlm
  - rq
  - rqs
  - speedlm
  - survexp
  - survfit
  - survreg
  - TukeyHSD
- column: estimate1
  description: Sometimes two estimates are computed, such as in a two-sample t-test
  used_by: htest
- column: estimate2
  description: Sometimes two estimates are computed, such as in a two-sample t-test
  used_by: htest
- column: event
  description: observed number of events
  used_by: pyears
- column: exp
  description: weighted expected number of events in each group
  used_by: survdiff
- column: expected
  description: expected number of events (present only if a `ratetable` term is present)  If
    the `data.frame = TRUE` argument is supplied to `pyears`, this is simply the contents
    of `x$data`.
  used_by: pyears
- column: flX
  description: Factor loading of term on factor X. There will be as many columns of
    this format as there were factors fitted.
  used_by: factanal
- column: fpr
  description: The false positive rate at the given cutoff.
  used_by: roc
- column: GCV
  description: generalized cross validation value for this lambda
  used_by: ridgelm
- column: group
  description: The group (if specified) in the lavaan model
  used_by: lavaan
- column: group1
  description: First group being compared
  used_by: pairwise.htest
- column: group2
  description: Second group being compared
  used_by: pairwise.htest
- column: index
  description: Index (i.e. date or time) for a `ts` or `zoo` object.
  used_by:
  - ts
  - zoo
- column: item1
  description: First item
  used_by: dist
- column: item2
  description: Second item
  used_by: dist
- column: kendall_score
  description: Kendall score.
  used_by: Kendall
- column: lag
  description: lag values
  used_by: acf
- column: lambda
  description: Value of penalty parameter lambda.
  used_by:
  - cv.glmnet
  - glmnet
  - ridgelm
- column: mcmc.error
  description: The MCMC error
  used_by: ergm
- column: mean
  description: The mean for each component. In case of 2+ dimensional models, a column
    with the mean is added for each dimension. NA for noise component
  used_by: Mclust
- column: meansq
  description: Mean sum of squares. Equal to total sum of squares divided by
    degrees of freedom.
  used_by:
  - anova
  - aov
  - aovlist
- column: method
  description: Needs custom info.
  used_by:
  - htest
  - lmodel2
- column: 'n'
  description: Needs custom info.
  used_by:
  - binDesign
  - binWidth
  - pyears
  - rcorr
- column: 'N'
  description: number of subjects in each group
  used_by: survdiff
- column: n.censor
  description: number of censored events
  used_by: survfit
- column: n.event
  description: number of events at time t
  used_by: survfit
- column: n.risk
  description: Number of individuals at risk at time zero.
  used_by:
  - survexp
  - survfit
- column: num.df
  description: Degrees of freedom
  used_by: manova
- column: nzero
  description: Number of coefficients that are exactly zero for given lambda.
  used_by: cv.glmnet
- column: obs
  description: weighted observed number of events in each group
  used_by: survdiff
- column: op
  description: The operator in the model syntax (e.g. `~~` for covariances, or `~`
    for regression parameters)
  used_by: lavaan
- column: outcome
  description: Outcome of manifest variable
  used_by: poLCA
- column: p
  description: True proportion.
  used_by: binWidth
- column: p.value
  description: Needs custom information.
  used_by:
  - aareg
  - anova
  - aov
  - aovlist
  - betareg
  - biglm
  - cch
  - coeftest
  - confusionMatrix
  - coxph
  - ergm
  - felm
  - gamlss
  - garch
  - glm
  - glmRob
  - gmm
  - htest
  - ivreg
  - Kendall
  - lavaan
  - lm
  - lmRob
  - manova
  - mjoint
  - multinom
  - nlrq
  - nls
  - pairwise.htest
  - plm
  - rcorr
  - rlm
  - rq
  - rqs
  - speedlm
  - survreg
- column: parameter
  description: Needs custom info.
  used_by:
  - tidy_optim
  - gamlss
  - htest
- column: power
  description: Power achieved for given value of n.
  used_by: binDesign
- column: proportion
  description: The mixing proportion of each component
  used_by: Mclust
- column: pyears
  description: person-years of exposure
  used_by: pyears
- column: response
  description: Which response column the coefficients correspond to (typically `Y1`, `Y2`, etc).
  used_by:
  - glm
  - glmRob
  - lm
  - lmRob
  - rlm
  - speedlm
- column: robust.se
  description: robust version of standard error estimate (only when `x` was called
    with `dfbeta = TRUE`)
  used_by: aareg
- column: scale
  description: Scaling factor of estimated coefficient
  used_by: ridgelm
- column: series
  description: Name of the series (present only for multivariate time series).
  used_by:
  - ts
  - zoo
- column: size
  description: Number of points assigned to cluster.
  used_by:
  - kmeans
  - Mclust
- column: state
  description: state if multistate survfit object inputted
  used_by: survfit
- column: statistic
  description: Needs custom information
  used_by:
  - aareg
  - anova
  - aov
  - aovlist
  - betareg
  - biglm
  - boot
  - cch
  - coeftest
  - coxph
  - felm
  - gamlss
  - garch
  - glm
  - glmRob
  - gmm
  - htest
  - ivreg
  - Kendall
  - lavaan
  - lm
  - lmRob
  - manova
  - mjoint
  - multinom
  - nlrq
  - nls
  - plm
  - rlm
  - rq
  - rqs
  - speedlm
  - survreg
- column: std.all
  description: Standardized estimates based on both the variances of both (continuous)
    observed and latent variables.
  used_by: lavaan
- column: std.error
  description: Standard error of the estimate. `boot` needs custom info.
  used_by:
  - aareg
  - Arima
  - betareg
  - biglm
  - boot
  - cch
  - coeftest
  - coxph
  - cv.glmnet
  - ergm
  - felm
  - fitdistr
  - gamlss
  - garch
  - glm
  - glmRob
  - gmm
  - ivreg
  - lavaan
  - lm
  - lmRob
  - mjoint
  - multinom
  - nlrq
  - nls
  - plm
  - poLCA
  - rlm
  - rq
  - rqs
  - speedlm
  - survfit
  - survreg
- column: std.lv
  description: Standardized estimates based on the variances of the (continuous) latent
    variables only
  used_by: lavaan
- column: std.nox
  description: Standardized estimates based on both the variances of both (continuous)
    observed and latent variables, but not the variances of exogenous covariates.
  used_by: lavaan
- column: step
  description: which step of lambda choices was used
  used_by: glmnet
- column: strata
  description: strata if stratified survfit object inputted
  used_by: survfit
- column: stratum
  description: The error stratum
  used_by: aovlist
- column: sumsq
  description: Sum of squares explained by this term
  used_by:
  - anova
  - aov
  - aovlist
- column: term
  description: Needs custom info.
  used_by:
  - aareg
  - anova
  - aov
  - aovlist
  - Arima
  - betareg
  - biglm
  - boot
  - btergm
  - cch
  - coeftest
  - confusionMatrix
  - ergm
  - felm
  - fitdistr
  - gamlss
  - garch
  - glm
  - glmnet
  - glmRob
  - gmm
  - ivreg
  - lavaan
  - lm
  - lmodel2
  - lmRob
  - mjoint
  - multinom
  - nlrq
  - nls
  - plm
  - ridgelm
  - rlm
  - rq
  - rqs
  - speedlm
  - survreg
  - TukeyHSD
- column: time
  description: Point in time.
  used_by:
  - muhaz
  - survexp
  - survfit
- column: tpr
  description: The true positive rate at the given cutoff.
  used_by: roc
- column: type
  description: Either "weighted" or "unweighted"
  used_by: kappa
- column: uniqueness
  description: Proportion of residual, or unexplained variance
  used_by: factanal
- column: value
  description: Needs custom info.
  used_by:
  - tidy_optim
  - ts
  - zoo
- column: var_kendall_score
  description: Variance of the kendall_score.
  used_by: Kendall
- column: variable
  description: Needs custom info.
  used_by:
  - factanal
  - poLCA
- column: variance
  description: In case of one-dimensional and spherical models, the variance for each
    component, omitted otherwise. `NA` for noise component
  used_by: Mclust
- column: withinss
  description: The within-cluster sum of squares
  used_by: kmeans
- column: y.value
  description: The response level
  used_by: multinom
- column: z
  description: z score
  used_by: aareg

**Comment by alexpghayes** [comment]
Some current conflicts I am aware of for `tidy()` (some of these not in the list above):

- `acf` / `autocorrelation`
- `comp` / `component`
- `conf.high` / `upper`
- `conf.low` / `lower`
- `exp` / `expected`
- `df` / `num.df`
- `n` / `N` / `size`
- `parameter` / `term` / `variable`
- `p` / `proportion`
- `strata` / `stratum`
- `response` / `y.level` / `y.value`
- `statistic` / `z`

It seems like there's also some redundancy in column names that describe "percent of variance" explained type information.

**Comment by copernican** [comment]
`nzero` is used by `cv.glmnet()`. The description above is "number of coefficients that are exactly zero for given lambda." I think this may be reversed. The documentation for `cv.glmnet()` states that this is actually the "number of non-zero coefficients at each lambda." If you agree (and if appropriate), I am happy to file an issue in **`modeltests`** instead, or to submit a PR.

**Comment by alexpghayes** [comment]
A PR or an issue would be ideal!
