### ISSUE TITLE
RFD/wishlist: option to standardize coefficients?

### ISSUE THREAD

**Issue by bbolker** [tidymodels/broom#460]
`dotwhisker` has an option to standardize coefficients.  It would be nice/interesting to fold this capability in upstream, in `broom` ... cf. https://github.com/fsolt/dotwhisker/issues/82

**Comment by alexpghayes** [comment]
So the proposal is for something like:

```
tidy(..., standardize = TRUE)
```

to match coefficients to terms in the `model.frame()` and scale by standard deviations?

I'm interested but think we'd want a very robust system for matching regression terms with predictor columns.

**Comment by bbolker** [comment]
I think I would prefer something slightly more flexible, i.e. `standardize=c("no","2sd","1sd")` (with `"none"` the default, of course).  I agree that matching regression terms is tricky.  I think, however, that if the model.matrix is accessible (i.e. `model.matrix(model.frame(.))` works], then standardizing column-by-column is an acceptable solution (see discussion at https://github.com/fsolt/dotwhisker/issues/82). Otherwise, we have to look at the `terms` attribute very carefully ...
