### ISSUE TITLE
Prediction intervals in augment()?

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#467]
As far as I am aware, `augment()` always returns confidence intervals rather than prediction intervals. I suspect that people often treat confidence intervals as prediction intervals without realizing it, and wonder if adding an explicit option for prediction intervals might result in catching this distinct more often.

**Aside**: this issue brought to you by an incoming `se_fit = FALSE/TRUE` argument to `augment()` methods so that users can control when to calculate confidence intervals for predictions, as this can be time consuming for some models.

**Comment by benwhalley** [comment]
I came here trying to work out how to get confidence intervals from `augment`, but it doesn't seem like you can - at least for `lm` or `glm`.  Agree that it would be great to have prediction intervals. As a point for reference, `rstanarm` makes this distinction clear  in their naming of `posterior_predict` vs `posterior_linpred`.

**Comment by alexpghayes** [comment]
Slowly working on a separate prediction backend to make this easier!

Hmmm that makes sense. Will look into some more.

**Comment by bwiernik** [comment]
Also stumbled here looking for how to get intervals from `agument()`. It seems odd that `agument.rq` accepts the `interval` argument, but `lm` and `glm` silently drop it. The basic step to pass `interval` to `predict` methods that support (like `prediction` does) until a more comprehensive solution is implemented would be really helpful.

**Comment by alexpghayes** [comment]
A PR is very welcome! Unfortunately this has pretty much fallen off the bottom of my todo list.

**Comment by bwiernik** [comment]
Okay! I will try to find some time to do that PR

**Comment by IndrajeetPatil** [comment]
Same as https://github.com/tidymodels/broom/issues/199. I think #199 can be closed in favor of this issue.
