### ISSUE TITLE
Documentation for the ordinal tidiers

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#478]
Didn't get updated with the rest of the tidiers but it needs it.

**Comment by vincentarelbundock** [comment]
This can probably be closed given that `tidy.clm.Rd`, `tidy.clm,.Rd`, `augment.clm.Rd`, `glance.clm.Rd`, and `glance.clmm.Rd` were update 4 days ago in https://github.com/tidymodels/broom/commit/52630677ede7b7bc6e642e07a0839c586293d9d0 (there is no `augment.clmm`)
