### ISSUE TITLE
Drop the reshape2 dependency

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#480]

**Comment by PirateGrunt** [comment]
I would love to have a go at this. Should I be working on the `master` branch, or is there another? Or should I create a new branch for this?

**Comment by alexpghayes** [comment]
That would be awesome! Definitely work on a new branch!

I'm pretty sure `reshape2` is a dependency because it gets used once to tidy an arbitrary dimension array. I don't think the current tidyverse tools have support for such arrays yet, but would love to have you take a look around and see if there's something you can get to work.

Alternatively, if we could just copy some from `reshape2` so we don't have to depend on the whole package, that would be great.

**Comment by PirateGrunt** [comment]
I've removed the dependency from `tidy.dist` and `list-xyz`. Pull request just updated and being checked.

`reshape2` also appears in the tidiers for `svd`, `polca` and `ks`. In each of those cases, it looks as though it's being used to melt a 3-D array. The fixes for the first two were fairly straightforward. For those remaining, I think `reshape2` may be an appropriate option. Replacing it would basically mean re-writing something that `reshape` already does well, i.e. melting high-dimensional data.

Thoughts?

**Comment by simonpcouch** [comment]
This was addressed in #852.🙂
