### ISSUE TITLE
Model -> LaTeX. A case for broom?

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/broom#492]
I came across [this](https://github.com/tidyverts/fable/issues/4) issue over on `fable`, and thought that this might be a useful generic for a number of models (not just time series). I'm wondering if you've ever thought of including this kind of thing in `broom`, or if this would be better suited for a different package (if it even seems useful). I'm not sure every model would have some kind of latex equivalent output, but many would.

Pulling the relevant stack exchange question out too:
https://stats.stackexchange.com/questions/340838/good-resource-for-converting-arima-output-in-r-to-equation-form

**Comment by alexpghayes** [comment]
Yes! I am a huge fan of this.

Definitely will be a lot of work but this fits well with the mission of broom as I see it.

cc @dgrtwo

**Comment by alexpghayes** [comment]
Someone else is taking this on at https://github.com/datalorax/equatiomatic!
