### ISSUE TITLE
Contributor code of conduct is 404

### ISSUE THREAD

**Issue by PirateGrunt** [tidymodels/broom#493]
The contributor code of conduct referenced in the README.md returns a 404 error. 
I think this link: https://github.com/PirateGrunt/broom/blob/master/CODE_OF_CONDUCT.md needs to be updated.

**Comment by IndrajeetPatil** [comment]
Code of conduct has been moved to a different directory now:
https://github.com/tidymodels/broom/blob/master/.github/CODE_OF_CONDUCT.md
