### ISSUE TITLE
tidy.polr throws bug when conf.int = T

### ISSUE THREAD

**Issue by haozhu233** [tidymodels/broom#497]
Hello, I found that `tidy.polr` generates a bug when `conf.int = T`. It seems that the `colnames` should be replaced with `names`.

```r
library(tidyverse)
library(broom)
MASS::polr(Species ~ Sepal.Length, data = iris, Hess = T) %>% 
  tidy(exponentiate = T, conf.int = T)
#> Error in `colnames<-`(`*tmp*`, value = c("conf.low", "conf.high")): attempt to set 'colnames' on an object with less than two dimensions
```

**Comment by rshaffer14** [comment]
Looks like I'm using 0.5.2. What is the dev version that I should be on? 
Thanks so much!

**Comment by alexpghayes** [comment]
Use the most recent dev version. You can install it with
`devtools::install_github("tidymodels/broom")`.
