### ISSUE TITLE
Using glance on a non-model object causes R to crash

### ISSUE THREAD

**Issue by BrianOB** [tidymodels/broom#503]
First time reporting an issue in GitHub, so I hope this is correct.

Brief description of the problem
Just learned about the glance() function. In taking it out for a spin, I used it on a tibble. It crashed the R session. Admittedly, it's not supposed to be used on a tibble, but I expected just an error message and, instead, got an error message followed by a message that the R session had terminated.

``` r
library(tidyverse)
library(broom)

test <- tibble(x = 1:5, y = c('a','b','c','d','e'))
test <- test %>% 
  mutate(z = list(1:3, 2:4, 3:5, 4:6, 5:7))
glance(test)
#> Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
```

<sup>Created on 2018-10-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
```

**Comment by alexpghayes** [comment]
I believe this is a duplicate of #154. There's a plan to fix this and replace it with a more informative error message.

**Comment by BrianOB** [comment]
Looks like it is. Sorry about that. I searched for all glance issues before posting but missed that one.

**Comment by alexpghayes** [comment]
No problem. Just FYI, this is fixed in the development version of broom, and I just added the warning for the linked issue:

``` r
library(broom)

glance(iris)
#> Error: There is no glance method for data frames. Did you mean `dplyr::glimpse()`?
glance(tibble::as_tibble(iris))
#> Error: There is no glance method for tibbles. Did you mean `dplyr::glimpse()`?
```

<sup>Created on 2018-10-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
