### ISSUE TITLE
Adding tidiers for regression models not currently covered by `broom`

### ISSUE THREAD

**Issue by IndrajeetPatil** [tidymodels/broom#505]
Here are some commonly used (`class` of) regression models that `broom` currently doesn't support but would be lovely if it does.

- [ ] zero-inflated regression: `zeroinfl` (https://cran.r-project.org/web/packages/pscl/vignettes/countreg.pdf)

- [ ] hurdle models for count data regression: `hurdle` (https://cran.r-project.org/web/packages/pscl/vignettes/countreg.pdf)

- [x] robust regression from `robustbase` package: `lmrob` (https://cran.r-project.org/web/packages/robustbase/robustbase.pdf)

- [ ] multivariate ordinal regression models: `mvord` (https://cran.r-project.org/web/packages/mvord/vignettes/vignette_mvord2.html)

- [ ] multinomial logit model: `mnlogit` (https://cran.r-project.org/web/packages/mnlogit/index.html)

- [ ] vector generalized linear models: `vglm` (https://cran.r-project.org/web/packages/VGAM/VGAM.pdf)

- [ ] outlier-robust fit for Generalized Additive Models: `rgam` (https://cran.r-project.org/web/packages/rgam/index.html)

- [ ] resistant regression: `lqs` (https://www.rdocumentation.org/packages/MASS/versions/7.3-51.4/topics/lqs)

- [ ] Robust Linear Regression with Compositional Data as Covariates : `complmrob` (https://cran.r-project.org/web/packages/complmrob/complmrob.pdf)

(I will keep updating this list as I find new, unsupported regression models.)

Unless somebody else does it first, I will also try to do a PR with these tidiers.

**Comment by dgrtwo** [comment]
Interesting: we have implementations for lmRob and glmRob from the robust package (though they're basically thin wrappers for the lm tidiers), but I hadn't heard of the lowercase versions. Sounds useful!

**Comment by bbolker** [comment]
when you (or someone, maybe me?) does `pscl::zeroinfl`, (a) worth doing `pscl::hurdle` at the same time, (b) worth trying to maintain consistency with the conventions in `broom.mixed`, which already has some zero-inflation support for `glmmTMB` models ...

**Comment by billdenney** [comment]
What about tidying the output of `optim()`?  A minor challenge with this is that it returns a list, not a named object class (so, the tidy method would need to look at the list and see if it appeared to be `optim()` output).

If interested, I'd be happy to generate a PR.

**Comment by alexpghayes** [comment]
There currently are tidiers for `optim()`! Do these work well for you, or do you have suggested changes?

``` r
library(broom)

r <- function(x) (3 - x[1])^2 + 4 * (x[2] - x[1]^2)^2
res <- optim(1:2, r)

tidy(res)
#> # A tibble: 2 x 2
#>   parameter  value
#>   <chr>      <dbl>
#> 1 parameter1  3.00
#> 2 parameter2  9.00
glance(res)
#> # A tibble: 1 x 4
#>          value function.count gradient.count convergence
#>          <dbl>          <int>          <int>       <int>
#> 1 0.0000000358            113             NA           0
```

<sup>Created on 2018-11-16 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by billdenney** [comment]
Whoops!  I had broom.mixed not broom loaded.  I have an idea for `optim()` that I'll bring up in a separate issue.

**Comment by mattle24** [comment]
@IndrajeetPatil I'm working on `glance` for `glmrob` objects, but I'm not familiar with the robustbase package. I'm having trouble finding goodness of fit measures to include. Do you have any suggestions? For `lmrob` objects, I have included r.squared, sigma, and df.residual, but these fields either seem to not exist or are NULL in `glmrob`.

**Comment by IndrajeetPatil** [comment]
@mattle24 Sorry for the late reply. Completely missed this in the notifications. 
I can't find that information as well for `glmrob` objects, so maybe not much that can be done about that.

**Comment by mattle24** [comment]
All good, thanks for checking!

**Comment by HedvigS** [comment]
(I would also love a function for tidying hurdle objects. Thanks for a great package regardless :) )

**Comment by lirpa939** [comment]
> (I would also love a function for tidying hurdle objects. Thanks for a great package regardless :) )
I would love to see this too!

**Comment by IndrajeetPatil** [comment]
Closing following https://github.com/tidymodels/broom/issues/795#issuecomment-639547477
