### ISSUE TITLE
Using tidy() on list/map object returns infinite recursion error

### ISSUE THREAD

**Issue by ldlpdx** [tidymodels/broom#512]
I've attached the `us_states` file from the `USABoundaries` package to a data set that I'm working with. I read that `fortify()` is deprecated and that I should use `tidy()` from the `broom` package, instead. At first, I was getting a cstack error, so I had to go in and create a new plist file to expand cstack limits. That worked, but now I'm getting an infinite recursion error.

```
> map_totals_df <- tidy(map_totals)
Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
Error during wrapup: evaluation nested too deeply: infinite recursion / options(expressions=)?
```  

The data file w/o the map file attached is [here](https://github.com/ldlpdx/r_stats/blob/master/pop_total.csv).

Here is my version info:
```

> R.version
               _                           
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          5.1                         
year           2018                        
month          07                          
day            02                          
svn rev        74947                       
language       R                           
version.string R version 3.5.1 (2018-07-02)
nickname       Feather Spray  
```

**Comment by alexpghayes** [comment]
Hmm will take a look soon.

**Comment by mikmart** [comment]
Likely related:

``` r
broom::tidy(tibble::as_tibble(mtcars))
#> Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
```

<sup>Created on 2019-03-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by alexpghayes** [comment]
Fairly sure this is a bug in the now removed data frame tidiers. Closing, please open a new issue if you come across something similar in the future and I was wrong!
