### ISSUE TITLE
make augment work with matrix-valued predictors?

### ISSUE THREAD

**Issue by bbolker** [tidymodels/broom#515]
At present the default behaviour of `augment.lm()` (for example) when neither `data` nor `newdata` is specified is to try to extract the model frame of the object *and convert it to a tibble*. This fails when the model frame contains matrix-valued predictors, e.g. if `base::scale()`, `stats::poly()`, or any of the spline bases (`splines::ns()` etc.) are used in the model: `Error: Provided data must be coercible to tibble`. 

This is easy to work around (just specify `data` explicitly), but it would be nice if it Just Worked.

I started to code a solution that used `do.call(data.frame, model.frame(x))` as the default (I changed the default value of the argument to `NULL`, as I don't like weird/magic statements appearing in the default argument list).  This works OK (although it uses `make.names()` on the model frame, so e.g. `scale(x)` turns into `scale.x.`; this could be changed if desired).  I was going to submit a PR, but for reasons I haven't figured out yet it breaks `check_augment_function()` (when calling with `data=newdata, add_missing=TRUE` ...)

Example:

```
set.seed(101)
dd <- data.frame(y=rpois(100,lambda=2),x=rnorm(100))
m_lm <- lm(y~poly(x,2), data=dd)
m_lm2 <- lm(y~scale(x), data=dd)
library(broom)
augment(m_lm,data=dd)  ##OK
augment(m_lm)  
## Error: Provided data must be coercible to `tibble`.
augment(m_lm2)
## Error: Provided data must be coercible to `tibble`.
names(augment(m_lm2,do.call(data.frame,model.frame(m_lm2))))
```

**Comment by alexpghayes** [comment]
Either one or two dplyr/tibble releases out. There's a thread somewhere tracking progress but I don't recall exactly where.

**Comment by bbolker** [comment]
Hmmm.  That feels like a while.  Any chance of including a more informative error message, something like the following?  (I can submit a PR if you want; I was having trouble running tests, no longer 100% convinced it's my fault ...)  (I did eventually find the documentation that mentions this issue ... but still think it would be better if users could be helped more ...)

```
--- a/R/utilities.R
+++ b/R/utilities.R
@@ -25,6 +25,10 @@ rename2 <- function(.data, ...) {
 #' @return A `tibble` potentially with a `.rownames` column
 #' @noRd
 as_broom_tibble <- function(data) {
+  if (is.data.frame(data) && any(vapply(data,is.matrix,logical(1)))) {
+      error("Provided data includes matrix-valued elements: pass data as a tibble or use do.call(data.frame, orig_data) to collapse")
+      ## data <- do.call(data.frame,data) ## ??
+  }
```

**Comment by alexpghayes** [comment]
That may be worthwhile. I remember initially writing an error message that suggested explicitly passing something to the `data` argument, but decided against at the time for a reason that now escapes me.

I don't think that coercing to a data frame and then coercing back to a tibble isn't particularly clean, but if you've got an example where that's necessary / makes life easier let me know and we can think about it as a short term patch.

**Comment by bbolker** [comment]
Hmm, I'm

**Comment by bbolker** [comment]
If you don't want to garble the names, I think `do.call(data.frame, model.frame(x), check.names=FALSE)` will work (at the price of having column names that are not legal R variables names -- the reason that `check.names=TRUE` by default).

Of your three choices, I would **strongly** favour options 1 or 3, don't have strong feelings about the tradeoff between user convenience vs. encouraging better user behaviour. (If you really want to force it, throw an error if `data` and `newdata` are both missing ...)

In general I predict you will find it very difficult to write a reliable method to extract the data that a model was originally fitted with; pretty much the only way to do this is to hope that `eval(getCall(model)$data)` works (which it won't unless you're working in a simple environment where nothing gets passed in and out of functions).
