### ISSUE TITLE
tidy.merMod gives bind_rows warnings

### ISSUE THREAD

**Issue by billdenney** [tidymodels/broom#521]
When running `tidy` on a lmer model, two warnings of "binding factor and character vector, coercing into character vector" occur.  At least one of them appears to be due to not having `stringsAsFactors=FALSE` here.

https://github.com/tidymodels/broom/blob/8a58412c0d02d8d50a730cbcd2d049b56c04d4f8/R/lme4-tidiers.R#L109

``` r
library(broom)
library(lme4)
#> Loading required package: Matrix

tidy(lmer(Petal.Width~(1|Species), data=iris))
#> Warning in bind_rows_(x, .id): binding factor and character vector,
#> coercing into character vector
#> Warning in bind_rows_(x, .id): binding character and factor vector,
#> coercing into character vector
#> # A tibble: 3 x 5
#>   term                    estimate std.error statistic group   
#>   <chr>                      <dbl>     <dbl>     <dbl> <chr>   
#> 1 (Intercept)                1.20      0.518      2.32 fixed   
#> 2 sd_(Intercept).Species     0.896    NA         NA    Species 
#> 3 sd_Observation.Residual    0.205    NA         NA    Residual
```

Created on 2018-10-26 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by bbolker** [comment]
may I recommend the `broom.mixed` version of this tidier?  At some point the mixed-model tidiers in broom will be deprecated in favour of the broom.mixed versions ...

**Comment by alexpghayes** [comment]
Strongly second this. If you can check out `broom.mixed` to see if your problem has already been resolved and then make a PR there if it hasn't, that would be ideal. (For details on the home of mixed model tidiers, check out #329). The `lme` family of tidiers will be deprecated in the next release.

**Comment by billdenney** [comment]
I'll move there.

**Comment by alexpghayes** [comment]
Awesome! Thanks for the PR and using `broom`!

**Comment by billdenney** [comment]
FYI, it's not an issue in `broom.mixed`.  I'll close this here, and no worries if you want to just close the PR.
