### ISSUE TITLE
tidy method for confusionMatrix

### ISSUE THREAD

**Issue by dchiu911** [tidymodels/broom#523]
Is the McNemar test associated with the kappa statistic? Currently the `tidy` method for `confusionMatrix` puts the McNemar p-value on the same row as kappa. I am not sure that this is accurate.
``` r
set.seed(1)
broom::tidy(caret::confusionMatrix(iris$Species, sample(iris$Species)), by_class = FALSE)
#> # A tibble: 2 x 5
#>   term     estimate conf.low conf.high p.value
#>   <chr>       <dbl>    <dbl>     <dbl>   <dbl>
#> 1 accuracy  0.327      0.252     0.408   0.599
#> 2 kappa    -0.01000   NA        NA       0.220
```

<sup>Created on 2018-10-31 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mkuehn10** [comment]
Should the p-value from McNemar's test be a separate row then or just don't include it?  I think I mistakenly assumed they went together because they are together in the output of confusionMatrix.

**Comment by alexpghayes** [comment]
I'm not that familiar with the `caret` output to be totally honest. @topepo what would be the appropriate way to report this?

**Comment by topepo** [comment]
It isn't associated with kappa. It should be on a separate line.

**Comment by malcolmbarrett** [comment]
I'll take care of this

**Comment by mkuehn10** [comment]
@malcolmbarrett Thanks for looking in to this and fixing it!
