### ISSUE TITLE
support for regsubsets (from leaps)

### ISSUE THREAD

**Issue by randomgambit** [tidymodels/broom#524]
Hello there!

I was wondering if you were planning to add support for the well-known `regsubsets` output from the `leaps` package. This is pretty standard best-subset selection in R. Would be pretty nice to `tidyfying` all that. :)

What do you think?
Thanks!

**Comment by alexpghayes** [comment]
This seems like a good idea. Did you close because you found an alternative solution?

**Comment by randomgambit** [comment]
ha actually it was a fat finger on my phone :) yes, that could be nice. the current console output is really horrible...

**Comment by randomgambit** [comment]
well done my man
