### ISSUE TITLE
augment.glm() not providing pearson residuals

### ISSUE THREAD

**Issue by asbates** [tidymodels/broom#526]
`augment.glm()` returns deviance residuals when the argument `type.residuals = "pearson"` is specified. The below example shows that `augment` doesn't provide the same residuals as using `rstandard`. The  [code](https://github.com/tidymodels/broom/blob/bea70cddcf3e100bc5d5a01505852077c3406ee5/R/stats-glm-tidiers.R#L70) for `augment` calls `rstandard` though so I'm not sure what could be causing this. 

``` r
library(broom)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(ISLR)

set.seed(42)
default <- Default %>% 
  sample_n(100)

fit <- glm(default ~ balance + income,
           data = default,
           family = binomial(link = "logit"))

pearson <- rstandard(fit, type = "pearson")
deviance <- rstandard(fit, type = "deviance")
broom_pearson <- augment(fit, type.residuals = "pearson") %>% 
  pull(.std.resid)

all.equal(pearson, broom_pearson, check.attributes = FALSE)
#> [1] "Mean relative difference: 0.4827163"
all.equal(deviance, broom_pearson, check.attributes = FALSE)
#> [1] TRUE
summary(pearson)
#>      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
#> -0.861222 -0.072384 -0.029730  0.031178 -0.006203  9.063461
summary(broom_pearson)
#>      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
#> -1.071136 -0.102235 -0.042035 -0.054334 -0.008773  3.001637
summary(deviance)
#>      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
#> -1.071136 -0.102235 -0.042035 -0.054334 -0.008773  3.001637
```

<sup>Created on 2018-11-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mattle24** [comment]
Hi @asbates, I'd love to try and help get to the bottom of this. I'm having some trouble reproducing the error though.  When I run the code I get that `broom_pearson = pearson`. Please let me know if you see any discrepancies in the code, I have no idea what could be causing the different outcomes.  

``` r
library(broom)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(ISLR)
#> Warning: package 'ISLR' was built under R version 3.5.1

set.seed(42)
default <- Default %>% 
  sample_n(100)

fit <- glm(default ~ balance + income,
           data = default,
           family = binomial(link = "logit"))

pearson <- rstandard(fit, type = "pearson")
deviance <- rstandard(fit, type = "deviance")
broom_pearson <- augment(fit, type.residuals = "pearson") %>% 
  pull(.std.resid)

all.equal(pearson, broom_pearson, check.attributes = FALSE)
#> [1] TRUE
all.equal(deviance, broom_pearson, check.attributes = FALSE)
#> [1] "Mean relative difference: 0.5437362"

summary(pearson)
#>      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
#> -0.861222 -0.072384 -0.029730  0.031178 -0.006203  9.063461
summary(broom_pearson)
#>      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
#> -0.861222 -0.072384 -0.029730  0.031178 -0.006203  9.063461
summary(deviance)
#>      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
#> -1.071136 -0.102235 -0.042035 -0.054334 -0.008773  3.001637
```

<sup>Created on 2019-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by asbates** [comment]
Hm. I just ran it again and I got the same result as I did before.

I did notice that in your example, you get  `Warning: package 'ISLR' was built under R version 3.5.1`. Could that have something to do with it? I'm using R 3.5.2.

**Comment by mattle24** [comment]
@asbates we're using ILSR for data, so I don't think that's the issue but good idea. I think you might have an older version of broom. Prior to August, broom treated `augment()` for `glm` the same as `augment()` for `lm()`. When I run the code like that (ie `augment.glm <- augment.lm()`), I get the same results as you. If you install the newest version of broom does that resolve the issue?

**Comment by asbates** [comment]
@mattle24 I was using broom 0.5.1. Just updated to the development version (0.5.1.9000) and I get the same result as you did above. Not sure why I was having issues with 0.5.1 since it was released in December. In any case, the issue seems to go away. Thanks for the help!

**Comment by mattle24** [comment]
No problem! Not sure why it wasn't before but happy it is now!

**Comment by simonpcouch** [comment]
Closing, as this seems like it's been addressed. :-)
