### ISSUE TITLE
Add Standard Error for `optim()`, if Hessian is available

### ISSUE THREAD

**Issue by billdenney** [tidymodels/broom#529]
It would be helpful if `tidy_optim()` supported summarizing the Hessian, if present.

``` r
library(broom)

tidy_optim <- function(x, ...) {
  if (is.null(names(x$par))) {
    names(x$par) <- paste0("parameter", seq_along(x$par))
  }
  ret <- tibble(parameter = names(x$par), value = unname(x$par))
  if ("hessian" %in% names(x)) {
    ret$std.error <- sqrt(diag(solve(x$hessian)))
  }
  ret
}

r <- function(x) (3 - x[1])^2 + 4 * (x[2] - x[1]^2)^2

res <- optim(1:2, r)
tidy_optim(res)
#> Error in tibble(parameter = names(x$par), value = unname(x$par)): could not find function "tibble"

resH <- optim(1:2, r, hessian=TRUE)
tidy_optim(resH)
#> Error in tibble(parameter = names(x$par), value = unname(x$par)): could not find function "tibble"
```

Created on 2018-11-16 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

(As mentioned in #505)

**Comment by bbolker** [comment]
the only tricky part here is that this assumes that the objective function is a negative log-likelihood function.  If someone provides, e.g., a sum-of-squares function, the "standard errors" (sqrt of diag of Hessian) will be bogus.  Don't know if this is mentioned in the docs ...

**Comment by billdenney** [comment]
@bbolker, good point.  Do you think that this should simply be a doc update, a warning, or something more?

**Comment by bbolker** [comment]
A warning seems like it could be onerous (unless there's an option to disable it, which adds further complexity). I think a strongly worded comment in the documentation would be sufficient ...

**Comment by simonpcouch** [comment]
Opted to add a note in the docs warning about supplying the correct objective function. Feel free to drop a note here if you think there should be more discussion and I can reopen.🙂
