### ISSUE TITLE
recipe version issues

### ISSUE THREAD

**Issue by topepo** [tidymodels/broom#531]
With the GH version of `rsample`, revdeps fail:

# broom

Version: 0.5.0

## Newly broken

*   checking re-building of vignette outputs ... WARNING
    ```
    ...
    
        intersect, setdiff, setequal, union
    
    Joining, by = "class"
    Joining, by = "class"
    Loading required package: tidyr
    
    Attaching package: 'rsample'
    
    The following object is masked from 'package:tidyr':
    
        fill
    
    The following object is masked from 'package:broom':
    
        tidy
    
    Quitting from lines 66-76 (bootstrapping.Rmd) 
    Error: processing vignette 'bootstrapping.Rmd' failed with diagnostics:
    Evaluation error: no applicable method for 'tidy' applied to an object of class "nls".
    Execution halted
    ```

Probably a bad interaction between `broom` and `generics`. Maybe load `broom` first?

**Comment by alexpghayes** [comment]
A patch to use update to `generics` is in progress on the `0.5.1` branch (https://github.com/tidymodels/broom/tree/0.5.1). If you build against that does the revdep issue go away?
