### ISSUE TITLE
Columns in tidy.ridgelm are inconsistent and do not pass strict tests

### ISSUE THREAD

**Issue by jmuhlenkamp** [tidymodels/broom#532]
Note, I intend to open a PR for this issue.

For `tidy.ridgelm`, the columns on the returned tibble are inconsistent depending on the original function call.

***Case 1: User DOES NOT specify an argument for lambda (i.e. single lambda is used)***

    library(broom)
    names(longley)[1] <- "y"
    fit1 <- MASS::lm.ridge(y ~ ., longley)
    colnames(tidy(fit1))
    ## [1] "lambda"   "term"     "estimate" "scale"    "xm" 

***Case 2: User DOES specify an argument for lambda with length > 1 (i.e. > 1 lambda is used)***

    fit2 <- MASS::lm.ridge(y ~ ., longley, lambda = seq(0.001, .05, .001))
    colnames(tidy(fit2))
    ## [1] "lambda"   "GCV"      "term"     "estimate" "scale" 

***Comparison***
- The column `xm` is included in Case 1, but not Case 2
- The column `GCV` is included in Case 2, but not Case 1

***Proposed Solution***
- `GCV` column will be added to Case 1 as this matches documentation and passes strict tests [#450 for related strict tests info](https://github.com/tidymodels/broom/issues/450).
- `xm` column will be removed from Case 1 because
  - `xm` prohibits passing of strict tests
  - `xm` column is not included in the documentation (`?tidy.ridgelm`)
  - `xm` is simply the column means of the training data (`?MASS:lm.ridge`) and thus does not reflect statistics specific to `lm.ridge` model fit.

**Comment by alexpghayes** [comment]
Nice digging! Apologies that I haven't responded to you over in #450 yet. Will try to take a look at the PR over Thanksgiving!
