### ISSUE TITLE
Autobuild pkgdown site

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#540]
See this commit https://github.com/tidymodels/textrecipes/commit/5cb8b3eb528b8e1326dd305937ab00d5d584516b

And https://github.com/r-lib/pkgdown/blob/master/R/deploy-site.R

**Comment by IndrajeetPatil** [comment]
This was resolved with https://github.com/tidymodels/broom/pull/651, no?

**Comment by alexpghayes** [comment]
Duplicate: #693

**Comment by alexpghayes** [comment]
@IndrajeetPatil Not quite. The travis infrastructure wasn't letting me set up private keys then. Hopefully my updates today have things working. We'll find out.

**Comment by alexpghayes** [comment]
Finally got this going!
