### ISSUE TITLE
Cannot install broom 

### ISSUE THREAD

**Issue by oij11** [tidymodels/broom#548]
---

I cannot install the package. 

```r
devtools::install_github("rstudio/broom", dependencies = TRUE)
```
 then I get an error as below:
Error: HTTP error 404.
  Not Found

  Rate limit remaining: 33/60
  Rate limit reset at: 2018-12-06 03:25:05 UTC

When I try  

```r
devtools::install_github("rstudio/broom", dependencies = TRUE)
```
the error is : Error: (converted from warning) unable to access index for repository https://cran.stat.ucla.edu/src/contrib:
  cannot open URL 'https://cran.stat.ucla.edu/src/contrib/PACKAGES'

Is this a glitch in cran? If then, how can I resolve this?

**Comment by alexpghayes** [comment]
Try `devtools::install_github("tidymodels/broom")`

**Comment by alexpghayes** [comment]
Try `install.packages("generics")` and then give it another go

**Comment by oij11** [comment]
Ok. I did and generics were installed after a few warnings (as below): 
Warning in install.packages :
  unable to access index for repository https://cran.stat.ucla.edu/src/contrib:
  cannot open URL 'https://cran.stat.ucla.edu/src/contrib/PACKAGES'
Warning in install.packages :
  unable to access index for repository https://cran.stat.ucla.edu/src/contrib:
  cannot open URL 'https://cran.stat.ucla.edu/src/contrib/PACKAGES'
Warning in install.packages :
  unable to access index for repository https://cran.stat.ucla.edu/bin/macosx/el-capitan/contrib/3.5:
  cannot open URL 'https://cran.stat.ucla.edu/bin/macosx/el-capitan/contrib/3.5/PACKAGES'
trying URL 'https://cran.cnr.berkeley.edu/bin/macosx/el-capitan/contrib/3.5/generics_0.0.2.tgz'
Content type 'application/x-gzip' length 61952 bytes (60 KB)
==================================================
downloaded 60 KB


The downloaded binary packages are in
	/var/folders/66/6996mtrd05g23kw64c08r91w0000gn/T//RtmpjfWNYk/downloaded_packages


Then I gave it another try for broom but still got the same error. It asked me if I'd want to update generics and then the error... would you have any solution? Thanks in advance for your help.

**Comment by alexpghayes** [comment]
I recommend [making a reprex](https://www.tidyverse.org/help/) and asking on community.rstudio.com!

**Comment by oij11** [comment]
Ok.  I will ask on the community, but I'd also like to share reprex here in case if you can help after seeing it.. 


devtools::install_github("tidymodels/broom")
#> Downloading GitHub repo tidymodels/broom@master
#> generics (0.0.2 -> d59e6b456...) [GitHub]
#> Downloading GitHub repo r-lib/generics@master
#>   
   checking for file ‘/private/var/folders/66/6996mtrd05g23kw64c08r91w0000gn/T/Rtmp9Xwb9A/remotes117c0272262fb/r-lib-generics-d59e6b4/DESCRIPTION’ ...
  
✔  checking for file ‘/private/var/folders/66/6996mtrd05g23kw64c08r91w0000gn/T/Rtmp9Xwb9A/remotes117c0272262fb/r-lib-generics-d59e6b4/DESCRIPTION’
#> 
  
─  preparing ‘generics’:
#> 
  
   checking DESCRIPTION meta-information ...
  
✔  checking DESCRIPTION meta-information
#> 
  
─  installing the package to process help pages
#> 
  
─  checking for LF line-endings in source and make files and shell scripts (939ms)
#> 
  
─  checking for empty or unneeded directories
#> 
  
─  building ‘generics_0.0.2.tar.gz’
#> 
  
   
#> 
  
   checking for file ‘/private/var/folders/66/6996mtrd05g23kw64c08r91w0000gn/T/Rtmp9Xwb9A/remotes117c04aa4ef8/tidymodels-broom-c5d85b4/DESCRIPTION’ ...
  
✔  checking for file ‘/private/var/folders/66/6996mtrd05g23kw64c08r91w0000gn/T/Rtmp9Xwb9A/remotes117c04aa4ef8/tidymodels-broom-c5d85b4/DESCRIPTION’
#> 
  
─  preparing ‘broom’: (667ms)
#> 
  
   checking DESCRIPTION meta-information ...
  
✔  checking DESCRIPTION meta-information
#> 
  
─  checking for LF line-endings in source and make files and shell scripts (541ms)
#> 
  
─  checking for empty or unneeded directories
#> 
  
─  looking to see if a ‘data/datalist’ file should be added
#> 
  
─  building ‘broom_0.5.1.9000.tar.gz’
#> 
  
   
#>

**Comment by alexpghayes** [comment]
Closing this for now, let me know if you're still having trouble!
