### ISSUE TITLE
Broom updata error and thus cannot install another package dependent on broom

### ISSUE THREAD

**Issue by oij11** [tidymodels/broom#554]
---

Hi, when I try to install another package papaja, it requires updating broom. However, broom update creates error. The error message is as below. I've also attached reflex. 

In addition, I've tried the solutions suggested here but this does not help me either. https://github.com/tidyverts/fable/issues/72

* installing *source* package ‘broom’ ...
** R
** byte-compile and prepare package for lazy loading
Error in unloadNamespace(pkg_name) : 
  namespace ‘broom’ is imported by ‘tidyverse’, ‘modelr’ so cannot be unloaded
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/broom’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/broom’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/66/6996mtrd05g23kw64c08r91w0000gn/T//RtmpbQhOy3/filea93c54074d06/broom_0.5.1.9000.tar.gz’ had non-zero exit status
```r
``` r
(devtools::install_github("crsh/papaja", force = TRUE))
#> Downloading GitHub repo crsh/papaja@master
#> broom (c5d85b45b... -> 9a85f7584...) [GitHub]
#> Downloading GitHub repo tidymodels/broom@master
#> 
#>   
   checking for file ‘/private/var/folders/66/6996mtrd05g23kw64c08r91w0000gn/T/RtmplD4Pqq/remotesaae348928a6b/tidymodels-broom-9a85f75/DESCRIPTION’ ...
  
✔  checking for file ‘/private/var/folders/66/6996mtrd05g23kw64c08r91w0000gn/T/RtmplD4Pqq/remotesaae348928a6b/tidymodels-broom-9a85f75/DESCRIPTION’
#> 
  
─  preparing ‘broom’: (495ms)
#> 
  
   checking DESCRIPTION meta-information ...
  
✔  checking DESCRIPTION meta-information
#> 
  
─  checking for LF line-endings in source and make files and shell scripts (540ms)
#> 
  
─  checking for empty or unneeded directories
#> 
  
─  looking to see if a ‘data/datalist’ file should be added
#> 
  
─  building ‘broom_0.5.1.9000.tar.gz’
#> 
  
   
#> 
  
   checking for file ‘/private/var/folders/66/6996mtrd05g23kw64c08r91w0000gn/T/RtmplD4Pqq/remotesaae3563c28a3/crsh-papaja-2e11aec/DESCRIPTION’ ...
  
✔  checking for file ‘/private/var/folders/66/6996mtrd05g23kw64c08r91w0000gn/T/RtmplD4Pqq/remotesaae3563c28a3/crsh-papaja-2e11aec/DESCRIPTION’
#> 
  
─  preparing ‘papaja’:
#> 
  
   checking DESCRIPTION meta-information ...
  
✔  checking DESCRIPTION meta-information
#> 
  
─  checking for LF line-endings in source and make files and shell scripts
#> 
  
─  checking for empty or unneeded directories
#> 
  
─  building ‘papaja_0.1.0.9842.tar.gz’
#> 
  
   
#> 
#> [1] "papaja"
```

<sup>Created on 2018-12-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>```

**Comment by alexpghayes** [comment]
Can you try restarting R and updating to the development version of `remotes`?

**Comment by alexpghayes** [comment]
Any updates?

**Comment by oij11** [comment]
I tried restarting and updating to the development version but still got errors. I could not figure out what caused the problem but I could install the package after I uninstalled deleted all R history files and reinstalled R.
