### ISSUE TITLE
Feature Request:  `glance` on a list of models?

### ISSUE THREAD

**Issue by billdenney** [tidymodels/broom#561]
I often want to compare many models-- usually collected in a list-- to each other.  I've currently implemented this in my `PKNCA` package with the non-exported `AIC.list()` function, but as I think of it more, `broom` (and `broom.mixed`) seem like a better home for the type of functionality I'm thinking of.

While I can accomplish the same thing with a call like the following (typed directly into GitHub; it may have bugs, but it hopefully indicates the intent):

```r
model_list %>%
  lapply(FUN=glance) %>%
  bind_rows()
```

For me, the multiple-model comparison need is common and I'd like to have an interface like:

```r
glance_list <- function(x, ...) {
  ret_list <- lapply(X=x, FUN=glance, ...)
  bind_rows(ret_list)
}
```

To make this work with models that don't converge, I'd also ideally like to have `glance()` methods for logical NA and NULL:

```r
glance.logical <- function(x, ...) {
  if (length(x) == 1 && is.na(x)) {
    # Choose appropriate "model summaries" for NA, possibly an empty data.frame, perhaps:
    data.frame(convergence=FALSE)
  } else {
    stop("Cannot glance at a logical value other than scalar NA.")
  }
}
```

```r
glance.NULL <- function(x, ...) {
  # Choose appropriate "model summaries" for NULL, matching NA
  glance.logical(NA, ...)
}
```

This relates to: billdenney/PKNCA#71 and billdenney/PKNCA#90

**Comment by billdenney** [comment]
@alexpghayes, That works well enough.

**Comment by alexpghayes** [comment]
Just realized that `glance()` currently returns an empty tibble for `NULL` values, but there isn't a `glance()` method for `NA` values, for models that aren't converging. Are there any model types / packages you work with that return `NA` for models that failed to converge?
