### ISSUE TITLE
Feature requests for tidy.coxph()

### ISSUE THREAD

**Issue by sjackson1236** [tidymodels/broom#566]
Hi, I've never posted one of these before so if I do something stupid (likely) just let me know. 

1) Is there a way to have an option that automatically concatenates the ci.low and ci.high into "(ci.low,ci.high)?" 

2) Is there a way to automatically not output certain columns? Like for myself, I never use "se" and "statistic" so I exclude them (typically these are the third and fourth columns). 

3) Is there a way to have an option to specify the number of digits?

4) Is there a way to modify this function to handle frailty terms? Otherwise I have to cut out the last row of the output first as tidy won't accept it. 

And one question:

In what situation is robust.se generated? I'm doing three models with time-dependent covariates, and in the one with multiple events it generates this additional column. 

Thanks,

Scott

**Comment by alexpghayes** [comment]
The [`dplyr`](https://dplyr.tidyverse.org/) package will do a lot of this for you, and is my recommended approach. In general, `broom` doesn't do this directly, but you can quickly manipulate the output of `tidy()` into your desired form.

> Is there a way to have an option that automatically concatenates the ci.low and ci.high into "(ci.low,ci.high)?"

Yes. Here's an example using the `dplyr` and `purrr` packages:

``` r
library(survival)
library(broom)
#> Warning: package 'broom' was built under R version 3.5.1
library(dplyr)
#> Warning: package 'dplyr' was built under R version 3.5.1
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

fit <- coxph(Surv(time, status) ~ age + sex, lung)
td <- tidy(fit)

td %>% 
  mutate(ci = purrr::map2(conf.low, conf.high, c))
#> # A tibble: 2 x 8
#>   term  estimate std.error statistic p.value conf.low conf.high ci       
#>   <chr>    <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl> <list>   
#> 1 age     0.0170   0.00922      1.85 0.0646  -0.00103    0.0351 <dbl [2]>
#> 2 sex    -0.513    0.167       -3.06 0.00218 -0.841     -0.185  <dbl [2]>
```

> Is there a way to automatically not output certain columns?

No, but you can strip them out with a single line:

```r
td %>% 
  select(-std.error, -statistic)
#> # A tibble: 2 x 5
#>   term  estimate p.value conf.low conf.high
#>   <chr>    <dbl>   <dbl>    <dbl>     <dbl>
#> 1 age     0.0170 0.0646  -0.00103    0.0351
#> 2 sex    -0.513  0.00218 -0.841     -0.185
```

> Is there a way to have an option to specify the number of digits?

Again, no, but `dplyr` will let you do this with a single line.

``` r
td %>% 
  mutate_if(is.numeric, round, 3)
#> # A tibble: 2 x 7
#>   term  estimate std.error statistic p.value conf.low conf.high
#>   <chr>    <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>
#> 1 age      0.017     0.009      1.85   0.065   -0.001     0.035
#> 2 sex     -0.513     0.167     -3.06   0.002   -0.841    -0.185
```

<sup>Created on 2018-12-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

> Is there a way to modify this function to handle frailty terms? Otherwise I have to cut out the last row of the output first as tidy won't accept it.

I don't know what a frailty term is. Can you provide a [`reprex`](https://www.tidyverse.org/help/) showing where `tidy()` errors and then I'll implement that?

> In what situation is robust.se generated? I'm doing three models with time-dependent covariates, and in the one with multiple events it generates this additional column.

I'm not entirely sure. Let me look into this and get back to you.

**Comment by sjackson1236** [comment]
thanks. Is there a way to do all those mutates in one statement? I rarely use dplyr.

For the last part, the frailty() option let's you fit random effects. If you modify the code above like this:

`` fit<- coxph(Surv(time, status) ~ age + sex + frailty(inst), lung)
``

and look at the output you will see this term. I does not have a coefficient, just a test.

**Comment by alexpghayes** [comment]
Yep you can chain them together with

``` r
td <- tidy(fit)

td %>% 
  mutate(ci = purrr::map2(conf.low, conf.high, c)) %>%
  select(-std.error, -statistic) %>%
  mutate_if(is.numeric, round, 3)
```

Will add support for frailty terms at some point here.

**Comment by riinuots** [comment]
I'll try this one
