### ISSUE TITLE
warnings for `ergm` tidiers

### ISSUE THREAD

**Issue by IndrajeetPatil** [tidymodels/broom#567]
The warnings are pretty much self-explanatory, so I won't add anything more to that.
``` r

# load the Florentine marriage network data
set.seed(123)
suppressPackageStartupMessages(library(ergm))
data(florentine)

# fit a model where the propensity to form ties between
# families depends on the absolute difference in wealth
gest <- ergm(flomarriage ~ edges + absdiff("wealth"))
#> Starting maximum pseudolikelihood estimation (MPLE):
#> Evaluating the predictor and response matrix.
#> Maximizing the pseudolikelihood.
#> Finished MPLE.
#> Stopping at the initial estimate.
#> Evaluating log-likelihood at the estimate.
class(gest)
#> [1] "ergm"

# show terms, coefficient estimates and errors
broom::tidy(gest, conf.int = TRUE)
#> Warning: You appear to be calling summary.ergm() directly. summary.ergm()
#> is a method, and will not be exported in a future version of 'ergm'. Use
#> summary() instead, or getS3method() if absolutely necessary.
#> # A tibble: 2 x 7
#>   term          estimate std.error mcmc.error    p.value conf.low conf.high
#>   <chr>            <dbl>     <dbl>      <dbl>      <dbl>    <dbl>     <dbl>
#> 1 edges          -2.30     0.402            0    1.02e-8 -3.09      -1.51  
#> 2 absdiff.weal~   0.0155   0.00616          0    1.17e-2  0.00345    0.0276

# show diagnostics
broom::glance(gest)
#> Warning: You appear to be calling logLik.ergm() directly. logLik.ergm()
#> is a method, and will not be exported in a future version of 'ergm'. Use
#> logLik() instead, or getS3method() if absolutely necessary.
#> # A tibble: 1 x 5
#>   independence iterations logLik   AIC   BIC
#>   <lgl>             <int>  <dbl> <dbl> <dbl>
#> 1 TRUE                  4  -51.0  106.  112.
```

<sup>Created on 2019-01-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                                             
#>  version  R Under development (unstable) (2018-11-30 r75724)
#>  os       Windows 10 x64                                    
#>  system   x86_64, mingw32                                   
#>  ui       RTerm                                             
#>  language (EN)                                              
#>  collate  English_United States.1252                        
#>  ctype    English_United States.1252                        
#>  tz       Asia/Calcutta                                     
#>  date     2019-01-03                                        
#> 
#> - Packages --------------------------------------------------------------
#>  package        * version     date       lib
#>  assertthat       0.2.0       2017-04-11 [1]
#>  backports        1.1.3       2018-12-14 [1]
#>  bindr            0.1.1       2018-03-13 [1]
#>  bindrcpp         0.2.2       2018-03-29 [1]
#>  broom            0.5.1.9000  2018-12-24 [1]
#>  callr            3.1.1       2018-12-21 [1]
#>  cli              1.0.1.9000  2018-10-30 [1]
#>  coda             0.19-2      2018-10-08 [1]
#>  crayon           1.3.4       2017-09-16 [1]
#>  DEoptimR         1.0-8       2016-11-19 [1]
#>  desc             1.2.0       2018-10-30 [1]
#>  devtools         2.0.1       2018-10-26 [1]
#>  digest           0.6.18      2018-10-10 [1]
#>  dplyr            0.7.8       2018-11-10 [1]
#>  ergm           * 3.9.4       2018-08-16 [1]
#>  evaluate         0.12        2018-10-09 [1]
#>  fansi            0.4.0       2018-11-05 [1]
#>  fs               1.2.6       2018-08-23 [1]
#>  generics         0.0.2       2018-11-29 [1]
#>  glue             1.3.0       2018-07-17 [1]
#>  highr            0.7         2018-06-09 [1]
#>  htmltools        0.3.6       2017-04-28 [1]
#>  knitr            1.21        2018-12-10 [1]
#>  lattice          0.20-38     2018-11-04 [2]
#>  lpSolve          5.6.13      2015-09-19 [1]
#>  magrittr         1.5         2014-11-22 [1]
#>  MASS             7.3-51.1    2018-11-01 [2]
#>  Matrix           1.2-15      2018-11-01 [1]
#>  memoise          1.1.0       2017-04-21 [1]
#>  network        * 1.13.0.1    2018-04-02 [1]
#>  pillar           1.3.1       2018-12-15 [1]
#>  pkgbuild         1.0.2       2018-10-16 [1]
#>  pkgconfig        2.0.2       2018-08-16 [1]
#>  pkgload          1.0.2       2018-10-29 [1]
#>  prettyunits      1.0.2       2015-07-13 [1]
#>  processx         3.2.1       2018-12-05 [1]
#>  ps               1.3.0       2018-12-21 [1]
#>  purrr            0.2.5.9000  2018-11-28 [1]
#>  R6               2.3.0       2018-10-04 [1]
#>  Rcpp             1.0.0       2018-11-07 [1]
#>  remotes          2.0.2       2018-10-30 [1]
#>  rlang            0.3.0.1     2018-10-25 [1]
#>  rmarkdown        1.11        2018-12-08 [1]
#>  robustbase       0.93-3      2018-09-21 [1]
#>  rprojroot        1.3-2       2018-01-03 [1]
#>  sessioninfo      1.1.1       2018-11-05 [1]
#>  statnet.common   4.1.4       2018-06-22 [1]
#>  stringi          1.2.4       2018-07-20 [1]
#>  stringr          1.3.1       2018-05-10 [1]
#>  testthat         2.0.1       2018-10-13 [1]
#>  tibble           1.4.99.9006 2018-12-21 [1]
#>  tidyr            0.8.2       2018-10-28 [1]
#>  tidyselect       0.2.5       2018-10-11 [1]
#>  trust            0.1-7       2015-07-04 [1]
#>  usethis          1.4.0.9000  2018-12-12 [1]
#>  utf8             1.1.4       2018-05-24 [1]
#>  withr            2.1.2       2018-03-15 [1]
#>  xfun             0.4         2018-10-23 [1]
#>  yaml             2.2.0       2018-07-25 [1]
#>  source                           
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.6.0)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.1)                   
#>  Github (tidymodels/broom@a1ac666)
#>  CRAN (R 3.6.0)                   
#>  Github (r-lib/cli@56538e3)       
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.0)                   
#>  Github (r-lib/desc@7c12d36)      
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.2)                   
#>  CRAN (R 3.5.1)                   
#>  Github (brodieG/fansi@ab11e9c)   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.6.0)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.6.0)                   
#>  CRAN (R 3.6.0)                   
#>  CRAN (R 3.5.0)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.6.0)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.6.0)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.6.0)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.6.0)                   
#>  CRAN (R 3.6.0)                   
#>  Github (tidyverse/purrr@b4ae036) 
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.6.0)                   
#>  CRAN (R 3.6.0)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.6.0)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.6.0)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.6.0)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.1)                   
#>  Github (tidyverse/tibble@f1eacb5)
#>  CRAN (R 3.6.0)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.2)                   
#>  Github (r-lib/usethis@923dd75)   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.5.1)                   
#>  CRAN (R 3.6.0)                   
#>  CRAN (R 3.5.1)                   
#> 
#> [1] C:/Users/inp099/Documents/R/win-library/3.6
#> [2] C:/Program Files/R/R-devel/library
```

</details>

**Comment by briatte** [comment]
Fixing this should be straightforward -- I'll try doing it soon-ish.

**Comment by briatte** [comment]
Just submitted a simple fix where I use `ergm:::summary` and `ergm:::logLik` to avoid the no-export warning.

Note that a problem will subsist with `ergm::get.miss.dyads` (used in the `glance` method), which is deprecated. The fix is less obvious.

Here's what the deprecated function currently looks like:

```r
> ergm::get.miss.dyads
function (constraints, constraints.obs) 
{
    .dep_once("as.rlebdm() ergm_conlist method")
    NVL3(as.rlebdm(constraints, constraints.obs = constraints.obs, 
        which = "missing"), as.network(as.edgelist(.), matrix.type = "edgelist", 
        directed = TRUE), network.initialize(2))
}
<bytecode: 0x10e9f2ab0>
<environment: namespace:ergm>
```

The corresponding code in `ergm-tidiers.R` reads as follows:

https://github.com/tidymodels/broom/blob/66411c4d2081456e82ea30a77c54edf90da1ecec/R/ergm-tidiers.R#L112-L116

This should be solvable by calling the right `statnet.common` functions, but since there are differences between what the code in `ergm-tidiers.R` is (`network.initialize(1)`) and what the solution to the deprecation in `ergm` is (`NVL3`, `network.initialize(2)`), I'll submit this to your general review before going further.

**Comment by alexpghayes** [comment]
@briatte Pretty sure I reorganized files, which results in some loss of the git history IIRC. A git wizard may know how to discover the original author but I do not.

> This part should probably be rewritten using ergm::as.rlebdm and statnet.common::NVL3, but since there are differences between what the code in ergm-tidiers.R is (network.initialize(1)) and what the solution to the deprecation in ergm is (NVL3, network.initialize(2)), I'll submit this to general review before going further.

I don't know enough about this to have an informed opinion. I trust your judgement, and let's just be sure to document any changes from previous behavior very carefully.

**Comment by briatte** [comment]
I'll be careful. In the meantime, the fix submitted above works fine :)

**Comment by alexpghayes** [comment]
@briatte `ergm 3.10` is headed to CRAN in a day or two, which makes the replacement for `get.miss.dyads()` somewhat more urgent. Would be willing to write a replacement?

Currently working this and some other small patches in the `0.5.2` branch.

**Comment by briatte** [comment]
@alexpghayes Hi ~ 

Will try to work on a replacement tonight (no guarantee, though).

Aren't some of the changes in the `0.5.2` branch going to collide with #611?

**Comment by krivit** [comment]
Thanks for looking into this. A few notes:
* `NVL3()` is dot-substitutes the first argument into the second if the first argument is not `NULL`, so it's probably overkill here.
* If you want to just get the dyads that contain information, which are those that are 1) not structurally constrained and 2) are not missing, just use something along the lines of `as.rlebdm(ergm$constrained, ergm$constrained.obs, which="informative")`.

Looking at this code pattern, I think that I'll implement an `as.rlebdm()` method for `ergm` objects, which automate that, and add an option not to return placeholders like `NULL`.

**Comment by krivit** [comment]
`ergm` 3.10 will have
* an `as.rlebdm()` method for `ergm` objects.
* an `nobs()` method for `ergm` objects.

Then `nobs(ergm.fit)` will return the number of non-missing non-constrained dyads in the model that was fit. It should be exactly what you are looking for.

In general, my goal is to encapsulate the `ergm` objects as much as possible to obviate the need to access nontrivial elements directly.

**Comment by briatte** [comment]
Dear @krivit – Thank you very much for your reply!

1. I think what you are suggesting is to have just this in the code calling `statnet.common::NVL3`:

```r
statnet.common::NVL3(
    as.rlebdm(x$constrained, x$constrained.obs, which = "missing"),
    null = network.initialize(2)
)
```

… hence skipping the second argument. I prefer to check that again with you, as I am hazy about how those functions are really supposed to behave.

Similarly, I still feel strange about having two successive `NVL*` calls in my code, not being sure about what it really achieves:

https://github.com/briatte/broom/blob/11097068d65bd6058e086e90d1661d4419956a87/R/ergm-tidiers.R#L115-L120

2. I'm interested in replacing some of the code with the `as.rlebdm(which = "informative")` call that you mention, but may I ask, how would that work here? What does that substitute for in the [current function](https://github.com/briatte/broom/blob/11097068d65bd6058e086e90d1661d4419956a87/R/ergm-tidiers.R#L112-L130)?

3. Last thing, I keep getting a deprecation warning when running those two lines:

```r
ret$AIC <- tryCatch(stats::AIC(x), error = function(e) NULL)
ret$BIC <- tryCatch(stats::BIC(x), error = function(e) NULL)
```

Please let me know if you know a way to avoid it.

Thanks a lot for your help!

**Comment by krivit** [comment]
> 1. I think what you are suggesting is to have just this in the code calling `statnet.common::NVL3`:
> 
> 
> ```r
> statnet.common::NVL3(
>     as.rlebdm(x$constrained, x$constrained.obs, which = "missing"),
>     null = network.initialize(2)
> )
> ```
> 
> … hence skipping the second argument. I prefer to check that again with you, as I am hazy about how those functions are really supposed to behave.
> 
> Similarly, I still feel strange about having two successive `NVL*` calls in my code, not being sure about what it really achieves:
> 
> https://github.com/briatte/broom/blob/11097068d65bd6058e086e90d1661d4419956a87/R/ergm-tidiers.R#L115-L120

I am not sure what that particular code is accomplishing. It looks like you are trying to count the number of non-missing dyads, and it seems like a pretty convoluted way to do so. (Granted, some code in `ergm` is pretty convoluted as well.)

> 1. I'm interested in replacing some of the code with the `as.rlebdm(which = "informative")` call that you mention, but may I ask, how would that work here? What does that substitute for in the [current function](https://github.com/briatte/broom/blob/11097068d65bd6058e086e90d1661d4419956a87/R/ergm-tidiers.R#L112-L130)?

It replaces the whole calculation of `dyads`: https://github.com/briatte/broom/blob/11097068d65bd6058e086e90d1661d4419956a87/R/ergm-tidiers.R#L115-L122 .

Pre 3.10:
```r
dyads <- sum(as.rlebdm(x$constrained, x$constrained.obs, which = "informative"))
```
3.10+:
```r
dyads <- nobs(x)
```

> 
> 2. Last thing, I keep getting a deprecation warning when running those two lines:
> 
> 
> ```r
> ret$AIC <- tryCatch(stats::AIC(x), error = function(e) NULL)
> ret$BIC <- tryCatch(stats::BIC(x), error = function(e) NULL)
> ```
> 
> Please let me know if you know a way to avoid it.

What is the specific version of `ergm`, and can you give me a minimal example?

**Comment by briatte** [comment]
@krivit Thank you very much for your reply.

1. I have fixed the code as suggested, anticipating on `ergm` 3.10:

https://github.com/briatte/broom/blob/38d00e02847c112c0c134053081e009d8e2c1b0f/R/ergm-tidiers.R#L113-L119

2. I am using `ergm` 3.9.4, the latest one on CRAN. Here's a MWE.

```r
library(ergm)
data(florentine)
gest <- ergm(flomarriage ~ edges + absdiff("wealth"))
stats::AIC(gest) # same if BIC is used
```

**Comment by krivit** [comment]
@briatte , thanks. For item 2, looks like a false positive in the don't-call-methods-directly-unless-you-have-to warning, and I am not sure why it's triggering on `ll()`. In any case, it's gone in the 3.10 branch.
