### ISSUE TITLE
Brainstorm: Tidying GAMMs

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#596]
Hey @Athanasiamo, following up from our rstudio::conf conversation. You mentioned that it would be great for `broom` to tidy GAMMs, and also a broader variety of objects produced by the `mgcv` package. I don't use GAMs and GAMMs enough to know what to extract from these objects, so it would be super useful to have a brainstorm here about what to extract for these models, and then base the implementation on that.

Tagging in @gavinsimpson as well. If anybody else has common GAM(M) workflows they would like to see supported, please chime in!

Some questions to get started:

- What classes should we tidy?
- What should `tidy` and `glance` return for GAMs? For GAMMs?
- Is there additional info beyond predictions and residuals that we be useful in `augment()`?

Also it may be worthwhile documenting the structure of `gamm` objects to some degree since the mixture of `lmer` and `gam` components requires some explanation.

**Comment by alexpghayes** [comment]
For reference, the current implementation does the following:

``` r
library(broom)
#> Warning: package 'broom' was built under R version 3.5.1
g <- mgcv::gam(mpg ~ s(hp) + am + qsec, data = mtcars)

tidy(g)
#> # A tibble: 1 x 5
#>   term    edf ref.df statistic p.value
#>   <chr> <dbl>  <dbl>     <dbl>   <dbl>
#> 1 s(hp)  2.36   3.02      6.34 0.00207

tidy(g, parametric = TRUE)
#> # A tibble: 3 x 5
#>   term        estimate std.error statistic p.value
#>   <chr>          <dbl>     <dbl>     <dbl>   <dbl>
#> 1 (Intercept)  16.7        9.83      1.70  0.101  
#> 2 am            4.37       1.56      2.81  0.00918
#> 3 qsec          0.0904     0.525     0.172 0.865

glance(g)
#> # A tibble: 1 x 6
#>      df logLik   AIC   BIC deviance df.residual
#>   <dbl>  <dbl> <dbl> <dbl>    <dbl>       <dbl>
#> 1  5.36  -74.4  162.  171.     196.        26.6
```

<sup>Created on 2019-01-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by Athanasiamo** [comment]
Hi @alexpghayes ! 

Thanks for picking this up! 

I think the tidiers for the `gam` seem ok, I think that is what most people would expect from it. I had not caught the `parametric = TRUE` option, which seems like a nice touch!

**Comment by Athanasiamo** [comment]
Here's a small bit with a random effect using `gamm` notice that firstly we need to go into the model object and specifically get the gam object from a list, then there is a decent tidier, but neither glance nor augment are working. I added a bit of code I use as a glance-type tidier for gamm

``` r

  library(broom)
  library(mgcv)
#> Loading required package: nlme
#> This is mgcv 1.8-26. For overview type 'help("mgcv-package")'.
  library(tidyverse)
  
  #> Warning: package 'broom' was built under R version 3.5.1
  g <- mgcv::gamm(mpg ~ s(hp) + am + qsec, random = list(am=~1), data = mtcars)
  
  tidy(g$gam)
#> # A tibble: 1 x 5
#>   term    edf ref.df statistic p.value
#>   <chr> <dbl>  <dbl>     <dbl>   <dbl>
#> 1 s(hp)  1.85   1.85      9.82 0.00106

  tidy(g$gam, parametric = TRUE)
#> # A tibble: 3 x 5
#>   term        estimate std.error statistic p.value
#>   <chr>          <dbl>     <dbl>     <dbl>   <dbl>
#> 1 (Intercept)   14.8       9.62      1.53  0.137  
#> 2 am             4.81      1.48      3.24  0.00316
#> 3 qsec           0.190     0.515     0.368 0.716

  glance(g$gam)
#> Error in `$<-.data.frame`(`*tmp*`, "logLik", value = numeric(0)): replacement has 0 rows, data has 1
  augment(g$gam)
#> Error: No augment method for objects of class gam
  
  # My glance type tidier for gamms
  g$gam %>% 
    summary() %>% 
    .$s.table %>% 
    as.data.frame() %>% 
    rownames_to_column(var = "Predictor")
#>   Predictor      edf   Ref.df        F     p-value
#> 1     s(hp) 1.849828 1.849828 9.815398 0.001063516
```

<sup>Created on 2019-01-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by Athanasiamo** [comment]
sigh, I need to not reply to stuff after a certain hour, my brain does not function well right before I sleep. My tidier above is the same tidier you posted!

**Comment by alexpghayes** [comment]
I'm not totally clear on which terms in a GAM(M) are best thought of as random effects, and how to report them. Currently `s(..., bs = "re")` just gets reported with the other parametric effects, but I'm not sure this is best way to do it? What about random smooths and so on?

**Comment by Athanasiamo** [comment]
I think most people are not clear on what terms GAM(M)s are best thought of as random effects. I my opinion, they are best placed with the parametrics. I always take them out of my tables when I make them, as I mainly look at randoms to check things look fine, the effects of it is not in it self of interest. I believe we can assume that any effect supplied through `random` or a spline with `bs = "re"` is a specification of a random effect. There might be more complex types, but I have not tried any other than these two options, really. In my own field, I can't really think of a use case for a random smooth, so I've never looked into that option.

**Comment by osorensen** [comment]
Thanks to all of you for working on this!

@alexpghayes, regarding you question about random smooths. To the best of my understand, such smooths are not possible to set up in `mgcv`. The only way to compute smooth random effects is by computing new columns from some smooth basis, and then defining them as parametric effects.

``` r
library(mgcv)
#> Loading required package: nlme
#> This is mgcv 1.8-27. For overview type 'help("mgcv-package")'.
set.seed(23)
dat <- gamSim(6,n=200,scale=.05,dist="poisson")
#> 4 term additive + random effectGu & Wahba 4 term additive model
# Random intercept, works
b2 <- gamm(y~s(x0)+s(x1)+s(x2),family=poisson,
           data=dat,random=list(fac=~1))
#> 
#>  Maximum number of PQL iterations:  20
#> iteration 1
#> iteration 2
#> iteration 3
# Random squared slope, works
b2 <- gamm(y~s(x0)+s(x1)+s(x2),family=poisson,
           data=dat,random=list(fac=~1 + x2^2))
#> 
#>  Maximum number of PQL iterations:  20
#> iteration 1
#> iteration 2
#> iteration 3

# Random smooth, fails
b2 <- gamm(y~s(x0)+s(x1)+s(x2),family=poisson,
           data=dat,random=list(fac=~1 + s(x2)))
#> 
#>  Maximum number of PQL iterations:  20
#> iteration 1
#> Error in model.frame.default(form, data): invalid type (list) for variable 's(x2)'
```

<sup>Created on 2019-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Random effects specified with `s(..., bs = "re")` are random intercepts, and no other type of random effects are possible with these functions given that the inputs are factors. Hence, random effects beyond random intercepts have to be specified using the `random = list(...)` argument, which is passed on to `nlme::lme`.

**Comment by adibender** [comment]
@osorensen Not sure this is true, the specification is different though: See Model 4, page 21/22 here: https://peerj.com/preprints/27320/

**Comment by osorensen** [comment]
Thanks, @adibender !

**Comment by gavinsimpson** [comment]
The `s(..., bs = 're')` can incorporate _uncorrelated_ random effects in the same sense as **lme4**, so random intercept and slopes, just not correlated ones. More complex "random effects" can be generated using the `'fs'` basis or a tensor product of one of the other bases with a `'re'` basis. Some of the discussion in the revised version (see [here](https://github.com/eric-pedersen/mixed-effect-gams/raw/master/compiled_paper/full_document.pdf)) of the paper @adibender linked to (inc one of the footnotes in the new version) talks about what we mean with these random smooths, which is somewhat different to the classical interpretation of random effects (hence the scare quotes).

For a GAM-like GAMM (`gam()`, bam()`), anything in an `s()`, `te()`, `t2()`, or `ti()` should reasonably be reported as a smooth term &mdash; the `s(..., bs = 're')` really *are* smooths just with not very interesting basis functions. They have EDFs, they're subject to shrinkage / the penalty, and the tests from `summary.gam()` are specifically tailored to tests for random effects (testing on the boundary etc). Also, if the `s(..., bs = 're')` aren't in the smooths, where do we put things like `t2(x, z, id, bs = c('tp','cc','re'), full = TRUE)`?

For a GAMM fitted via `gamm()` or `gamm4::gamm4()` with "proper" random effects sensu **nlme** or **lme4**, we should perhaps treat random effects as the tidiers for those mixed models treat them.

**Comment by Athanasiamo** [comment]
interesting @gavinsimpson ! This is really extending our understanding of what we can actually do with gamms (we seem to have been working with simple models, a lot of the time because we had no knowledge of how or whether more complex models fit better!). So this is educational in several ways!

What if there was an option to either omit or include (default) smooths that were set as 're'? This way we might have an easy way of tidying also the random smooths? Though, that might be a feature that @alexpghayes might not want to introduce into the method, as it would be very specific to GAMMs, In that case, smooths should stay in the non-parametric tidiers, no matter how they are tagged, and it would e up to the user to do another extra tidy after the tidier...

**Comment by gavinsimpson** [comment]
@Athanasiamo The problem with setting `'re'` smooths to be treated differently is that we'll get into all sorts of complications with smooths that for valid reasons are fit with `te()`, `t2()` etc. Plus, things that people might like to think of as random "effects", like `s(x, f, bs = 'fs')` will get treated differently.

I would strongly argue in favour of keeping anything estimated via `s()`, `te()`, `ti()`, `t2()` etc in it's spline-based representation, to avoid making things overly complex/confusion. Users can always `filter()` the tidied object to remove terms they are not interested in.

Something else to consider is an option to reduce the splines in a GAMM to variance components such that we can report all the smooths and random effects specified via `random` as if they were the variance components of a mixed model. This can be gleaned from `gam.vcomp()`, which I think works for  `gamm()` and `gamm4()`.
