### ISSUE TITLE
Feature request: Make glance.NULL return a single (empty) row?

### ISSUE THREAD

**Issue by billdenney** [tidymodels/broom#600]
This is directly related to #258 and tangentially related to #561.

To make the return of glance consistent across any input, could `glance(NULL)` return a single empty row tibble (1x0) instead of a 0x0 tibble?  The rationale is that it would make glance consistent (as described in #258, NULL is the only class where `glance()` returns something other than one row.

A benefit would be that when comparing models (as brought up in #561), it is helpful to have a "this did not work" row, and since there is a preference not to have `NA_glance_` or similar constant (as discussed in #565) which would map to a failed model, the next best, general solution I thought of is `NULL`, but since `NULL` returns zero rows, it disappears from summaries when running something like the following:

```r
# make a list of many models with descriptive names of what is tested; some of them fail, so assign NULL
lots_of_models %>%
  lapply(FUN=glance) %>%
  bind_rows()
```

The output of the above would look like models that failed were never tested rather than that they were tested and failed.

**Comment by alexpghayes** [comment]
I think this is the wrong approach, because it doesn't make sense to treat `NULL` like a model that didn't fit. When models fail to fit, they should either give an informative error message, or failing that, you probably still want to catch the exception and handle it.

So I propose something like:

```r
model_fn <- function(...) {
  tryCatch({
    fit_function,
    error = function(cnd) {
      # return some a "model that failed to converge object", etc
    }
  })
}

glance.unconverged_model <- function(...) {
  # custom logic
}

models <- map(model_fn, model_specs)
map_df(models, glance)
```

If this isn't clear, please let me know and I'll provide some more functional code as an example. In general, though, we need to treat `failed_fit` and `NULL` as different objects. R has a tradition of not using typed exceptions in modeling circumstances, so this may seem a bit new, but it's definitely the most robust approach to the problem.

**Comment by billdenney** [comment]
That is clear and it makes sense.

Would you accept a PR that made and exported an `NA_failed_fit_` object with a class `"failed_fit"` that would then fit the definition above for handling?

Specifically, it would have a `glance()` method that would return a 1-row, 0-column tibble and a `tidy()` method that would return the same with a warning indicating that it is tidying a `"failed_fit"` object.  I don't think it would get an `augment()` method, but if you feel otherwise, I'd be happy to add that, too.

(I brought this up in #565, but I'm not sure if I was clear when discussing it then.  Sorry if it seems like duplication or pushing too hard here.)

**Comment by alexpghayes** [comment]
> Would you accept a PR that made and exported an `NA_failed_fit_` object with a class `"failed_fit"` that would then fit the definition above for handling?

Probably not -- I would do this internally in your package. I think it's a good idea to start developing infrastructure / classed exceptions for model failures, but I think that should be done carefully and thought out ahead of time. For temporary / more-patchy solutions like `NA_failed_fit_` I think they should live in other packages for the moment. I believe the `fable` crew may be thinking about a more general solution to this problem (see the end of https://github.com/tidyverts/fable/issues/91 for example).

> Sorry if it seems like duplication or pushing too hard here.

Not at all, I'm happy to discuss! This is a very real problem that I think we should solve, I just think we want to build a general solution when we do solve it.

cc @topepo @DavisVaughan `parsnip` / the model implementation principles could be a good place to start considering classed model failure exceptions as well
