### ISSUE TITLE
Update NEWs based on Dev Day contributions

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#601]
- [x] update `NEWS`
- [x] make sure everyone makes it into CONTRIBUTORS

**Comment by alexpghayes** [comment]
Oh god this is going to be tricky I waited too long.

**Comment by alexpghayes** [comment]
I have missed way too many contributors recently and that's not good. Systematically review Github contributors and compare to `DESCRIPTION` before the next release to make sure we're not missing anyone.

**Comment by simonpcouch** [comment]
New contributors added to `DESCRIPTION` in 195cfd6.🙂 Workshopping `NEWS.md` here soon.

**Comment by simonpcouch** [comment]
Addressed in 27005a7 and fea0cfc!
