### ISSUE TITLE
contributor

### ISSUE THREAD

**Issue by lilymedina** [tidymodels/broom#607]
A few months ago I contributed with the tidier for mediate (pkg: mediation). Tidier seems to be working fine, but sadly I  saw that my name was not included in the list of contributors. 

Not sure if this is the right place for this, but thought I'd point it out.

**Comment by alexpghayes** [comment]
Gah you definitely should be on there sorry about that!

It looks like you made it onto the list with the initial PR (https://github.com/tidymodels/broom/pull/494/files), but oftentimes I merge several at once and there are conflicts that I resolve by hand. I must have made a mistake in there! Apologies!

Some notes for myself here about the PR process:

- [ ] Add Lily Medina back to `DESCRIPTION` as Contributor
- [ ] Set up a default PR template

**Comment by IndrajeetPatil** [comment]
@alexpghayes https://github.com/r-lib/usethis/issues/621

**Comment by medinali** [comment]
that's fine! thanks for following up.

**Comment by alexpghayes** [comment]
Closed in de62aad. Apologies again, and that you for your contribution!
