### ISSUE TITLE
tidy() fails for non model output

### ISSUE THREAD

**Issue by BibeFiu** [tidymodels/broom#612]
tidy(x) fails with an error
Error: C stack usage  19907888 is too close to the limit
if x is 
# A tibble: 3 x 3
  term  estimate std.error
  <lgl> <lgl>    <lgl>    
1 NA    NA       NA       
2 NA    NA       NA       
3 NA    NA       NA       
>

I guess checking if x is an appropriate input would solve the problem.

**Comment by alexpghayes** [comment]
This is a duplicate of #154. A more informative error message is coming in #614.
