### ISSUE TITLE
Update developer facing documentation

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#623]
Generally needs a lot of work, but two small things:

- use `arg_match()` (imported from `rlang`), rather than `arg.match()`
- don't use `return()`, just end on the object (purely stylistic). i.e.

```r
f <- function(x) {
  ...
  result
}
```

instead of 

```r
f <- function(x) {
  ...
  return(result)
}
```

This should go in the *How to contribute new tidiers* vignette

**Comment by alexpghayes** [comment]
Related: no longer okay to use `tidy.other_class` on objects of `my_class` -- `my_class` objects need their own tidier. This is for the purpose of maintainability -- if each class has it's own method instead of being rammed through some general function `tidy_many_classes()`, the individual tidiers are safer to change and easier to reason about.

**Comment by alexpghayes** [comment]
Things to get rid of / turn into more modular single functions:

- `process_lm()`
- `process_*()`
- ordinal tidiers

Turn each of these into a well documented issue that someone could tackle on their own

**Comment by alexpghayes** [comment]
Replacing functions: want to recreate functionality with cleaner code, rather than copy-pasting existing code. Explain this better!

**Comment by alexpghayes** [comment]
Just say no to `quick`

**Comment by alexpghayes** [comment]
All in the periods for stylistic purposes in both column names and function arguments -- double this is the case.

**Comment by alexpghayes** [comment]
Advice on how to support multiple versions of the same package, if that will be necessary (and how to determine when it is). Examples: `gam`, `ergm`.

**Comment by softloud** [comment]
I'd be interested in helping out with this if you'd like a new-to-dev r-user to try things out. 

I am learning about S3 working on these `metafor` tidiers, never encountered this before. I wrote a [blog post about it](http://cantabile.rbind.io/posts/2019-03-28-quack-quack-said-the-duck/).

**Comment by alexpghayes** [comment]
This brings up another great point, which is that in `broom` there are sort of two S3 things happening at the same time:

1. the standard S3 dispatch stuff
2. since the methods are all for the same generics, some extra tricks to enforce consistency amongst the methods (i.e. the `check_arguments()` test for example)

And it would be good to document both but especially 2.

**Comment by alexpghayes** [comment]
- [ ] How to read the documentation for the individual `check_*` tests
- [ ] Add some words of warning about `augment()` and starting with `safe_predict()`

**Comment by softloud** [comment]
Yes! I was feeling so chuffed with my fluffy duck, I thought I had it all figured out. But then I discovered there was more to S3 in this context. (btw, obviously it's entirely possible that all this information is the docs and I didn't absorb it, but then, I figure :shrug: that in and of itself is interesting.)

I agree this is really accessible as a project for beginners. It's clear where to integrate work, in terms of file structure. Still, alas, git for me is the hardest part; and I'm learning a lot from doing this.

**Comment by alexpghayes** [comment]
- [ ] Importing boilerplate documentation for the whole tidier with the classVar thing
- [ ] How to document params with and without templates
- [ ] How to document returns with `return_*()`

**Comment by alexpghayes** [comment]
Don't use `as_broom_tibble()` in `tidy.*()`

**Comment by alexpghayes** [comment]
How to write comments: steal from review of `diwanalr` pkg:

- Don't document *what* is happening, instead document *why* it is happening
- If you need comments to explain *what* the code is doing, the variable and function names need to be rewritten
