### ISSUE TITLE
Malformed Authors@R field

### ISSUE THREAD

**Issue by Jungpin** [tidymodels/broom#662]
> devtools::install_github("tidymodels/broom")
Downloading GitHub repo tidymodels/broom@master
✔  checking for file ‘/tmp/Rtmp41QOpi/remotes467c4bb11cde/tidymodels-broom-750d6ad/DESCRIPTION’ ...
─  preparing ‘broom’:
E  checking DESCRIPTION meta-information ...
   Malformed Authors@R field:
     <text>:198:57: 未預期的 ')'
   197:              email = "krauskae@gmail.com"),
   198:              comment = c(ORCID = "0000-0002-1466-5850")))
                                                                ^
   
   See section 'The DESCRIPTION file' in the 'Writing R Extensions'
   manual.
   
Error in run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  : 
  System command error

**Comment by alexpghayes** [comment]
Fixed in 0f11aa9
