### ISSUE TITLE
Improve categorical variable labels in tidy()

### ISSUE THREAD

**Issue by jessecambon** [tidymodels/broom#667]
I'd like to resurrect [this issue](https://github.com/tidymodels/broom/issues/16). When a categorical independent variable is present in a regression model, tidy() labels it in the term column by smooshing together the variable name and level. For instance, a variable "Cylinder" with levels of 6 and 8 is labeled "Cylinder6" and "Cylinder8".

For some use cases, it would be convenient to split the variable name and level into separate columns. This would make it easier to create custom formatted labels and join extra information, such as the sample sizes for each level, onto the dataframe that tidy() produces. A reproducible example where I have done this is below. 

I don't think that this feature would need to be done by default, but it would be nice to have it be an option (something like splitTermLabs=TRUE ?).

``` r
## Setup
library(broom)
library(tidyverse)

# obtain character list of independent variables in a model object. 
obtain_model_varlist <- function(model_obj) {
    var_list_raw <- unlist(strsplit(as.character(formula(model_obj)[3]),split=' \\+ '))
    # Remove smooth terms (s())
    return(var_list_raw[!str_detect(var_list_raw,'^s\\(')])
}

# Find frequency counts for all categorical variables in variable list
var_freq <- function(data,var) {
  var <- rlang::sym(var)
  print(var)

  if (is.factor(data %>% pull(!!var)) | is.character(data %>% pull(!!var))) {
  return(data %>% count(!!var) %>% mutate(term=quo_name(var)) %>%
          rename(level=!!var) %>%
          mutate(level=as.character(level), # convert to char
                 is_categorical=1) %>%
           select(term,everything()))
  } else {
    return(tibble())
  }
}

# Iterate through an entire dataset and return a dataset with sample
# sizes for all levels of categorical variables
find_all_freqs <- function(data,var_list) {
  all_freqs <- tibble()
  for (var in var_list) {
    all_freqs <- all_freqs %>%
      bind_rows(var_freq(data,var))
  }
  return(all_freqs)
}

# adds term_name field to a tidy dataframe which includes sample sizes
add_termnames <- function(data,term_freqs,var_list) {
  # Regexs to match the varname (when it begins a string)
  varregex <- paste(str_replace(var_list,'^','\\^'), collapse = "|")

  return(
  data %>%
  mutate(term_name = str_extract(term,varregex),
         level = case_when(!is.na(term_name) ~ str_replace(term,varregex,""))) %>%
  # add in frequency counts and labels
  left_join(term_freqs,by=c('term_name'='term','level')) %>%
  mutate(label=case_when(is.na(n) ~ term, # if not categorical than use original label
        is_categorical == 1 ~ str_c(term_name,': ', level,' (',scales::comma(n),')'),
                TRUE ~ str_c(level,' (',scales::comma(n),')')))
  )
}

## Build Linear Model

Mymtcars <- mtcars %>%
  mutate(Cylinders=factor(cyl),
         Gears=factor(gear))

car_model <- lm(mpg ~ Cylinders + disp + Gears,data=Mymtcars)

# obtain list of independent variables 
car_varlist <- obtain_model_varlist(car_model)
# sample sizes for categorical variable levels
car_freqs <- find_all_freqs(Mymtcars,car_varlist)
#> Cylinders
#> disp
#> Gears

tidy_car <- tidy(car_model,conf.int=T) %>%
  add_termnames(car_freqs,car_varlist)

## Plot Coefficients 

# Default Labels
ggplot(data=tidy_car %>% filter(label != '(Intercept)'),
          aes(x = reorder(term,-estimate), y = estimate)) +
geom_point() +
scale_y_continuous() +
geom_hline(yintercept=0,color='grey') +
coord_flip() +
  theme_bw() +
  theme(plot.title = element_text(lineheight=1, face="bold",hjust = 0.5)) +
geom_pointrange(mapping=aes(ymin=conf.low, ymax=conf.high)) + 
labs(title='MPG Linear Model - Default Labels',
     caption='Sample sizes shown in (). Horizontal lines represent 95% confidence intervals.') +
xlab('Term') + ylab('Coefficient')
```
![](https://i.imgur.com/FbSXHyj.png)

``` r
# Reformatted labels
ggplot(data=tidy_car %>% filter(label != '(Intercept)'),
          aes(x = reorder(label,-estimate), y = estimate)) +
geom_point() +
scale_y_continuous() +
geom_hline(yintercept=0,color='grey') +
coord_flip() +
  theme_bw() +
  theme(plot.title = element_text(lineheight=1, face="bold",hjust = 0.5)) +
geom_pointrange(mapping=aes(ymin=conf.low, ymax=conf.high)) + 
labs(title='MPG Linear Model - With Improved Labels',
     caption='Sample sizes shown in (). Horizontal lines represent 95% confidence intervals.') +
xlab('Term') + ylab('Coefficient')
```
![](https://i.imgur.com/jREoZPQ.png)

<sup>Created on 2019-03-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by alexpghayes** [comment]
I am happy to explore this but really need to understand in full detail how `model.matrix()` names and creates new columns first, to make sure that we don't create a brittle solution.

According to @topepo the only way to understand exactly what `model.matrix()` does is to read the underlying C code.

So I'm putting this on the back burner until I come across nice documentation of exactly what `model.matrix()` does. Perhaps @DavisVaughan has pointers from recent `hardhat` expeditions?

**Comment by DavisVaughan** [comment]
It's not a fun read, but I think the C code for it is here https://github.com/wch/r-source/blob/8bb261ce34d260078ddb95d45dbe156c9594b2a9/src/library/stats/src/model.c#L589

I'm not sure this is something broom should do. It feels like a special case honestly.

**Comment by alexpghayes** [comment]
Thinking about this more and I agree. It would be nice for this functionality to live in a separate package and to just call it from `broom`. Perhaps tools to recover variables names + levels and a detailed writeup of `model.matrix()` behavior could be an intern project next summer.

**Comment by mehrlander** [comment]
As a passerby I think this feature would be quite useful.  In the plots above you could have 30 terms and you'd like to color them by the variable they came from.  Having the variable at all in the labels easily gets cluttered, and sending it to color would seem like a common and useful expectation.  I was just watching one of David Robinson's Tidy Tuesday videos where he mutates the variable parts individually to reduce clutter.  The wine reviews video, specifically.  I had been playing around today with how to replace the variable part with icons, but sending it to color would be much better.  It would also be great to be able to join sample size as noted above (I've had the same wish at another time) as that would also go great in these plots.  I was trying to figure out how to separate them myself and that is what brought me here.

**Comment by topepo** [comment]
The problem is writing potentially complicated code to undo what `model.matrix()`produces. 

I agree that it would be good but think that we should avoid doing it. 

There is an alternative... use a [recipe](https://www.tidymodels.org/start/recipes/) with tidymodels. `step_dummy()` separates the column and level using an underscore (and allows you to customize that, if needed). More information is [here](https://recipes.tidymodels.org/articles/Dummies.html). 

``` r
library(tidymodels)
#> ── Attaching packages ─────────────────────────────────────── tidymodels 0.1.0 ──
#> ✓ broom     0.5.6      ✓ recipes   0.1.12
#> ✓ dials     0.0.6      ✓ rsample   0.0.6 
#> ✓ dplyr     0.8.5      ✓ tibble    3.0.1 
#> ✓ ggplot2   3.3.0      ✓ tune      0.1.0 
#> ✓ infer     0.5.1      ✓ workflows 0.1.1 
#> ✓ parsnip   0.1.1      ✓ yardstick 0.0.6 
#> ✓ purrr     0.3.4
#> Warning: package 'recipes' was built under R version 3.6.2
#> ── Conflicts ────────────────────────────────────────── tidymodels_conflicts() ──
#> x purrr::discard()  masks scales::discard()
#> x dplyr::filter()   masks stats::filter()
#> x dplyr::lag()      masks stats::lag()
#> x ggplot2::margin() masks dials::margin()
#> x recipes::step()   masks stats::step()

Mymtcars <- mtcars %>%
  mutate(Cylinders=factor(cyl),
         Gears=factor(gear))

# make a custom function: 

car_names <- function (var, lvl, ordinal = FALSE, sep = "_")  {
  paste0(var, ": ", lvl)
}

car_rec <- 
  recipe(mpg ~ Cylinders + disp + Gears, data = Mymtcars) %>% 
  step_dummy(all_nominal(), naming = car_names) %>% 
  prep()

model_data <- juice(car_rec)

car_model <- lm(mpg ~ .,data = juice(car_rec))
tidy_car <- 
  tidy(car_model, conf.int = TRUE) %>% 
  # remove backticks
  mutate(term = gsub("`", "", term))


ggplot(data = tidy_car %>% filter(term != '(Intercept)'),
       aes(x = reorder(term, -estimate), y = estimate)) +
  geom_point() +
  geom_hline(yintercept = 0, color = 'grey') +
  coord_flip() +
  theme_bw() +
  theme(plot.title = element_text(lineheight=1, face="bold",hjust = 0.5)) +
  geom_pointrange(mapping = aes(ymin = conf.low, ymax = conf.high)) 
```

![](https://i.imgur.com/urW3MH6.png)

<sup>Created on 2020-05-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mehrlander** [comment]
Very nice!  I've been interested to dig into tidymodels.  To give it color, then, I get this.

``` r

library(tidymodels)
#> -- Attaching packages ----------------------------------------------------------------------------------------------------------------------------- tidymodels 0.1.0 --
#> v broom     0.5.6      v recipes   0.1.12
#> v dials     0.0.6      v rsample   0.0.6 
#> v dplyr     0.8.5      v tibble    3.0.1 
#> v ggplot2   3.3.0      v tune      0.1.0 
#> v infer     0.5.1      v workflows 0.1.1 
#> v parsnip   0.1.1      v yardstick 0.0.6 
#> v purrr     0.3.4
#> -- Conflicts -------------------------------------------------------------------------------------------------------------------------------- tidymodels_conflicts() --
#> x purrr::discard()  masks scales::discard()
#> x dplyr::filter()   masks stats::filter()
#> x dplyr::lag()      masks stats::lag()
#> x ggplot2::margin() masks dials::margin()
#> x recipes::step()   masks stats::step()

Mymtcars <- mtcars %>%
  mutate(Cylinders=factor(cyl),
         Gears=factor(gear))

# make a custom function: 
car_names <- function (var, lvl, ordinal = FALSE, sep = "_")  {
  paste0(var, "|:", lvl)
}

car_rec <- 
  recipe(mpg ~ Cylinders + Gears + hp + wt + disp + drat + qsec, data = Mymtcars) %>% 
  step_dummy(all_nominal(), naming = car_names) %>% 
  prep()

model_data <- juice(car_rec)

car_model <- lm(mpg ~ ., data = model_data)
tidy_car <- 
  tidy(car_model, conf.int = T) %>% 
  # remove backticks
  mutate(term = gsub("`", "", term)) %>%
  tidyr::separate(term, c("var","cat"), sep = "[|]", fill = "left") %>%
  mutate(var = ifelse(is.na(var),"num",var)) 

ggplot(data = tidy_car %>% filter(cat != '(Intercept)'),
       aes(x = reorder(cat, -estimate), y = estimate)) +
  geom_hline(yintercept = 0, color = 'grey') +
  coord_flip() +
  theme_bw() +
  theme(plot.title = element_text(lineheight=1, face="bold",hjust = 0.5)) +
  geom_pointrange(mapping = aes(ymin = conf.low, ymax = conf.high, color = var), size = 1) +
  scale_color_manual(values=c("maroon", "darkgreen", "grey"))
```

![](https://i.imgur.com/TgdEHVh.png)

<sup>Created on 2020-05-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by guyabel** [comment]
I created a package [https://github.com/guyabel/tidycat](https://github.com/guyabel/tidycat) with a `tidy_categorical()` function based on `dummy.coef()` that might address some of the issues (in this issue). Any comments or suggestions are very welcome.

**Comment by mehrlander** [comment]
Looks cool, but I just tried to install it via CRAN and received:  package ‘tidycat’ is not available (for R version 4.0.0).  Is that expected?

**Comment by guyabel** [comment]
@mehrlander yeah... i just submitted it... so might take a while - hopefully github version works

**Comment by mehrlander** [comment]
Well it looks useful to me.  A few questions I'd have:
* Does it not work if you have non-factor variables in the model?  I'd hope that it could deal with those also.  It raises the question of whether to leave the term NA or to copy over the variable for both.  The tidyr::separate function I used with Max's suggestion above has a "fill" argument which gives options.  
* Maybe I should, but I don't know what your "effect" column refers to.
* I'm sure a very common column people will want to add is sample size (n, as I thought of it).  Perhaps an add_count type option would be useful.
* Another stumbling block I had, though it's likely out of your scope, is to be able to color the labels as well on those plots.  It seems particularly helpful here if you have a large set of them.  Below is a broken version where I used the solution proposed here: https://stackoverflow.com/questions/38862303/customize-ggplot2-axis-labels-with-different-colors 
A comment mentions the warning when trying to use a vectorized solution: 
`Warning message: Vectorized input to "element_text()" is not officially supported. Results may be unexpected or may change in future versions of ggplot2.`  This matched my experience as you can see, so I don't know what the story is there or if it is anything that can be helped here.
![image](https://user-images.githubusercontent.com/39290383/82882471-f4d50a00-9ef5-11ea-8b60-60bce6536ce6.png)

**Comment by guyabel** [comment]
@mehrlander not sure if this is the right place to discuss your ideas - perhaps if you have any more you can open an issue on the tidycats [github](https://github.com/guyabel/tidycat/issues)? - in any case...

1) i have changed the output so that the `level` column takes the name of the continuous variable, which makes plotting much easier 
2) `effect` is to filter between main effects and interactions - see the help file and the second example i added to the [README](https://github.com/guyabel/tidycat#interactions), 
3) i added an option `n_level` to get the number of observations in each category and 
4) i think if you set `colour = variable` in ggplot you would get the plot you want - see a new example in the [README](https://github.com/guyabel/tidycat#enhanced-coefficient-plots)

**Comment by mehrlander** [comment]
That's great, I will try it out. I'm also curious to see if tidymodels means broom is less important.  It seems more like "clean as you go."  :)

**Comment by topepo** [comment]
> I'm also curious to see if tidymodels means broom is less important.

It does not.
