### ISSUE TITLE
tidy.multinom() fails when formula is an object

### ISSUE THREAD

**Issue by namarkus** [tidymodels/broom#668]
I usually assign formulae to a variable and refer to this variable in the model function. For lineare models (lm and glm) this works fine. However, using this approach with nnet::multinomial function raises an error: 

> Error in is.data.frame(data) : object '.x' not found

Here's a short reprex:

```r

# Assignin formula to a variable works with linear models
log_mod = vs ~ mpg + qsec + gear

mtcars %>%
  nest(-am) %>% 
  mutate(fit = map(data, ~ lm(log_mod, data = .x)),
         tidied = map(fit, tidy)) %>% 
  unnest(tidied)


# Same approach fails using nnet::multinom function
multinom_mod = cyl ~ mpg + qsec + gear

mtcars %>%
  nest(-am) %>% 
  mutate(fit = map(data, ~ nnet::multinom(multinom_mod, data = .x)),
         tidied = map(fit, tidy)) %>% 
  unnest(tidied)

# There's nothing wrong with formular or data, because defining the formular directly in multinom-function just works fine.
mtcars %>%
  nest(-am) %>% 
  mutate(fit = map(data, ~ nnet::multinom(cyl ~ mpg + qsec + gear, data = .x)),
         tidied = map(fit, augment)) %>% 
  unnest(tidied)
```
maybe this is a scoping issue?

**Comment by brunaw** [comment]
It's easier to make it work by defining `.x = .x` inside the `map`:
```
mtcars %>%
  nest(-am) %>% 
  mutate(fit = map(data, ~ nnet::multinom(multinom_mod, data = .x, .x = .x)),
         tidied = map(fit, tidy)) %>% 
  unnest(tidied)
```
A true 'fix' would require changing the internals of the `summary` function for multinomial regression, which can be very messy :)

**Comment by namarkus** [comment]
Thanks for your reply @brunaw although it doesn't change the behaviour, I still get the same error ("Error in is.data.frame(data) : object '.x' not found")

Meanwhile I found out, that the main difference between using formula as variable vs using formula directly is a different ".Environment" attribut in multinom object.

    # model using formula-object
    multinom_mod = cyl ~ mpg + qsec + gear

    mod_form_obj =
    mtcars %>%
      nest(-am) %>% 
      mutate(fit = map(data, ~ nnet::multinom(multinom_mod, data = .x)))

    # tidying doesn't work:
    mod_form_obj %>% mutate(tidied = map(fit, tidy))

    # model using formula directly
    mod_form =
    mtcars %>%
      nest(-am) %>% 
      mutate(fit = map(data, ~ nnet::multinom(cyl ~ mpg + qsec + gear, data = .x)))

    # tidying does work:
    mod_form %>% mutate(tidied = map(fit, tidy))

    # the difference lays in the said attribute
    mod_form_obj %>% pluck("fit", 1,"terms") %>% attr(".Environment")  # <environment: R_GlobalEnv>
    mod_form %>% pluck("fit", 1,"terms") %>% attr(".Environment")  # <environment: 0x000002d1bd07a5e0>

Obviously .x doesn't exist in global environment.
Maybe there is a better way to provide the formula-object to multinom function, so that environment of multinom object is set correctly?

**Comment by vincentarelbundock** [comment]
I investigated this issue a bit and concluded that this is unrelated to `broom`. Therefore, I think this issue should be closed.

If we remove the `broom` package and all calls to `tidy` from your example, the first chunk still works (with warning as before) and the second chunk still fails.

``` r
library(tidyverse)

# Assigning formula to a variable works with linear models
f = vs ~ mpg + qsec + gear
mtcars %>%
  nest(-am) %>% 
  mutate(fit = map(data, ~ lm(f, data = .x)))

#> Warning: All elements of `...` must be named.
#> Did you want `data = c(mpg, cyl, disp, hp, drat, wt, qsec, vs, gear, carb)`?
#> # A tibble: 2 x 3
#>      am data               fit   
#>   <dbl> <list>             <list>
#> 1     1 <tibble [13 × 10]> <lm>  
#> 2     0 <tibble [19 × 10]> <lm>

# Same approach fails using nnet::multinom function
f = cyl ~ mpg + qsec + gear
mtcars %>%
  nest(-am) %>% 
  mutate(fit = map(data, ~ nnet::multinom(f, data = .$x)))

#> Warning: All elements of `...` must be named.
#> Did you want `data = c(mpg, cyl, disp, hp, drat, wt, qsec, vs, gear, carb)`?
#> Warning: Problem with `mutate()` input `fit`.
#> ℹ Unknown or uninitialised column: `x`.
#> ℹ Input `fit` is `map(data, ~nnet::multinom(f, data = .$x))`.
#> Warning: Unknown or uninitialised column: `x`.
#> Error: Problem with `mutate()` input `fit`.
#> ✖ object 'cyl' not found
#> ℹ Input `fit` is `map(data, ~nnet::multinom(f, data = .$x))`.
```

<sup>Created on 2020-12-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by simonpcouch** [comment]
Yeah, it looks like some soft-deprecations have happened in `tidyr` since this issue was filed, and I'm unable to reproduce the specific error you're seeing.

A slightly more minimal reprex:

``` r
library(nnet)
library(broom)
  
tidy(multinom(cyl ~ mpg + qsec + gear, data = mtcars))
#> # weights:  15 (8 variable)
#> initial  value 35.155593 
#> iter  10 value 15.752103
#> iter  20 value 7.324057
#> iter  30 value 5.070677
#> iter  40 value 2.889624
#> iter  50 value 2.119980
#> iter  60 value 1.418743
#> iter  70 value 1.104838
#> iter  80 value 1.053459
#> iter  90 value 0.979002
#> iter 100 value 0.916800
#> final  value 0.916800 
#> stopped after 100 iterations
#> # A tibble: 8 x 6
#>   y.level term        estimate std.error statistic p.value
#>   <chr>   <chr>          <dbl>     <dbl>     <dbl>   <dbl>
#> 1 6       (Intercept)   119.       81.6      1.45   0.146 
#> 2 6       mpg            -2.21      2.13    -1.04   0.301 
#> 3 6       qsec           -2.81      2.68    -1.05   0.295 
#> 4 6       gear           -5.31      5.27    -1.01   0.314 
#> 5 8       (Intercept)   292.        2.79   105.     0     
#> 6 8       mpg            -4.06      4.51    -0.900  0.368 
#> 7 8       qsec           -8.81      4.50    -1.96   0.0503
#> 8 8       gear          -15.2      10.5     -1.45   0.146

form <- cyl ~ mpg + qsec + gear
tidy(multinom(form, data = mtcars))
#> # weights:  15 (8 variable)
#> initial  value 35.155593 
#> iter  10 value 15.752103
#> iter  20 value 7.324057
#> iter  30 value 5.070677
#> iter  40 value 2.889624
#> iter  50 value 2.119980
#> iter  60 value 1.418743
#> iter  70 value 1.104838
#> iter  80 value 1.053459
#> iter  90 value 0.979002
#> iter 100 value 0.916800
#> final  value 0.916800 
#> stopped after 100 iterations
#> # A tibble: 8 x 6
#>   y.level term        estimate std.error statistic p.value
#>   <chr>   <chr>          <dbl>     <dbl>     <dbl>   <dbl>
#> 1 6       (Intercept)   119.       81.6      1.45   0.146 
#> 2 6       mpg            -2.21      2.13    -1.04   0.301 
#> 3 6       qsec           -2.81      2.68    -1.05   0.295 
#> 4 6       gear           -5.31      5.27    -1.01   0.314 
#> 5 8       (Intercept)   292.        2.79   105.     0     
#> 6 8       mpg            -4.06      4.51    -0.900  0.368 
#> 7 8       qsec           -8.81      4.50    -1.96   0.0503
#> 8 8       gear          -15.2      10.5     -1.45   0.146
```

<sup>Created on 2020-12-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

The formula being an object doesn't seem to be an issue.🙂
