### ISSUE TITLE
`survey` package not present in vignette `Available methods`

### ISSUE THREAD

**Issue by cimentadaj** [tidymodels/broom#693]
The vignette is [here](https://broom.tidyverse.org/articles/available-methods.html) yet there are methods and an `.R` file for the `survey` package [here](https://github.com/tidymodels/broom/blob/8e542fe687f0a28cd0a195014974a2a68e8ef87f/R/survey-tidiers.R)

**Comment by alexpghayes** [comment]
The pkgdown site is very out of date. I am working on setting up automatic deployment of the pkgdown site so this won't be an issue in the future.
