### ISSUE TITLE
lfe/felm tidyers: code not updated?

### ISSUE THREAD

**Issue by MatthieuStigler** [tidymodels/broom#698]
Hi

I could not find anymore in 0.5.2 commits made previously, introduced in I believe 0.5. Was that an implementation decision, or did it disappear unvolunatrily?

- [lfe-tidier: add argument quick to tidy ](https://github.com/tidymodels/broom/commit/24715191a7456ae99edda3788a56087d8969f10d#diff-915eee131333bdcfe043ee22b2121763)

- [lfe tidyr: allow for multiple responses models ](https://github.com/tidymodels/broom/commit/ffe83afe78e0a0784ad1c7ed95bebe2535619fa3#diff-915eee131333bdcfe043ee22b2121763)

Thanks!!

**Comment by IndrajeetPatil** [comment]
I think the code you contributed is going to be part of `0.7.0` release (not `0.5.2`): https://github.com/tidymodels/broom/blob/master/NEWS.md

**Comment by MatthieuStigler** [comment]
Thanks for your answer!

Ok, you are right. Somehow, that contribution was announced for version 0.5 (look for line *Added argument quick for tidy.plm and tidy.felm* in NEWS), but it will actually come for 0.7!

**Comment by alexpghayes** [comment]
Definitely a me being bad at git issue. Sorry for the confusion.
