### ISSUE TITLE
Don't export confint_tidy()

### ISSUE THREAD

**Issue by jasonyang5** [tidymodels/broom#703]
---

Although the confint_tidy function makes a table as expected, it doesn't include a 'term' like the tidy for models does, so the table doesn't tell you which confidence interval refers to which variable. 

This should be a really easy fix (I could probably push it if you show me where the source code for confint_tidy is) by appending the rownames to a column.

I attached an example where you can compare the normal confint function to the confint_tidy output.

```r
library(tidyverse)
library(reprex)
library(broom)
attach(diamonds)

diamonds_model = lm(price ~ carat + depth, data = diamonds)
ci_normal = confint(diamonds_model)
ci_tidy = confint_tidy(diamonds_model)
```

<sup>Created on 2019-05-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
```

**Comment by alexpghayes** [comment]
Thanks for pointing this out! This reminds me that `confint_tidy()` is really supposed to be an internal function -- I'd rather not export it. 

If you'd like to make this change, it'll mean removing this line: https://github.com/tidymodels/broom/blob/master/R/utilities.R#L410

**Comment by alexpghayes** [comment]
Aside: if you ever need to find a function in package, open the package source in RStudio use the `ctrl` + `.` shortcut, then type in the function name in the search field that shows up!

**Comment by jasonyang5** [comment]
I see! Great, thank you!

**Comment by alexpghayes** [comment]
Reopening to remind myself to not export `confint_tidy()`.

**Comment by anddis** [comment]
Hello, I understand why you don't want to export `confint_tidy()`, but why is it deprecated now? It was a useful function.
My user case is to calculate Wald confidence intervals (`confint.default()`) instead of profile likelihood CIs for `glm` objects (`confint.glm()`).
An alternative could be to specify the desired `confint` method directly in `tidy()` to override the generic if one wishes so?

**Comment by alexpghayes** [comment]
If this is something you're interested in I might be open to a `type.confint` argument to `tidy.glm()`. `confint_tidy()` has been superseded by other internal tooling, and was not intended for direct use by users.

**Comment by anddis** [comment]
I am **extremely** interested!

As a matter of fact, it would be a big improvement over `confint_tidy()` (which I know was never intended for direct use by users, but it's a handy function for this purpose).
I don't know if there are other user cases that would warrant adding a `type.confint` argument to other methods as well, but it would be great to have it for `tidy.glm()`.
