### ISSUE TITLE
glmer.nb and Conf Int

### ISSUE THREAD

**Issue by aperaltasantos** [tidymodels/broom#717]
Hello, 

I am trying to use augment with a negative binomial model, but i cant find a way to get the Conf Intervals out of the augment function 
Code bellow

c.dpt3.drt <- glmer.nb(
  dpt_3 ~ month + fdistrict  + myear + int1 + int_slope + int2 + int_slope2 + treat  + treat:myear  + treat:int1 + treat:int_slope + treat:int2 + treat:int_slope2 + dpt3_target + (1 +  myear| ID),
  data = comp.df, 
  nAGQ = 0,
  control = glmerControl(optimizer = "nloptwrap"))

pred_c.dpt3.drt <- broom.mixed::augment(c.dpt3.drt,  
                       conf.int = TRUE, 
                       effects = "random",
                       type = "response")

In the pred_c.dpt3.drt dataframe I get the .fitted values but i can't find any conf intervals or any SE that allow me to calculate the CI.
Thanks

Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem

```r
# insert reprex here
```

**Comment by alexpghayes** [comment]
Hey! It's hard to help without the data you used to fit the model, but try:

```
library(broom)
tidy(your_model_object, conf.int = TRUE)
```

**Comment by aperaltasantos** [comment]
Thanks, Alex, 

The tidy function works fine, it's the "augment" that it's not given me back the conf intervals

**Comment by alexpghayes** [comment]
Ah, didn't realize this is in `broom.mixed`. It might not be implemented? If it isn't and you'd like to request confidence/prediction intervals, you could do that at https://github.com/bbolker/broom.mixed/

**Comment by alexpghayes** [comment]
Closing since I haven't heard back! Let me know if there's anything I can help with!

**Comment by aperaltasantos** [comment]
Thanks, Alex,

We decided to go with another method, thank for the support anyway.

And congrats for your contributions to the R community

All the best
________________________________
