### ISSUE TITLE
Use term instead of parameter in tidy.epi.2byb2()

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#718]
Re: #715

**Comment by alexpghayes** [comment]
@zoews this would be a good place to start. The issue consists of changing the name of a column in a dataframe for consistent behavior throughout the package. I also recommend reading https://broom.tidyverse.org/articles/adding-tidiers.html to get a feeling for contributing to `broom`!

**Comment by zoews** [comment]
Pull request for fix is: #723  !
