### ISSUE TITLE
Compatibility with logistf package

### ISSUE THREAD

**Issue by Roisin-White** [tidymodels/broom#724]
Hello,

Thank you for this amazing package! Would it be possible to add a tidier for model output from the logistf package for running Firth's bias-reduced logistic regressions?

**Comment by alexpghayes** [comment]
Probably! Can you provide a [reprex](https://www.tidyverse.org/help/#reprex) showing how to fit the model you'd like to see supported?

**Comment by vlepori** [comment]
Hi! not the original poster, but I would also love to see this implemented.  The penalized logistic regression is fitted with the usual syntax:

```
require(logistf)
data <- data.frame(time = 1:12, event = c(0,1,0,1,1,1,1,1,1,1,1,1))
model <- logistf::logistf(event ~time, data)
summary(model)
coef(model)
# broom::tidy(model) 
```
Thanks so much for your work!

**Comment by IndrajeetPatil** [comment]
`broom` is moving away from adding new tidiers (https://github.com/tidymodels/broom/issues/795#issuecomment-639547477). 

In the meanwhile, you can use this alternative solution:

```r
library(logistf)
data <- data.frame(time = 1:12, event = c(0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1))
model <- logistf::logistf(event ~ time, data)
summary(model)
#> logistf::logistf(formula = event ~ time, data = data)
#> 
#> Model fitted by Penalized ML
#> Confidence intervals and p-values by Profile Likelihood Profile Likelihood 
#> 
#>                   coef  se(coef) lower 0.95 upper 0.95     Chisq          p
#> (Intercept) -1.1128004 1.6182163 -5.8454487   1.759779 0.5483083 0.45900976
#> time         0.5039592 0.3582692 -0.0195013   2.090745 3.4797286 0.06212493
#> 
#> Likelihood ratio test=3.479729 on 1 df, p=0.06212493, n=12
#> Wald test = 1.978663 on 1 df, p = 0.1595313
#> 
#> Covariance-Matrix:
#>            [,1]       [,2]
#> [1,]  2.6186239 -0.4934323
#> [2,] -0.4934323  0.1283568

broomExtra::tidy_parameters(model)
#> # A tibble: 2 x 7
#>   term        estimate std.error conf.low conf.high df.error p.value
#>   <chr>          <dbl>     <dbl>    <dbl>     <dbl>    <dbl>   <dbl>
#> 1 (Intercept)   -1.11      1.62   -5.85        1.76       10  0.459 
#> 2 time           0.504     0.358  -0.0195      2.09       10  0.0621
```

**Comment by vlepori** [comment]
Thank you for the update and the suggestion @IndrajeetPatil , will try this out !

**Comment by vincentarelbundock** [comment]
I started PR https://github.com/tidymodels/broom/pull/963 for this but eventually gave up because:

1. `confint.logistf` does not correctly handle the `level` argument.`
2. `confint.logistf` triggers some hard to track down (for me) error in `broom_confint_terms`.
3. `logistf` is one of those packages that `cat`s to console, and I find that annoying.
4. There is some weird incompatibility between `logistf` and `stats::oneway.test`. As soon as we load the former, estimating the latter breaks with an error about needeing a two-sided formula. I saw a similar problem on StackOverflow, so that may not be entirely `logistf`'s fault, but I can see the side effect that causes the problem.

For future reference, here are draft/incomplete versions of tidy methods:

```
tidy.logistf <- function(x, conf.int = FALSE, conf.level = 0.95, ...) {

  trash <- utils::capture.output(s <- summary(x))
  ret <- tibble(
     term = names(s$coefficients),
     estimate = s$coefficients,
     std.error = sqrt(diag(s$var)),
     p.value = s$prob)
  
  if (conf.int) {
    if (conf.level != x$conflev) {
      warning("Models of class `logistf` do not allow `glance` to modify the alpha level after fitting the model. Please use the `alpha` argument of the `logistf::logistf` function.")
    }

    ## broom_confint_terms triggers a level-related argument 
    # ci <- broom_confint_terms(x, level = conf.level)
    # ret <- dplyr::left_join(ret, ci, by = "term")

    ci <- confint(x, level = conf.level)
    ci <- tibble::tibble(
      term = row.names(ci),
      conf.low = ci[, 1],
      conf.high = ci[, 2])

    ret <- dplyr::left_join(ret, ci, by = "term")
  }

  ret
}

glance.logistf <- function(x, ...) {
  trash <- utils::capture.output(s <- summary(x, ...))
  ret <- as_glance_tibble(
    df     = s$df,
    nobs   = s$n,
    na_types = "ii")
  ret
} 
```

**Comment by simonpcouch** [comment]
Thanks for giving those a go!
