### ISSUE TITLE
Potential Feature Request: Including the reference level for a factor variable in tidy object

### ISSUE THREAD

**Issue by mattwarkentin** [tidymodels/broom#726]
Hi,

So my thought process is that it is probably becoming many peoples workflow to run a model, `tidy` it with `broom`, and feed the `tibble` into something like `kable` or `ggplot2` to produce a table or figure for a report. However, one issue I see is that the reference level for a factor variable is lost and when presenting model coefficients in a table, it is often useful to provide the reference level as the null effect (for example 0 for log-odds or 1 for odds ratio in logistic regression).

Unless I am missing something, I don't see a good way to recover the reference level so it can be used easily to show the reference/null effect in tables and figures.

Here is a really bad (but working) example of what I think would be nice. It is a wrapper for `broom::tidy.lm()`, but adds back the reference level for the factor variable. Again, this code is definitely brittle and only demonstrates this very simple example...

```r
# Fit linear model with a factor variable
lm.obj <- lm(Sepal.Length ~ as.factor(Species), data = iris)

# New function that tidys object with broom, then adds back the reference level
tidy_lm <- function(obj) {
  tidy_tib <- broom::tidy(obj)
  
  # Take the first level in obj$xlevels and glue it to the factor variable name
  term <- glue::glue('{names(obj$xlevels)}{obj$xlevels[[1]][1]}')
  
  # Make estimate null effect, with all other statistics as missing
  ref_tib <- tibble::tibble(
    term = term,
    estimate = 0,
    std.error = NA_real_,
    statistic = NA_real_,
    p.value = NA_real_
  )
  
  tidy_with_ref <- dplyr::bind_rows(tidy_tib, ref_tib)
  tidy_with_ref
}

tidy_lm(lm.obj) %>% 
  knitr::kable(format = 'pandoc')
```

**Comment by alexpghayes** [comment]
Hey! `tidy()` is about reporting model parameters. I think you're looking for *marginal means* instead. I would take a look at the [`emmeans`](https://cran.r-project.org/web/packages/emmeans/index.html) package!

**Comment by mattwarkentin** [comment]
@alexpghayes Hmm. I am a little confused about what in my post is related to marginal means and the `emmeans` package? My interest is in whether it makes sense for `tidy()` to return the reference level and null value for a factor variable when tidying a model in order to make it easier to present data in tables and figures.

**Comment by alexpghayes** [comment]
I'm hoping to write a longer answer explaining the different between the two in the near future, but for now, I would ask: what is the value of adding the additional row to the table like in the code above? What is the information contained in that row? Is it the same kind of information contained in the other rows?

I can see the value of including reference levels to make coefficients interpretable, but I think that kind of information should go in a footnote or caption to the table, not the table itself. The reference level and the coefficient estimates are two different kinds of information that it doesn't make sense to mix.
