### ISSUE TITLE
by_2sd set to FALSE throws error

### ISSUE THREAD

**Issue by ecohen13** [tidymodels/broom#727]
---

Trying to set by_2sd=FALSE in order to not rescale the models throws "Error in 1 - level : non-numeric argument to binary operator" error.

```r
library(dotwhisker)
# run a regression compatible with tidy
m1 <- lm(mpg ~ wt + cyl + disp + gear, data = mtcars)
m2 <- update(m1, . ~ . + hp) # add another predictor
dwplot(list(m1, m2), by_2sd = FALSE)
```

**Comment by alexpghayes** [comment]
Does `dwplot()` call `tidy()`? Would you mind making a [reprex](https://www.tidyverse.org/help/#reprex)? I think you're almost there but what package does `dwplot` come from?

**Comment by ecohen13** [comment]
I've updated the reprex to load the right package. Should this be an issue for `dotwhisker` and not `broom`?

**Comment by alexpghayes** [comment]
My suspicion is yes!
