### ISSUE TITLE
documentation for `tidy()` goes nowhere

### ISSUE THREAD

**Issue by IndrajeetPatil** [tidymodels/broom#738]
While trying to diagnose the source of https://github.com/r-lib/generics/issues/43, I noticed that `tidy()` documentation in `broom` website goes nowhere:

![tidy](https://user-images.githubusercontent.com/11330453/62826236-ecd5f480-bb85-11e9-8aaf-1d1b8cd7e507.gif)

I think this is because you are using the `CRAN` version of `pkgdown`-

https://github.com/tidymodels/broom/blob/4a6cdcb78d8508236bc7ef1b47ae0e461b86d478/.travis.yml#L15-L22

In the development version of `pkgdown`, functions are linked to their documentation on https://rdrr.io

For example, here is a template from `rlang`-

https://github.com/r-lib/rlang/blob/09fbc8618bb0a886d2d4546e8cbd378b1c178f65/.travis.yml#L14-L21

**Comment by simonpcouch** [comment]
Thanks for catching this! This seems to be have been fixed with the new pkgdown release, as you predicted. Closing for now.🙂
