### ISSUE TITLE
augment should allow including all columns of glm$data, not just those included in formula

### ISSUE THREAD

**Issue by Inferrator** [tidymodels/broom#753]
I propose adding a `include_full_data` argument to augment. If TRUE, augment includes the entire dataset in glmobject$data in the output.

Let me illustrate where it is an issue

```r
#simulated glm data
glmdata = data.frame(ID=1:100, A=rnorm(100), B=rnorm(100)) %>% mutate(response=rbinom(length(ID),1,1/(1+exp(-2*A-3*B))  ))

#fit model, not including the ID variable
glmfit = glm(response~A+B, glmdata,family='binomial')

#ID variable is contained in glm$data
str(glmfit$data)

#works!
head(glmfit$data$ID)


#use broom::augment
augmented = glmfit %>% augment

#does not work
augmented$ID
```

How do we deal with it now? Using the newdata argument, and passing data ...again.
```r
augmented = glmfit %>% augment(newdata=glmdata)
head(augmented$ID)
```

So why is this not satisfactory? Because it gets ugly when using nested data.

```r
glmdata1 = data.frame(segm=1,ID=1:100, A=rnorm(100), B=rnorm(100)) %>% mutate(response=rbinom(length(ID),1,1/(1+exp(-2*A-3*B))  ))
glmdata2 = data.frame(segm=2,ID=1:100, A=rnorm(100), B=rnorm(100)) %>% mutate(response=rbinom(length(ID),1,1/(1+exp(-3*A-2*B))  ))

glmdata_nest = rbind(glmdata1,glmdata2) %>% group_by(segm) %>% nest


#fit the two models via map
glmfit_nest= glmdata_nest %>% mutate(model=map(data, glm, formula=response~A+B, family='binomial') )

#run augment via map
glmfit_nest_augmented = glmfit_nest %>% mutate(augmented = map(model,augment))

#ID is not here ...
glmfit_nest_augmented$augmented$ID


#ok, we have to reference .$data here, and the code looks ugly
glmfit_nest_augmented <- glmfit_nest %>% mutate(augmented = map(model,~ augment(., newdata=.$data)))
```

So the problem is ...
```r
glmfit_nest %>% mutate(augmented = map(model,~ augment(., newdata=.$data)))
``` 
looks a lot uglier than
```r
glmfit_nest %>% mutate(augmented = map(model,augment, include_full_data=T))
```
would

**Comment by Inferrator** [comment]
Taking a look at `augment.glm`, we can see that `model.frame` is used:

  data = model.frame(x)

Maybe we can change this to 
data = x$data

?

**Comment by alexpghayes** [comment]
@Inferrator I don't think the solution to this aesthetic issue is to introduce redundant special-case functionality into `broom`. I would encourage you to check out `rap` (https://github.com/romainfrancois/rap) and related packages for vectorizing operations in data frames.

**Comment by Inferrator** [comment]
@alexpghayes: I disagree. When a set of functions is used with %>% pipes, unnecessarily losing information along the pipe is not desirable behavior. 

Something as simple as a respondent ID is lost when calling augment.glm, making it hard to to use predictions or analyze outliers.
While you can use newdata= - it doesn't look pretty, and it is inefficient.
