### ISSUE TITLE
Suggestion: in survival tidier, extract strata variable into separate variables

### ISSUE THREAD

**Issue by dgrtwo** [tidymodels/broom#765]
The survfit tidier currently returns all the predictor variables in a combined string, which could be separated into usable variables.

```r
library(dplyr)
library(survival)
library(broom)

surv_td <- survfit(Surv(stop - start, status) ~ sex + pcdx,
                    data = mgus1) %>%
  tidy()
```

This returns a strata column of the form `sex=..., pcdx=...`, see here:

```r
> surv_td %>% count(strata)
# A tibble: 7 x 2
  strata                  n
  <chr>               <int>
1 sex=female, pcdx=AM     7
2 sex=female, pcdx=LP    10
3 sex=female, pcdx=MA     2
4 sex=female, pcdx=MM    45
5 sex=male, pcdx=AM       8
6 sex=male, pcdx=MA      12
7 sex=male, pcdx=MM      42
```

Ideally, these could be extracted into separate columns, `sex` and `pcdx`, which would allow them to be used immediately in visualizations or summaries. For reverse compatibility with existing uses of the survival tidiers, the result could still retain the `strata` column.

**Comment by alexpghayes** [comment]
Sounds like a great PR 😉!

**Comment by jcfisher** [comment]
I put together a [fix for this](https://github.com/jcfisher/broom/tree/fix-issue-765), but it may not be the most robust.  For example, it breaks when you do:

    surv_td <- survfit(Surv(stop - start, status) ~ interaction(sex, pcdx),
                   data = mgus1) %>%
      tidy()

What's the best way to move forward with it?

**Comment by jcfisher** [comment]
Nevermind, I think I sorted that issue out, and submitted a [pull request](https://github.com/tidymodels/broom/pull/770).  I'm a GitHub newbie, so hopefully I did it right!
