### ISSUE TITLE
lfe-tidier: add argument robust to tidy

### ISSUE THREAD

**Issue by kuriwaki** [tidymodels/broom#772]
`lfe::felm` objects can be printed showing robust/cluster SEs in the `lfe:::summary.felm` with the `robust = TRUE` option, but currently `tidy.felm` does not have that option. Could it be added as an argument so it simply passes through? 

I've tested it on a fork that I can PR (https://github.com/kuriwaki/broom).
``` r
library(lfe)
#> Loading required package: Matrix
library(broom)

# example from lfe::felm help page -----
x <- rnorm(1000)
x2 <- rnorm(length(x))

## individual and firm
id <- factor(sample(20,length(x),replace=TRUE))
firm <- factor(sample(13,length(x),replace=TRUE))

## effects for them
id.eff <- rnorm(nlevels(id))
firm.eff <- rnorm(nlevels(firm))

## left hand side
u <- rnorm(length(x))
y <- x + 0.5*x2 + id.eff[id] + firm.eff[firm] + u

## estimate and print result
est1 <- felm(y ~ x+x2 | id + firm)  # no clusters
est2 <- felm(y ~ x+x2 | id + firm | 0 | id + firm) # cluster SEs


# PROPOSED behavior----
# different SEs depending on the robust option
tidy(est1, robust = FALSE)
#> # A tibble: 2 x 5
#>   term  estimate std.error statistic   p.value
#>   <chr>    <dbl>     <dbl>     <dbl>     <dbl>
#> 1 x        1.00     0.0332      30.2 8.60e-142
#> 2 x2       0.525    0.0324      16.2 2.01e- 52
tidy(est1, robust = TRUE)
#> # A tibble: 2 x 5
#>   term  estimate std.error statistic   p.value
#>   <chr>    <dbl>     <dbl>     <dbl>     <dbl>
#> 1 x        1.00     0.0329      30.5 8.87e-144
#> 2 x2       0.525    0.0325      16.1 4.94e- 52

# robust = TRUE turns on cluster SEs when those are specified
tidy(est2, robust = FALSE)
#> # A tibble: 2 x 5
#>   term  estimate std.error statistic   p.value
#>   <chr>    <dbl>     <dbl>     <dbl>     <dbl>
#> 1 x        1.00     0.0332      30.2 8.60e-142
#> 2 x2       0.525    0.0324      16.2 2.01e- 52
tidy(est2, robust = TRUE)
#> # A tibble: 2 x 5
#>   term  estimate std.error statistic   p.value
#>   <chr>    <dbl>     <dbl>     <dbl>     <dbl>
#> 1 x        1.00     0.0292      34.3 1.74e-169
#> 2 x2       0.525    0.0377      13.9 3.21e- 40
```

<sup>Created on 2019-10-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kuriwaki** [comment]
I forgot to account for the fact that the default value for `robust` is

``` r
args(lfe:::summary.felm)
#> function (object, ..., robust = !is.null(object$clustervar) || 
#>     getOption("lfe.robust"), lhs = NULL) 
#> NULL
```

<sup>Created on 2020-02-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

which means that it will be `TRUE` when there is clustering. I will make a new PR to fix that and let that supercede; otherwise the default behavior of summary.felm is always to set `robust = FALSE`.

**Comment by eweisbrod** [comment]
It would be great if this was the default value in broom.  I just ran into this issue and your issue/comments were really helpful.  Right now I pass through the robust=TRUE argument but it would be great if clustered SE were passed by default. Thanks! 


> I forgot to account for the fact that the default value for `robust` is
> 
> ```r
> args(lfe:::summary.felm)
> #> function (object, ..., robust = !is.null(object$clustervar) || 
> #>     getOption("lfe.robust"), lhs = NULL) 
> #> NULL
> ```
> 
> Created on 2020-02-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)
> 
> which means that it will be `TRUE` when there is clustering. I will make a new PR to fix that and let that supercede; otherwise the default behavior of summary.felm is always to set `robust = FALSE`.

**Comment by kuriwaki** [comment]
Will try to complete the PR #818  this week.
