### ISSUE TITLE
Clarify studentized vs standardized residuals in augment.lm()

### ISSUE THREAD

**Issue by aloy** [tidymodels/broom#780]
For `lm` objects, could you add a `type.residuals` argument to allow for studentized residuals to be requested?

**Comment by alexpghayes** [comment]
At the moment, if you (1) do not pass anything to `newdata`, the `.std.resid` column gives studentized residuals, rather than standardized residuals. We should probably document this better, and possibly allow users to get standardized residuals as well.

**Comment by aloy** [comment]
Thanks! I agree that making this explicit in the documentation will fix this confusion point.
