### ISSUE TITLE
Improve documentation about definition of residual

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#802]
See #778

**Comment by alexpghayes** [comment]
This documentation actually lives in `modeltests`, but apart from that anyone can write it!

**Comment by alexpghayes** [comment]
tfw when the internet tells you you're wrong https://twitter.com/carlislerainey/status/1205561665007341569

@carlislerainey i think https://twitter.com/CookieSci/status/1205653889321713669 is a good point and in light of this i'm happy to reconsider #778 

it may take some effort to make sure this definition gets applied consistently across all augment methods

**Comment by quangnguyen1995** [comment]
Hi! I was wondering if I can submit a PR and tackle this issue as a beginner. I'm confused about what to do though, since it seems now the task is to apply the new `y - yhat` definition for residuals?
