### ISSUE TITLE
Use as_tibble() instead of fix_data_frame()

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#806]
It's hard to understand `fix_data_frame()` relative to `as_tibble()`.

**Comment by IndrajeetPatil** [comment]
Is `fix_data_frame()` not being exported anymore? I can no longer use `broom.mixed`.

This is what I get with commit 3c922d5. 

```r
> library(broom.mixed)

Error: package or namespace load failed for ‘broom.mixed’:
 object ‘fix_data_frame’ is not exported by 'namespace:broom'

> traceback()
6: stop(msg, call. = FALSE, domain = NA)
5: value[[3L]](cond)
4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
3: tryCatchList(expr, classes, parentenv, handlers)
2: tryCatch({
       attr(package, "LibPath") <- which.lib.loc
       ns <- loadNamespace(package, lib.loc)
       env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)
   }, error = function(e) {
       P <- if (!is.null(cc <- conditionCall(e))) 
           paste(" in", deparse(cc)[1L])
       else ""
       msg <- gettextf("package or namespace load failed for %s%s:\n %s", 
           sQuote(package), P, conditionMessage(e))
       if (logical.return) 
           message(paste("Error:", msg), domain = NA)
       else stop(msg, call. = FALSE, domain = NA)
   })
1: library(broom.mixed)
```

**Comment by IndrajeetPatil** [comment]
I see that this function was removed in f34d12c, but I still the function being exported in `NAMESPACE` file, so not sure what's going on.  

Tagging also @bbolker in case `broom.mixed` needs to have an internal copy of `fix_data_frame` in the future release since that function will no longer be exported from `broom`.

**Comment by alexpghayes** [comment]
`fix_data_frame()` was not removed in f34d12c, but I did recently stop exporting it. That was meant to be an internal helper function and it was only exported by accident. If `broom.mixed` needs `fix_data_frame()`, definitely copy that code over. I'm also planning to remove `augment_columns()`.

Again, these are primarily maintainability changes, as `fix_data_frame()` and `augment_columns()` get called in dozens of places and have lots of hidden edge case in their error handling that makes them difficult to reason about.

**Comment by IndrajeetPatil** [comment]
Yeah, by _removed_ I meant removed from exported functions.

**Comment by bbolker** [comment]
about to go in and try to fix this stuff.  Trying to brush up on what `fix_data_frame` actually does. Other than the error-checking, I think this is equivalent?

```
fix_data_frame <- function(data, newnames=NULL, newcol=".rownames") {
    df <- as_tibble(data)
    if (!is.null(newnames)) df <- setNames(df,newnames)
    if (has_rownames(df)) df <- df %>%
                              rownames_to_column(var=newcol)
    return(df)
}
```

**Comment by alexpghayes** [comment]
I think so. There are some weird idioms in how it gets called to allow `data` to have varying numbers of columns.

**Comment by bbolker** [comment]
and ...  what are you doing in general to replace `augment_columns`?  The easy thing to do would be for me to copy the code over, but if you have better practices now ...

**Comment by alexpghayes** [comment]
That is a work in progress and won't be done for quite a while. I haven't figured out exactly the new plan, I just know that the maintenance burden for `augment_columns()` is currently too high.

**Comment by bbolker** [comment]
OK.  I think I've got `broom.mixed` passing tests with the current devel version of `broom`, so I'm going to stop for now (there's a huge amount of refactoring that *could* be done, but it's not a priority right now ...) [@IndrajeetPatil  , feel free to check/confirm and re-open if necessary ...]

**Comment by bbolker** [comment]
FWIW this is my new internal code:

```
has_rownames <- function(df) {
  return (!tibble::is_tibble(df) &&
          any(rownames(df) != as.character(seq(nrow(df)))))
}

## previously from broom                                                                                                     
## converts to tibble, optionally                                                                                            
fix_data_frame <- function(df, newnames=NULL, newcol=".rownames") {
    df <- as.data.frame(df)
    if (!is.null(newnames)) df <- setNames(df,newnames)
    if (has_rownames(df)) df <- df %>%
                              rownames_to_column(var=newcol)
    df <- as_tibble(df) ## must happen **AFTER** converting rownames                                                         
    return(df)
}
```
