### ISSUE TITLE
Incorrect v0.5.3 tag name

### ISSUE THREAD

**Issue by QuLogic** [tidymodels/broom#808]
The [0.5.3 release](https://github.com/tidymodels/broom/releases/tag/f3d37ecb6) is currently on a tag named `f3d37ecb6` instead of `v0.5.3` like the rest.

**Comment by simonpcouch** [comment]
Thanks for catching this @QuLogic! Just cleaned up the release tags.

**Comment by QuLogic** [comment]
BTW, 0.5.4 and 0.5.6 have an extra dot in the tag name: `v.0.5.4` vs `v0.5.4`.
