### ISSUE TITLE
Error messages instead of output in documentation

### ISSUE THREAD

**Issue by gershomtripp** [tidymodels/broom#809]
Looking at the PAM documentation [here](https://broom.tidyverse.org/reference/tidy.pam.html) it looks like there was an issue in the original Rmarkdown. There are error messages instead of the expected output.

<img width="687" alt="grafik" src="https://user-images.githubusercontent.com/20071483/72660949-0e5cc700-39d5-11ea-8d5f-4a2cedd775c3.png">

**Comment by gershomtripp** [comment]
It looks like there is no method for pam currently, despite being in the online documentation.

**Comment by simonpcouch** [comment]
Hi there @gershomtripp! I've just fixed the `pkgdown` build, so the site should be good to go.🙂

The documentation on the site reflects the developmental version of the package. If you're interested in using the pam tidiers, you can install the developmental version of broom with:

```
install.packages("devtools")
devtools::install_github("tidymodels/broom")
```
