### ISSUE TITLE
broom::glance and broom::augment does not work after the fit

### ISSUE THREAD

**Issue by economer** [tidymodels/broom#811]
## The problem

I'm having trouble with creating broom:: glance and broom:: augment after fitting a linear model. I can only get the broom::tidy.

**Comment by topepo** [comment]
Originally sent to `tune` repo. Without more information (like a `reprex`), this sounds like a pure `broom` issue.

**Comment by bbolker** [comment]
This issue definitely needs a reproducible example (e.g. see the [reprex package](https://github.com/tidyverse/reprex)).  The trivial example shown below works fine in the current version of broom (0.5.4).

```
library(broom)
dd <- data.frame(x=1:10, y =1:10)
m <- lm(y~x, dd)
glance(m)
augment(m)
```
