### ISSUE TITLE
Broom support for Fixed effect Logit

### ISSUE THREAD

**Issue by petrhrobar** [tidymodels/broom#813]
Hi,

I think it would be cool to add ```broom``` package support for fixed effect logit model from ```broom``` package.

Example is here:
```
library(bife)
dataset <- psid

logit <- glm(LFP ~ I(AGE^2) + log(INCH) + KID1 + KID2 + KID3 + factor(TIME), data = dataset, family = "binomial")
mod <- bife(LFP ~ I(AGE^2) + log(INCH) + KID1 + KID2 + KID3 + factor(TIME) | ID, dataset)

summary(logit)
summary(mod)

broom::augment(mod)
```

**Comment by simonpcouch** [comment]
Thanks for the issue! We’ve decided that, in general, we won’t be adding new tidier methods to broom after the upcoming 0.7.0 release in favor of asking the model-owning package (in this case, `bife`) to write and export the tidiers. We’ve written [some documentation](https://www.tidymodels.org/learn/develop/broom/) on how to make this happen and have also provided a much lighter-weight dependency than broom, `r-lib/generics`, to supply the tidier generics. We'll keep that tidymodels.org article linked above up to date with current resources to help in the process.🙂
