### ISSUE TITLE
Including number of observations used to build the model

### ISSUE THREAD

**Issue by mschubert** [tidymodels/broom#82]
I think it would be useful if some version of the `data.frame` that represents the result also include a column with the number of observations that were used to build the model.

An easy way to access would be using e.g. `nobs()` for `stats::lm()`, but I'm sure other models have similar reporting of this.

It would be even more useful if it could include the actual number of observations for `logicalTRUE` or `factorLEVEL`.

**Comment by grasshoppermouse** [comment]
I also think it would be useful if glance output included nobs. It looks like glance.stanreg already does:

https://github.com/dgrtwo/broom/blob/master/R/rstanarm_tidiers.R

**Comment by hughjonesd** [comment]
Just adding my vote to this feature. I think in most fields, it is standard to report the N as one of the summary statistics.

**Comment by randomgambit** [comment]
hello there! is there a fix for that very important feature?
thanks!!

**Comment by alexpghayes** [comment]
I'd be willing to this in a tryCatch to `finish_glance` to pick up an `n` column for relevant models. The question then is how many models actually implement `nobs()` methods.

I'm hesitant to report counts for each factor level in `glance()` because this is moving more into data summarizing than properties of a model. If a `tidy()` method doesn't already inherit this information from `summary()` or whatnot I don't think it's worth the effort to try implement this consistently across tidiers. Also, `skimr::skim()` is fantastic for this sort of thing.

**Comment by vincentarelbundock** [comment]
@alexpghayes One possible design that I would be willing to implement:

For each element of the list above which are *not* compatible with `nobs`, extract the value explicitly in the model-specific glance function.

Modify the `finish_glance` function. If `'n' %in% names(ret)`, then `tryCatch(stats::nobs)`

This is a bit more work (which I am willing to do), but it's explicit, and would avoid unexpected side effects from having a bunch of ifelse statements.

**Comment by vincentarelbundock** [comment]
See https://github.com/tidymodels/broom/pull/594

**Comment by gavinsimpson** [comment]
Sounds simpler to just implement `nobs()` methods for these internally, where they don't exist. Ideally these would be offered upstream to the respective package maintainers, but there's nothing stopping these being in broom if they are not wanted or maintainers are unresponsive. Using `nobs()` makes it simpler/safer to implement return of number of observations in `glance`.

**Comment by vincentarelbundock** [comment]
Sure. I'm happy to write a bunch of `nobs` methods if people find those useful. There's also a discussion about how these methods would be used in my WIP PR: https://github.com/tidymodels/broom/pull/594

Basically,

1. Each `glance` function call its own `nobs()`
2. `finish_glance` calls `nobs()` for all of them, as it currently does for `AIC`, `BIC`, etc.

**Comment by vincentarelbundock** [comment]
I'm in the process of checking every model object for which `broom` offers a `glance` function to see if they work with `stats::nobs`. I'm also write new methods for those that don't. The results are collected in this Gist:

https://gist.github.com/vincentarelbundock/24bedac98499181790aab230cc5b74bc

**Comment by alexpghayes** [comment]
Closed in #597! Thanks @vincentarelbundock!
