### ISSUE TITLE
Modernize vignettes

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#831]
They should probably conform to tidyverse best current practices but do not. Note that `message = FALSE` and `warning = FALSE` currently hide lots of warning messages.

**Comment by alexpghayes** [comment]
Side note: the vignettes currently have `message = FALSE` and `warning = FALSE` in `knitr::set_check_options()`, so a lot of the gentle syntax deprecation warnings won't show up at the moment. I would re-activate these warnings and double check for outdated syntax!

**Comment by simonpcouch** [comment]
Ahhh, gotcha. Will come back to this tomorrow!
