### ISSUE TITLE
Request to include class "Match" objects

### ISSUE THREAD

**Issue by dsself** [tidymodels/broom#84]
First off thank you for this package. I'm using quite frequently. 

I'm currently working on paper where I use the Matching package to do some Genetic Matching. The output is an object that I am unable to coerce to a data frame limiting my ability to even something simple like report the findings in a table. 

https://cran.r-project.org/web/packages/Matching/Matching.pdf

**Comment by dsself** [comment]
I think it would be as easy as this

with(mgen1,
 as.data.table(data.frame(Estimate = est, `AI SE` = se, `T-stat` = est/se, p.val = (1 - pnorm(abs(est/se))) *
             2))
)

**Comment by alexpghayes** [comment]
I know it's been a long long time, but would you be willing to write up a PR for this? I don't know what information would be most useful to include in the tidy output since I don't do any matching in my day to day.
