### ISSUE TITLE
transition away from scoped dplyr verbs

### ISSUE THREAD

**Issue by simonpcouch** [tidymodels/broom#853]
A reminder, re: #852 , to transition from scoped dplyr verbs to `across()` and `where()` once dplyr 1.0.0+ is on CRAN and more widely adopted.

**Comment by vincentarelbundock** [comment]
@simonpcouch In your opinion, is it too early to start work on this?

**Comment by simonpcouch** [comment]
@vincentarelbundock I think a few more months until I'd give this a go, yeah. 

Also, all of your high quality work within this last day or so is much appreciated! Amazed by how much work you've put in. Trying to work my way through your PRs this morning.

**Comment by vincentarelbundock** [comment]
that's what happens when my todo list is full of stuff I hate to do ;)
