### ISSUE TITLE
Error: No tidy method for objects of class pam

### ISSUE THREAD

**Issue by Laura-O** [tidymodels/broom#859]
Although it's mentioned in the [documentation](https://broom.tidymodels.org/reference/tidy.pam.html), using augment/glance/tidy with the output of `cluster::pam` gives this error:
`Error: No tidy method for objects of class pam`

Minimal example:
```r
library(cluster)
library(broom)

iris.pam <- iris %>%
  select(-Species) %>%
  pam(k=3)

tidy(iris.pam)
```

**Comment by simonpcouch** [comment]
Hi there @Laura-O! The documentation currently on https://broom.tidymodels.org/ reflects a development version of the package—we'll be adding `pam` tidiers to the next CRAN release. If you're interested in using the new `pam` tidiers, I'd recommend installing the development version.🌼

```
# if you don't yet have `devtools` installed
# install.packages("devtools")

library(devtools)
install_github("tidymodels/broom")
```
