### ISSUE TITLE
`object 'fstatistic' not found` when model contains intercept only

### ISSUE THREAD

**Issue by stefvanbuuren** [tidymodels/broom#865]
In trying to solve <https://github.com/stefvanbuuren/mice/issues/237> I found that `broom 0.7.0.9000` produces an expected result when the model contains only an intercept.

```r
library(broom)

# normal operation
fit1 <- lm(mpg ~ disp, data = mtcars)
glance(fit1)

# intercept only throws error: Error in eval_tidy(xs[[j]], mask) : object 'fstatistic' not found
fit0 <- lm(mpg ~ 1, data = mtcars)
glance(fit0)
```

Is this normal behaviour?

**Comment by simonpcouch** [comment]
Thanks for the issue! This shouldn't be the case, no. Will get started on a fix and update tests to check for this in the future.
