### ISSUE TITLE
Error: No tidy method for objects of class logitmfx

### ISSUE THREAD

**Issue by grantmcdermott** [tidymodels/broom#873]
My recently merged PR (https://github.com/tidymodels/broom/pull/756) provides tidy methods for the **mfx** package. This worked fine on my local machine and also seemed to passed all tests during CI. 

However, I just tried to run the dev version and ran into an unexpected error. The tidy methods don't appear to be recognized even though they are present (albeit hidden) in the broom NAMESPACE. Any ideas?

---

``` r
## Just to prove the I'm using the latest broom version
devtools::install_github("tidymodels/broom")
#> Using github PAT from envvar GITHUB_PAT
#> Skipping install of 'broom' from a github remote, the SHA1 (04070a27) has not changed since last install.
#>   Use `force = TRUE` to force installation

## Libs
library(broom)
library(mfx)
#> Loading required package: sandwich
#> Loading required package: lmtest
#> Loading required package: zoo
#> 
#> Attaching package: 'zoo'
#> The following objects are masked from 'package:base':
#> 
#>     as.Date, as.Date.numeric
#> Loading required package: MASS
#> Loading required package: betareg

## Simple logit regression 
mod_logmfx <- logitmfx(am ~ cyl + hp + wt, atmean = TRUE, data = mtcars)

## Tidy results (doesn't work!)
tidy(mod_logmfx)
#> Error: No tidy method for objects of class logitmfx

## Check that the tidiers are actually there (i.e. in the NAMESPACE)
broom:::tidy.logitmfx
#> function (x, conf.int = FALSE, conf.level = 0.95, ...) 
#> {
#>     x_tidy <- as_tibble(x$mfxest, rownames = "term")
#>     colnames(x_tidy) <- c("term", "estimate", "std.error", "statistic", 
#>         "p.value")
#>     if (!grepl("atmean", format(c(x$call)))) {
#>         x_tidy$atmean <- TRUE
#>     }
#>     else {
#>         x_tidy$atmean <- as.logical(gsub(".*atmean = |,.*|).*", 
#>             "", format(c(x$call))))
#>     }
#>     if (conf.int) {
#>         x_tidy <- x_tidy %>% dplyr::mutate(conf.low = estimate - 
#>             qt(1 - (1 - conf.level)/2, df = x$fit$df.residual) * 
#>                 std.error, conf.high = estimate + qt(1 - (1 - 
#>             conf.level)/2, df = x$fit$df.residual) * std.error)
#>     }
#>     dplyr::select(x_tidy, term, contains("atmean"), everything())
#> }
#> <bytecode: 0x5654345df148>
#> <environment: namespace:broom>
```

<sup>Created on 2020-06-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by simonpcouch** [comment]
Hmm.. I'm having trouble reproducing this error. Some of the builds on `master` are failing right now—was your `install_github()` attempt successful? i.e. what would that same reprex with `devtools::install_github("tidymodels/broom", force= TRUE)` look like?

**Comment by grantmcdermott** [comment]
Thanks for checking. Still running into the same error, regardless of whether I use `force = TRUE`. I thought it might be something particular to my system (maybe some weird with my CCACHE??). But I just tried in two fresh environments &mdash; a Docker container and a GCE cloud instance &mdash; and they both returned the same error.

My local session info fwiw.

``` r
sessionInfo()
#> R version 4.0.0 (2020-04-24)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Arch Linux
#> 
#> Matrix products: default
#> BLAS/LAPACK: /usr/lib/libopenblas_haswellp-r0.3.9.so
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] mfx_1.2-2        betareg_3.1-3    MASS_7.3-51.6    lmtest_0.9-37   
#> [5] zoo_1.8-8        sandwich_2.5-1   broom_0.7.0.9000
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.4.6      pillar_1.4.4      compiler_4.0.0    highr_0.8        
#>  [5] tools_4.0.0       digest_0.6.25     evaluate_0.14     lifecycle_0.2.0  
#>  [9] tibble_3.0.1      lattice_0.20-41   pkgconfig_2.0.3   rlang_0.4.6      
#> [13] yaml_2.2.1        xfun_0.14         dplyr_1.0.0       stringr_1.4.0    
#> [17] knitr_1.28        generics_0.0.2    vctrs_0.3.1       nnet_7.3-14      
#> [21] stats4_4.0.0      grid_4.0.0        tidyselect_1.1.0  glue_1.4.1       
#> [25] R6_2.4.1          flexmix_2.3-15    rmarkdown_2.2     Formula_1.2-3    
#> [29] purrr_0.3.4       tidyr_1.1.0       magrittr_1.5      backports_1.1.7  
#> [33] ellipsis_0.3.1    htmltools_0.4.0   modeltools_0.2-23 stringi_1.4.6    
#> [37] crayon_1.3.4
```

**Comment by grantmcdermott** [comment]
I should add that `tidy.betamfx` at least works for me. So it's just the other set of **mfx** tidiers. 

That might actually be a clue, because I separated the `mfx::betamfx` tidiers from the other **mfx** tidiers for reasons described [here](https://github.com/tidymodels/broom/pull/756#issuecomment-565738765)... At the same time, they're all calling exactly the same `tidy.mfx` function under the hood (see [here](https://github.com/tidymodels/broom/blob/master/R/mfx-tidiers.R#L84-L95) and [here](https://github.com/tidymodels/broom/blob/master/R/mfx-tidiers.R#L233)). 

Sorry to dump more links on you, but I'm truly stumped!

**Comment by simonpcouch** [comment]
Pretty stumped on this as well—the tidiers worked fine for me locally and are passing unit tests currently. Have you come across this before, @alexpghayes? Any ideas?

**Comment by vincentarelbundock** [comment]
Probably a naive question, but shouldn't you `@export` the methods here?

https://github.com/tidymodels/broom/blob/master/R/mfx-tidiers.R#L86

**Comment by simonpcouch** [comment]
Welp.. I feel like a goofball.😆 Thanks, @vincentarelbundock!

This is now fixed on the release candidate branch!

**Comment by grantmcdermott** [comment]
> Welp.. I feel like a goofball

OMG tell me about it. (You know when you stare at something long enough that it stops making sense...)

Sorry to waste your time with  this @simonpcouch and thanks @vincentarelbundock!

**Comment by jennybigman** [comment]
Hi,

I am now having this issue:

for example, 

tidy(brmsfit object) %>% slice(1:3) %>% mutate_if(is.double, round, digits = 2) 
"Error: No tidy method for objects of class brmsfit"

I tried reinstalling broom, tidyverse, & using the code above (devtools::install_github("tidymodels/broom", force= TRUE)), but no luck. 

I have also tried using broom.mixed, but get a different error (Error: The model does not contain group-level effects.).

If anyone can help, that'd be great. Thanks!

**Comment by vincentarelbundock** [comment]
As far as I know, `brmsfit` objects are not supported by `broom`, which is what this first message tells you. Therefore, if you want to raise this issue, I would do it on the `broom.mixed` github issues tracker.

To make that new issue more useful, and to increase your chances of getting a constructive response, I would prepare a [Minimal Reproducible Example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example).

Also try to investigate that error message: "Error: The model does not contain group-level effects." Should the model have group-level effects? Look here to figure out which part of the `tidy` function produces this error message when applied to your object:

https://github.com/bbolker/broom.mixed/blob/master/R/brms_tidiers.R#L102

**Comment by grantmcdermott** [comment]
@jennybigman I'm not sure why you are filing under this issue. 

Regardless, I'm pretty sure you want broom.mixed. I'd file about your second error message there. https://github.com/bbolker/broom.mixed/issues

**Comment by jennybigman** [comment]
Thanks all, I will file under brooms.mixed.

I did not have this problem previously (using broom with brmsfit) and the above was the same issue as I've found, so thought this was the place. 

Thanks again.

**Comment by grantmcdermott** [comment]
No, worries: Just making sure I wasn't confused. Good luck!
