### ISSUE TITLE
When will 0.7.0 be on CRAN

### ISSUE THREAD

**Issue by dmenne** [tidymodels/broom#874]
Any plans when 0.7 will be on CRAN? I have made my package dependent on it, but not uploded it, but now I am forced to do so because of a change in policy:  https://cran.r-project.org/web/checks/check_results_breathtestcore.html

**Comment by simonpcouch** [comment]
Hey there @dmenne! We're hoping to send the new version off ASAP (end of the business week, perhaps), but we can't be sure how fast the package will make it through the review process. I'll drop a note here when it's accepted!

**Comment by simonpcouch** [comment]
Hey there! Thanks for your patience. 0.7.0 was accepted to CRAN today. :-)

**Comment by dmenne** [comment]
Congratulation, looks like it was hard work  My packages were removed from CRAN because I had made a minor revision contingent on broom too.
