### ISSUE TITLE
Release broom 0.7.0

### ISSUE THREAD

**Issue by topepo** [tidymodels/broom#876]
Prepare for release: 
 
* [x] `devtools::build_readme()` 
* [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_broom.html) 
* [x] `devtools::check(remote = TRUE, manual = TRUE)` 
* [x] `devtools::check_win_devel()` 
* [x] `rhub::check_for_cran()` 
* [x] `revdepcheck::revdep_check(num_workers = 4)` 
* [x] Update `cran-comments.md` 
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release) 
* [x] Review pkgdown reference index for, e.g., missing topics 
* [x] Draft blog post 
 
Submit to CRAN: 
 
* [x] `usethis::use_version('minor')` 
* [x] `devtools::submit_cran()` 
* [x] Approve email 
 
Wait for CRAN... 
 
* [x] Accepted :tada: 
* [x] `usethis::use_github_release()` 
* [x] `usethis::use_dev_version()` 
* [ ] Finish blog post 
* [ ] Tweet 
* [ ] Add link to blog post in pkgdown news menu

**Comment by simonpcouch** [comment]
Release candidate on the `0.7.0-rc` branch!

**Comment by alexpghayes** [comment]
I'd like to be involved in writing the blog post for this release; I have some comments on both design choices + maintenance that I'd like to make. Has that started? If so, can I get a link?

**Comment by simonpcouch** [comment]
I'll be PRing to tidyverse.org here in a sec and will cc you!

**Comment by IndrajeetPatil** [comment]
@simonpcouch Trying to schedule a few personal package releases with this release in mind, and so was wondering if this version has been submitted to `CRAN` and if it is currently under review?

**Comment by simonpcouch** [comment]
@IndrajeetPatil Currently in submission, yes!

**Comment by simonpcouch** [comment]
Round 3 of revdepchecks, at CRAN's request, on #885.
