### ISSUE TITLE
reverse dependency checks for 0.7.0, round 3

### ISSUE THREAD

**Issue by simonpcouch** [tidymodels/broom#885]
Another round of reverse dependency checks for broom 0.7.0 (on the `0.7.0-rc` branch)—since the first round of checks in #862, 19 of 37 contacted maintainers have updated their packages on CRAN, and we've also softened some deprecations since round 2 of revdepchecks, at the CRAN team's request, resulting in 3 prior failures being remedied. I'll keep this table up to date as I check in on each of these issues.

## New problems (20)

|package                                   |version |ERROR  |WARNING |NOTE     |additional notes    |
|:-----------------------------------------|:-------|:------|:-------|:--------|:--------|
|[allestimates](problems.md#allestimates)  |0.1.6   |__+1__ |        |1        | (Same issue as before—changes to `conf.int` defaults.) Not hosted on GitHub, so reached out to the maintainer by email again. |
|[arsenal](problems.md#arsenal)            |3.4.0   |__+1__ |        |         | Fixed on the devel `master`branch a month ago—waiting to submit until 0.7.0 is posted. |
|[CGPfunctions](problems.md#cgpfunctions)  |0.6.1   |__+1__ |        |         | Same issue as before—changes to supplied columns in `tidy.aov`.) Dropped a note in the issue from the first round of checks. |
|[chest](problems.md#chest)                |0.3.1   |__+1__ |        |1        | Same issue as before. Fixed on the devel branch `master`, and will be submitted once broom is on CRAN. |
|[ERSA](problems.md#ersa)                  |0.1.1   |__+1__ |        |         | Same issue as before—no response on the initial GitHub issue, just dropped another note. |
|[eyetrackingR](problems.md#eyetrackingr)  |0.1.8   |__+2__ |        |         | Same issue as before. Still no longer maintained. |
|[forestmodel](problems.md#forestmodel)    |0.5.0   |__+1__ |        |         | Same issue as before. Checked in on the issue from the first round of checks. |
|[ggasym](problems.md#ggasym)              |0.1.4   |__+1__ |        |         | Same issue as before—Results from warning -> error switch (unit tests reflected broom functionality). Fixed 25 days ago on the devel branch, will be submitted to CRAN once broom is released. |
|[glmmfields](problems.md#glmmfields)      |0.1.3   |       |        |1 __+1__ | Same issue as before—results from planned deprecation of mixed model tidiers to `broom.mixed`. Fixed 28 days ago on the devel branch and will be submitted to CRAN once broom is released. |
|[konfound](problems.md#konfound)          |0.2.1   |__+2__ |        |1        | Same issue as before—results from planned deprecation of mixed model tidiers to `broom.mixed`. No response on the issue filed a month ago, just checked in again. |
|[mice](problems.md#mice)                  |3.9.0   |__+1__ |        |         | Same issue as before—relevant to changes in glance.*() methods for lm and aov objects. Fixed 25 days ago and on its way to CRAN. |
|[moderndive](problems.md#moderndive)      |0.4.0   |__+1__ |        |1        | Same issue as before, fixed on `master` branch. |
|[nlstimedist](problems.md#nlstimedist)    |1.1.4   |__+1__ |        |         | Same issue as before, fixed on `master` branch. |
|[radiant.model](problems.md#radiantmodel) |1.3.10  |__+1__ |        |         | Maintainer has noted that they will submit the necessary changes as soon as the new version of broom hits CRAN—the relevant breakages are due to the change in how degrees of freedom are supported, so a workaround for supporting both versions would be messy. |
|[RCT](problems.md#rct)                    |1.0.2   |__+2__ |        |         | Same issue as before. Checking in on the initial issue.  |
|[survminer](problems.md#survminer)        |0.4.7   |__+1__ |        |1        | Unrelated to broom and addressed on issue 472 of the package. |
|[survutils](problems.md#survutils)        |1.0.2   |__+1__ |        |         | Same issue as before—related to changes in `conf.int` defaults. Checked in on the issue filed a month ago. |

Update 24 June 2020—just worked through each of these issues. Of the 17 remaining issues, 9 of them have been fixed in development versions and are waiting on the release of 0.7.0 to submit. I've reached out to maintainers for all remaining issues, besides `eyetrackingR` which currently does not have a maintainer.

**Comment by vnijs** [comment]
FYI I will update radiant.model as soon as the new version of broom hits and make 0.7.0 required. With the changes in how dfs are reported by broom for logistic regression it would be a bit of a mess to support multiple versions.

**Comment by simonpcouch** [comment]
@vnijs Sounds great, thanks! Will make note of that. :-)
