### ISSUE TITLE
coxph with frailty models fails when conf.int=TRUE

### ISSUE THREAD

**Issue by matthieu-faron** [tidymodels/broom#899]
Hi, thank you for the great work on the broom package

I'am using CRAN broom 0.7.0

I'am triyng a coxph model with a frailty term. When using tidy without conf.int = TRUE, everything works properly 

```r
library(survival)
library(broom)

model <- coxph(Surv(time, status) ~ age + sex + frailty(inst), lung)
tidy(model, conf.int = FALSE)
```

But when using conf.int = TRUE, it returns an errors 
```r
model <- coxph(Surv(time, status) ~ age + sex + frailty(inst), lung)
tidy(model, conf.int = TRUE)
```

Note that if your coxphmodel only has one variable, the confidence interval will recycle when the function binds the conf int with the coefficients.
```r
model <- coxph(Surv(time, status) ~ age + frailty(inst), lung)
tidy(model, conf.int = TRUE)
```

I guess the conf.int should be [NA-NA] for the frailty term ?
I may be able to contribute a solution but I'am not very used to github...
Kind regards

**Comment by simonpcouch** [comment]
Thanks for catching this!

This fix would probably need to address any of the penalty functions (`ridge()`, `pspline()`, and `frailty()`, as far as I know) supplied by `coxph`.

Let me know what you think the best approach here is, @alexpghayes.

**Comment by alexpghayes** [comment]
I don't know enough about survival to answer this. We should find someone
who does.

**Comment by simonpcouch** [comment]
Closing in favor of #966! Thanks for yalls patience here. :-)
