### ISSUE TITLE
Glance method for geeglm objects fails with unstructured residuals

### ISSUE THREAD

**Issue by andrjohns** [tidymodels/broom#911]
---

I'm running into an issue where calling ```glance``` on ```geeglm``` objects with unstructured residual covariances no longer works:

``` r
library(geepack)
library(broom)
gee1 <- geeglm(Weight ~ Cu, data=dietox, id=Pig, family=gaussian(), corstr="unstructured")
out = glance(gee1)
#> Error: All elements must be size one, use `list()` to wrap.
#> x Element `alpha` is of size 66.
```

<sup>Created on 2020-08-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I've tested this with both the CRAN and github versions of ```broom```.

If I use the 'old' definition of the ```glance``` method, the code runs without issue:
``` r
library(geepack)
library(broom)
library(tidyverse)

glance.geeglm  <- function(x, ...) {
    s <- summary(x)
    tibble(
        df.residual = x$df.residual,
        n.clusters = length(s$clusz),
        max.cluster.size = max(s$clusz),
        alpha = x$geese$alpha,
        gamma = x$geese$gamma
    )
}

gee1 <- geeglm(Weight ~ Cu, data=dietox, id=Pig, family=gaussian(), corstr="unstructured")
out = glance(gee1)

head(out)
#> # A tibble: 6 x 5
#>   df.residual n.clusters max.cluster.size  alpha gamma
#>         <int>      <int>            <int>  <dbl> <dbl>
#> 1         858         72               12  1.77   622.
#> 2         858         72               12  1.43   622.
#> 3         858         72               12  1.07   622.
#> 4         858         72               12  0.692  622.
#> 5         858         72               12  0.322  622.
#> 6         858         72               12 -0.114  622.
```

<sup>Created on 2020-08-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by simonpcouch** [comment]
Hmm... thanks for pointing this out! I'm seeing the same error on the main development branch and 0.7.0, as well as the same output with 0.5.6.

I'm not sure the old output is "correct", as the output of `glance()` methods should always be a one-row tibble.

Thoughts on the best form for this output to take? Is there precedent for similar situations @alexpghayes? The `alpha` entry (in `x$geese$alpha`) is usually 1-element, but is longer when `corstr="unstructured"`, resulting in the remaining columns being recycled.
