### ISSUE TITLE
tidy.lm "error on inappropriate subclassing" breaks my code - is stop() needed / could it be overruled by argument?

### ISSUE THREAD

**Issue by LukasWallrich** [tidymodels/broom#917]
In psychology research, I often need to compare and display standardised and non-standardised lm models side-by-side. Therefore, I have written a function that returns a standardised lm model, with two classes "lm" and "rN_std." I then use the second class to distinguish standardised and non-standardised models for reporting - however, I would like to use the broom tidiers on both, which worked fine in the spring.

When I now returned to this after a few months, the code doesn't work anymore because of the new error on inappropriate subclassing (#742). I am not sure what the history behind that error is, or whether I am abusing classes too grossly - but I wonder whether the error could be replaced by a warning or whether there could be an argument to ignore extra classes?

**Comment by alexpghayes** [comment]
We'll definitely keep the current design as is, but you can get around this by creating a `tidy.rN_std()` method like so:

``` r
tidy.rN_std <- tidy.lm

# the rest of your code here
```

Let me know if you have any followup questions!

**Comment by LukasWallrich** [comment]
Thanks, Alex. However, I don't quite understand this workaround.

Currently, my object has classes `[1] "lm"     "rN_std"` so that `tidy.lm` fails even after I add this new alias. I could switch the classes around in my function and then get the `rN_std` method to strip that class before calling `tidy.lm` with an lm-only object - is that what you would suggest?

Should I expect a similar error to be introduced into glance.lm etc in the future?
