### ISSUE TITLE
Unable to tidy a glm2 object using a log link

### ISSUE THREAD

**Issue by kristyrobledo** [tidymodels/broom#918]
Hi :) 
After fitting a glm2 model, with a log link rather than a logit link, I get an error asking for starting values and also receive additional warnings about the model being unable to converge (after it has already converged). 

> Error: no valid set of coefficients has been found: please supply starting values
> In addition: There were 23 warnings (use warnings() to see them)

Here is my reproducible example. I think this might be linked to a comment from this issue (#769) where Alex says something about glm2 not playing nicely with glm objects?

---

library(reprex)
library(tidyverse)
library(glm2)
library(broom)

data(iris)

##create an outcome
df <-iris %>%
  mutate(outcome = case_when(Petal.Width>2 ~1, 
                             TRUE ~0))

#go to glm2 to fit the model, but need starting values for this:
p0 <- sum(as.numeric(df$outcome))/length(as.numeric(df$outcome))
start.val <- c(log(p0),rep(0,2))

model<-glm2(outcome ~ Sepal.Length+Sepal.Width, data=df, 
    family = binomial(link="log"), 
    start = start.val)
#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence
#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

##get warnings, but converges
model$converged
#> [1] TRUE

##now tidy up and display model
tidy(model, conf.int=TRUE, exponentiate=TRUE)
#> Warning: step size truncated due to divergence
#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence
#> Warning: glm.fit: algorithm did not converge
#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence
#> Warning: glm.fit: algorithm did not converge
#> Error: no valid set of coefficients has been found: please supply starting values

#doesnt work? not sure why I am receiving errors now saying that the model hasnt converged?

class(model)
#> [1] "glm" "lm"

tidy(model, conf.int=TRUE, exponentiate=TRUE, start=start.val)
#> Warning: step size truncated due to divergence
#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence
#> Warning: glm.fit: algorithm did not converge
#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence
#> Warning: glm.fit: algorithm did not converge
#> Error: no valid set of coefficients has been found: please supply starting values
 
#doesnt recognise starting values that I gave it either ?

Created on 2020-08-26 by the reprex package (v0.3.0)
```

Hope this is clear - thanks :)

**Comment by simonpcouch** [comment]
Hi @kristyrobledo. Thanks for your patience and for the reprex.

Yeah, looks like `glm2` objects are especially tough to handle as they, in Alex's words, "hijack" the same class that `glm()` objects use—the output of `glm2()` has the same class as `glm()`, which makes S3 dispatch difficult.

A reprex with some style edits:

``` r
library(tidyverse)
library(glm2)
library(broom)

data(iris)

df <- iris %>%
  mutate(outcome = case_when(Petal.Width > 2 ~ 1,TRUE ~ 0))

p0 <- sum(as.numeric(df$outcome)) / length(as.numeric(df$outcome))
start_val <- c(log(p0), rep(0, 2))

model <- glm2(
  outcome ~ Sepal.Length + Sepal.Width, 
  data = df,
  family = binomial(link="log"),
  start = start_val
)
#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence
#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

#> Warning: step size truncated due to increasing deviance

# the issue -- glm2 objects use the same class
# as glm objects
class(model)
#> [1] "glm" "lm"

# coverged, despite warnings
model$converged
#> [1] TRUE

tidy(model, conf.int = TRUE, exponentiate = TRUE)
#> Warning: step size truncated due to divergence
#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence
#> Warning: glm.fit: algorithm did not converge
#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence

#> Warning: step size truncated due to divergence
#> Warning: glm.fit: algorithm did not converge
#> Error: no valid set of coefficients has been found: please supply starting values
```

<sup>Created on 2020-09-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

@alexpghayes, on #769 you wrote

> Another case of glm2 hijacking the glm class. Same fix as always.

Was that "same fix" disentangling `tidy.lm` from `tidy.glm`?

As a result of that S3 dispatch trickiness, and the fact that the tidiers still work sometimes on `glm2` output, broom has "unintentionally" supported some `glm2` output for some time. Not sure if there's precedent for handling this kind of situation in broom.

My initial thought is not to deprecate the functionality that has been "supported", though always issue a warning when the output is from `glm2()` that this functionality isn't maintained.

**Comment by alexpghayes** [comment]
Two comments:

1. The "usual fix" is to do something like `tidy.glm2 <- tidy.default` but in this case `glm2` does not return an object with `glm2` class, so this will not work. To make this work we would have to modify the `tidy.glm()` method. I am personally opposed to this, unless we can find a way to differentiate between `glm2::glm` objects and `stats::glm` objects, and then do some sort of internal dispatch to a `tidy_glm2_helper` or something like that.

2. It looks like there is model re-fitting happening when we request confidence intervals. My impression is that the solution here is to figure out when and why this happens and then to tighten convergence criteria or something like that.

**Comment by simonpcouch** [comment]
For now, implemented a helper that warns users that output isn't maintained when it's from glm2 rather than glm. Functionality that was previously (unintentionally) "supported" will continue to work as before (with the addition of the new warning). :-)

Again, thank you for bringing this to our attention @kristyrobledo!
