### ISSUE TITLE
ivreg tidiers

### ISSUE THREAD

**Issue by grantmcdermott** [tidymodels/broom#922]
The new [**ivreg**](https://john-d-fox.github.io/ivreg/index.html) package spins off the old `AER::ivreg()` methods into their own dedicated library.

The [existing](https://github.com/tidymodels/broom/blob/master/R/aer-tidiers.R) `ivreg()` tidiers all continue to work with the new package. But these should be separated from the other AER tidiers into their own file... especially since **ivreg** will become a dependency for **AER** in the next release (see [here](https://twitter.com/AchimZeileis/status/1301454613200154624)).

**Comment by grantmcdermott** [comment]
Just to add: This should mostly be a simple matter of copying across some lines to code, since the tests etc. are all in place. 

I'd probably just think about also adding the summary diagnostics (for the first-stage regression) to `ivreg.glance`, since this is important information that would normally get passed on to any regression table.

```r
    library(ivreg)

    m = ivreg(log(packs) ~ log(rprice) + log(rincome) | salestax + log(rincome), data = CigaretteDemand)

    summary(m)
    #> 
    #> Call:
    #> ivreg(formula = log(packs) ~ log(rprice) + log(rincome) | salestax + 
    #>     log(rincome), data = CigaretteDemand)
    #> 
    #> Residuals:
    #>       Min        1Q    Median        3Q       Max 
    #> -0.611000 -0.086072  0.009423  0.106912  0.393159 
    #> 
    #> Coefficients:
    #>              Estimate Std. Error t value Pr(>|t|)    
    #> (Intercept)    9.4307     1.3584   6.943 1.24e-08 ***
    #> log(rprice)   -1.1434     0.3595  -3.181  0.00266 ** 
    #> log(rincome)   0.2145     0.2686   0.799  0.42867    
    #> 
    #> Diagnostic tests:
    #>                  df1 df2 statistic  p-value    
    #> Weak instruments   1  45    45.158 2.65e-08 ***
    #> Wu-Hausman         1  44     1.102      0.3    
    #> Sargan             0  NA        NA       NA    
    #> ---
    #> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    #> 
    #> Residual standard error: 0.1896 on 45 degrees of freedom
    #> Multiple R-Squared: 0.4189,  Adjusted R-squared: 0.3931 
    #> Wald test: 6.534 on 2 and 45 DF,  p-value: 0.003227
    summary(m)$waldtest
    #> [1]  6.5336721  0.0032271  2.0000000 45.0000000
    summary(m)$diagnostics
    #>                  df1 df2 statistic      p-value
    #> Weak instruments   1  45 45.157769 2.654508e-08
    #> Wu-Hausman         1  44  1.102002 2.995590e-01
    #> Sargan             0  NA        NA           NA

    ## Glance method missing this info...
    library(broom)
    glance(m)
    #> # A tibble: 1 x 8
    #>   r.squared adj.r.squared sigma statistic p.value    df df.residual  nobs
    #>       <dbl>         <dbl> <dbl>     <dbl>   <dbl> <int>       <int> <int>
    #> 1     0.419         0.393 0.190      6.53 0.00323     3          45    48
```
<sup>Created on 2020-09-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by simonpcouch** [comment]
Thanks for bringing this up!

I don't quite see the argument for separating files / maintaining separate tidiers for `ivreg` and `AER` output—the only current `AER` functionality besides `ivreg` tidiers is an informative error for `tidy.tobit`. Because they share the same class, too, S3 dispatch would send model objects from either package to the same method. Definitely worth dropping in a comment that that class is shared by model objects from two packages, though!

I believe the summary diagnostics you mentioned are currently supported through the `diagnostics` argument for both output versions:

``` r
library(tidyverse)
library(broom)
library(AER)
#> Loading required package: car
#> Loading required package: carData
#> 
#> Attaching package: 'car'
#> The following object is masked from 'package:dplyr':
#> 
#>     recode
#> The following object is masked from 'package:purrr':
#> 
#>     some
#> Loading required package: lmtest
#> Loading required package: zoo
#> 
#> Attaching package: 'zoo'
#> The following objects are masked from 'package:base':
#> 
#>     as.Date, as.Date.numeric
#> Loading required package: sandwich
#> Loading required package: survival

data("CigarettesSW")

df <- CigarettesSW %>%
  mutate(
    rprice = price / cpi,
    rincome = income / population / cpi,
    tdiff = (taxs - tax) / cpi
  )

fit <- ivreg(
  log(packs) ~ log(rprice) + log(rincome) | log(rincome) + tdiff + I(tax / cpi),
  data = df, subset = year == "1995"
)

glance(fit, diagnostics = TRUE)
#> # A tibble: 1 x 12
#>   r.squared adj.r.squared sigma statistic p.value    df df.residual  nobs
#>       <dbl>         <dbl> <dbl>     <dbl>   <dbl> <int>       <int> <int>
#> 1     0.429         0.404 0.188      13.3 2.93e-5     3          45    48
#> # … with 4 more variables: statistic.Sargan <dbl>, p.value.Sargan <dbl>,
#> #   statistic.Wu.Hausman <dbl>, p.value.Wu.Hausman <dbl>

library(ivreg)
#> Registered S3 methods overwritten by 'ivreg':
#>   method              from
#>   anova.ivreg         AER 
#>   hatvalues.ivreg     AER 
#>   model.matrix.ivreg  AER 
#>   predict.ivreg       AER 
#>   print.ivreg         AER 
#>   print.summary.ivreg AER 
#>   summary.ivreg       AER 
#>   terms.ivreg         AER 
#>   update.ivreg        AER 
#>   vcov.ivreg          AER
#> 
#> Attaching package: 'ivreg'
#> The following objects are masked from 'package:AER':
#> 
#>     ivreg, ivreg.fit

fit <- ivreg(
  log(packs) ~ log(rprice) + log(rincome) | log(rincome) + tdiff + I(tax / cpi),
  data = df, subset = year == "1995"
)

glance(fit, diagnostics = TRUE)
#> # A tibble: 1 x 12
#>   r.squared adj.r.squared sigma statistic p.value    df df.residual  nobs
#>       <dbl>         <dbl> <dbl>     <dbl>   <dbl> <int>       <int> <int>
#> 1     0.429         0.404 0.188      13.3 2.93e-5     3          45    48
#> # … with 4 more variables: statistic.Sargan <dbl>, p.value.Sargan <dbl>,
#> #   statistic.Wu.Hausman <dbl>, p.value.Wu.Hausman <dbl>
```

<sup>Created on 2020-09-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Let me know if I'm missing anything here. :-)

**Comment by simonpcouch** [comment]
Agreed on both! Definitely much appreciated if you end up getting around to a PR re: 2. :-)

Will leave the issue open as a reminder to come back to this.

**Comment by grantmcdermott** [comment]
Hey Simon,

I've started digging into this and just a quick heads up that new package (API) does appear to introduce some breaking changes for the current tidy.ivreg methods. E.g. Just taking the simplest example from the new `ivreg()` docs.

```r
    library(ivreg)
    library(broom)

    m <- ivreg(log(packs) ~ log(rprice) + log(rincome) | salestax + log(rincome),
               data = CigaretteDemand)

    tidy(m, conf.int = TRUE, instruments = TRUE)
    #> Error: New columns must be compatible with `.data`.
    #> x New column has 2 rows.
    #> ℹ `.data` has 1 row.
```
<sup>Created on 2020-09-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

To be honest, the "instruments" argument for `tidy.ivreg` makes very little sense to me now that I look at it. The output is strange in of itself, even in cases where it works. (Why would you want to isolate the coefficient from second-stage instrumented variable; as opposed to the actual instruments from the first-stage? You never see that in a scientific publication.) 

As it stands, the new `ivreg()` method does offer support for extracting the first-stage elements. (See also https://github.com/john-d-fox/ivreg/issues/1.) So that's what I'll look to incorporate in the PR.

**Comment by simonpcouch** [comment]
I appreciate the thoroughness and your willingness to make those additions! Will keep an eye out for that PR.
