### ISSUE TITLE
Argument to pass additional summary functions to glance

### ISSUE THREAD

**Issue by bwiernik** [tidymodels/broom#926]
I'd sometimes like to add additional information to a `glance()` summary table, and it would be nice to be able to do this as part of the `glance` call, rather than needing to `mutate` the data frame afterward. For example, with a linear model, I might want to compute the corrected AIC (AICc) or a confidence interval for `r.squared`. 

It would be nice to be able to do so with a call like this to specify such additional functions:
```
glance(model, funs = list(AICc = AICc))
```

Here is a full example:

``` r
library(broom)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
AICc <- function (object, ..., k = 2) {
  UseMethod("AICc")
}
AICc.default <- function(object, ..., k = 2, n = NULL) {
  aic <- AIC(object, k = k)
  df <- attr(logLik(object), "df")
  if (is.null(n)) {
    n <- tryCatch(nobs(object),
                  error = function(e)
                    stop("Could not determine sample size for `fit`. Please specify `n`.")
    )
  }
  return(aic + 2 * (df^2 + df) / (n - df - 1))
}

mod <- lm(mpg ~ factor(cyl) + log(disp), data = mtcars)

AICc(mod)
#> [1] 159.4323
glance(mod, funs = list(AICc = AICc))
#> # A tibble: 1 x 12
#>   r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
#>       <dbl>         <dbl> <dbl>     <dbl>    <dbl> <dbl>  <dbl> <dbl> <dbl>
#> 1     0.835         0.817  2.58      47.2 4.47e-11     3  -73.6  157.  164.
#> # ... with 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>
glance(mod) %>% mutate(AICc = AICc(mod))
#> # A tibble: 1 x 13
#>   r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
#>       <dbl>         <dbl> <dbl>     <dbl>    <dbl> <dbl>  <dbl> <dbl> <dbl>
#> 1     0.835         0.817  2.58      47.2 4.47e-11     3  -73.6  157.  164.
#> # ... with 4 more variables: deviance <dbl>, df.residual <int>, nobs <int>,
#> #   AICc <dbl>
```

<sup>Created on 2020-09-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The output of the two `glance` calls would be the same.

Functions should be expected to return a single (probably numeric) value. Functions with vector output could be accepted by creating names the same way that `tidyr::pivot_longer` does by conctatenating the name given in `funs` to the names of the vector output.

Would you be open to a pull request implementing this?

**Comment by simonpcouch** [comment]
Thanks for the issue!

To me, the workflow with `mutate()` looks plenty clean/expressive, and I don't feel this functionality is worth the maintenance burden. Will sit on this.

**Comment by bwiernik** [comment]
Fair enough, the major benefit I'm encountering with respect to my teaching is that the `mutate()` workflow requires the dplyr data manipulation methods before students are able to work with it.

**Comment by alexpghayes** [comment]
AIC() has fairly variable behavior so relying on the default method will be
difficult to maintain and will introduce spooky behaviors here.

In general I understand the need for this but think this is feature creep I
would like to avoid. I'd prefer to consider PRs that just add new columns
to existing tidiers.
