### ISSUE TITLE
Support for H2O model objects

### ISSUE THREAD

**Issue by LCHansson** [tidymodels/broom#93]
First, thanks for a wonderful package!

Since H2O seems to be on its way to becoming increasingly popular among R users as a modelling/prediction backend, might it be possible to make `broom` support tidying its model objects?

The [H2O R package can be found here](https://github.com/h2oai/h2o-3/tree/master/h2o-r).

**Comment by dgrtwo** [comment]
I'd be interested in broom covering these, but it looks like it would be a huge undertaking. There are many kinds of models that can be contained within H2OModel (glm, kmeans, H2OMultinomialModel), and each would require its own tidying logic.

Did you have particular models you were most interested in? Would you consider writing any yourself and contributing them as a pull request?

**Comment by LCHansson** [comment]
So far I've only been working with H2OBinomialModel but I could definitely give that one a shot. I'll post a pull request once I have something reasonably feasible.

**Comment by kevinykuo** [comment]
Began working on this in https://github.com/tidyverse/broom/pull/214

**Comment by alexpghayes** [comment]
@kevinykuo Any chance you're still interested this? I know it's been a while but I think it would be an incredibly useful contribution that would see a lot of use.

**Comment by kevinykuo** [comment]
Won't have time for a few months so others feel free to take this on.
