### ISSUE TITLE
Rchoice tidiers

### ISSUE THREAD

**Issue by Nateme16** [tidymodels/broom#930]
I created a tidier for Rchoice model objects. I am not sophisticated enough to add to Broom, but maybe others can? Here it is below. It works now to call modelsummary (which relies on broom). Maybe someone more R savy can integrate this so that Rchoice objects can be tidied, or whatever you call it. 

tidy.Rchoice <- function(object, ...) {
  s <- getSummary.Rchoice(object, ...)
  ret <- tibble::tibble(term = row.names(s$coef),
                        estimate = s$coef[, 1],
                        std.error = s$coef[, 2],
                        z.value=s$coef[, 3], 
                        p.value=s$coef[,4],
                        conf.low=s$coef[,5],
                        conf.high=s$coef[,6])
  ret
}
glance.Rchoice <- function(object, ...) {
  s <- getSummary.Rchoice(object, ...)
  ret <- tibble::tibble(
                        n = s$sumstat['N'],
                        logLik = s$sumstat['logLik'],
                        AIC = s$sumstat['AIC'],
                        BIC = s$sumstat['BIC'],
                        df = s$sumstat['df']
                        )
  ret
}

**Comment by simonpcouch** [comment]
Thanks for the implementation!

If someone gets to this, I'd prefer to rely only on the model-owning package (and the typical helper packages, like `tibble` and `dplyr`) inside of tidiers' internals—feeling uncomfortable taking on the additional layer of dependencies with `modelsummary`.

Will leave this issue open for a bit to see if anyone jumps on this!

**Comment by simonpcouch** [comment]
Addressed in #961 🎉  Thanks to both of yall.
