### ISSUE TITLE
Segmented Object Error

### ISSUE THREAD

**Issue by JReising09** [tidymodels/broom#939]
First and foremost, thank you to all who work to develop and maintain packages in tidyverse and tidymodels. You all are heroes in book. I had an issue come up in some of my scripts that utilize nested models and map summaries with tidy() and glance() for segmented linear models. I am able to do so with broom version 0.5.2 but not able to with version 0.7.0, which is loaded from tidymodels. I am using the 'segmented' package version 1.2-0 (June 2020) and I have been unsuccessful in finding an example with the tidymodels framework for linear segmented models. Is there another preferred package for this type of modeling in the tidymodels/broom framework or will 'segmented' be supported again in later releases? Thanks!

**Comment by simonpcouch** [comment]
@JReising09 Thanks for the appreciation! Passing on to the tidy dev team. :-)

Do you mind to provide a [reprex] for the functionality you're hoping to see? If we previously supported `segmented` model objects, I'm unaware.

Two things come to mind... we deprecated data frame tidiers in 0.7.0, so if you mean that you had models in list-columns, you'll need to now `purrr::map()` over those columns. Also, mixed model tidiers now lived in `broom.mixed`, if that's relevant.

**Comment by JReising09** [comment]
Sure thing! Below is an example of the output I am expecting from version 0.5.2 and then the error I receive with version 0.7.0.

```R
# Install previous version broom

library(remotes)
install_version('broom', version = '0.5.2')
# Select 'None' for package updates
# Restart R 

library(tidyverse)
library(segmented)
library(broom)

Ex_Data<-expand.grid(Group = c('A','B'), X_var = seq(1:30))%>%
  bind_cols( data.frame(Error = sample(x = rnorm(60, sd = .5), size = 60)))%>%
  mutate(Y_var = ifelse(Group == 'A' & X_var < 10, 5 + .3*X_var + Error,
                        ifelse( Group == 'B' & X_var < 10, 2 + .5*X_var + Error, 7 + .15*X_var + Error)))

ModelData<-Ex_Data%>%
  group_by(Group)%>%
  nest(.key = 'Data')%>%
  mutate(SegMod = map(Data, ~segmented(lm(Y_var ~ X_var, data = .x), seg.Z = ~X_var)),
         ModelSummary = map(SegMod, ~tidy(.x)))

ModelData$ModelSummary[[1]]

## Output

# # A tibble: 4 x 5
# term        estimate std.error statistic  p.value
# <chr>          <dbl>     <dbl>     <dbl>    <dbl>
#   1 (Intercept)    4.91     0.408      12.0  3.89e-12
# 2 X_var          0.332    0.0601      5.53 8.44e- 6
# 3 U1.X_var      -0.182    0.0656     -2.78 1.00e- 2
# 4 psi1.X_var     0        2.56        0    1.00e+ 0


# Update broom to version 0.7.0
rm(Ex_Data)
rm(ModelData)

install.packages('broom')
#Restart R

library(tidyverse)
library(segmented)
library(broom)

Ex_Data<-expand.grid(Group = c('A','B'), X_var = seq(1:30))%>%
  bind_cols( data.frame(Error = sample(x = rnorm(60, sd = .5), size = 60)))%>%
  mutate(Y_var = ifelse(Group == 'A' & X_var < 10, 5 + .3*X_var + Error,
                        ifelse( Group == 'B' & X_var < 10, 2 + .5*X_var + Error, 7 + .15*X_var + Error)))

ModelData<-Ex_Data%>%
  group_by(Group)%>%
  nest(.key = 'Data')%>%
  mutate(SegMod = map(Data, ~segmented(lm(Y_var ~ X_var, data = .x), seg.Z = ~X_var)),
         ModelSummary = map(SegMod, ~tidy(.x)))

## Error

# Error: Problem with `mutate()` input `ModelSummary`.
# x No tidy method for objects of class segmented
# i Input `ModelSummary` is `map(SegMod, ~tidy(.x))`.
# i The error occurred in group 1: Group = "A".

ModelData$ModelSummary[[1]]
#Error: object 'ModelData' not found
```

**Comment by simonpcouch** [comment]
Thanks so much for the reprex! Helped to track down the issue much more quickly. 

The issue here is that `segmented` objects subclass `lm`, and the S3 dispatch doesn't defer to `lm` (which seems to work just fine.) A slightly more minimal reprex:

``` r
library(broom)
library(segmented)

# segmented model
seg <- segmented(lm(drat ~ wt, data = mtcars), seg.Z = ~wt)

# check class
class(seg)
#> [1] "segmented" "lm"

# try to tidy
tidy(seg)
#> Error: No tidy method for objects of class segmented

# overwrite class
class(seg) <- "lm"

# call on tidy.lm
tidy(seg)
#> # A tibble: 4 x 5
#>   term        estimate std.error statistic  p.value
#>   <chr>          <dbl>     <dbl>     <dbl>    <dbl>
#> 1 (Intercept)    5.23     0.296     17.6   1.05e-16
#> 2 wt            -0.525    0.0961    -5.46  7.84e- 6
#> 3 U1.wt          1.02     3.00       0.340 7.36e- 1
#> 4 psi1.wt        0        1.84       0     1.00e+ 0
```

<sup>Created on 2020-09-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Have to run to class, but wanted to document this for now. :-)

Related to #173.

**Comment by simonpcouch** [comment]
Thanks for your patience on this! This tidier was previously unintentionally supported before the broom 0.7.0 release. In 0.7.0, we decided to error out on objects that weren't `lm` objects but relied on the `lm` tidiers under the hood. We've transitioned this error to a warning in the development version of broom, and the previous output will be restored in broom 0.7.2.
