### ISSUE TITLE
Confidence level in augment.lm

### ISSUE THREAD

**Issue by julian-urbano** [tidymodels/broom#949]
Hi!

I was checking `augment` to compute intervals, and wanted to use different confidence levels. I presumed this would be done via something like `conf.level=0.9`, thinking about how `predict` is used. However, the intervals are always the same, regardless of the confidence level.

I looked at the code for `predict.lm` and found this line here https://github.com/tidymodels/broom/blob/8bd38356c2f675f6889df2627d687d110a4c0fe7/R/stats-lm-tidiers.R#L136

I think it should read as follows
```r
df <- augment_newdata(x, data, newdata, se_fit, interval, ...)
```
to forward other arguments, such as `conf.level` in this case.

Thoughts?

**Comment by simonpcouch** [comment]
This sounds like a good idea to me! 

re: the comment `be *incredibly* careful that the ... are passed correctly` in the `augment_newdata` comments, checking in—does this sound good to you, @alexpghayes?

**Comment by petebaker** [comment]
Hi @julian-urbano, @simonpcouch and @alexpghayes 

I would also like to nudge this topic along but I'm not sure about the interest level. I think that _broom_ is fantastic and it's a great step in the right direction. However, being able to set the `level` for a CI but not a PI is a deal breaker for me and I believe it is a trap for the unwary.

Recently, I **highly recommended** _broom_ to colleagues but once I found out the state of play w.r.t. prediction intervals I've **highly un-recommended** it. Here's why.

My colleagues wanted to study various prediction intervals  80%, 90% etc but they pointed out that the prediction intervals are always 95% which makes `augment.lm` essentially useless for them, and unfortunately they couldn't work out how to make it work so they abandoned `augment.lm`  and rolled their own using `predict.lm` and `level`.

The documentation around `...` is somewhat messy but the important problem is that `...` is not implemented. The documentation gives a heads up that things can go wrong when options are chosen via `...` which is perfectly sensible. (However, given that  `...` isn't implemented for prediction, then it is simply wrong). Am I missing something here?

I think _broom_ is great but if standard options/arguments like `level` for `predict.lm` simply aren't implemented when it appears that they are available, then this seems dangerous to me.

If maintainers are interested, then I will have a go at a pull request.

Comments most welcome!

Cheers
Peter

PS: Having produced both CIs and PIs for about 40 years now, then I would say that prediction intervals for new observations are often more useful than confidence intervals for the mean response (unless fixed at some arbitrary level of course).

**Comment by ptoche** [comment]
This would definitely be a nice addition. I think most people use `tidy()` to set confidence levels, rather than `augment()`, but I too tried it and noticed the confidence intervals weren't updated. Feels like a natural thing to try. Would be nice to have.

**Comment by julian-urbano** [comment]
So another year has passed, and I decided to have a go at this and create a pull request, as suggested by @alexpghayes.
However, when testing I get this error:
```
Failure (test-stats-lm.R:9:3): lm tidier arguments
length(not_allowed) == 0 is not TRUE

`actual`:   FALSE
`expected`: TRUE 
Arguments level to `augment.lm` must be listed in the argument glossary.
Backtrace:
 1. modeltests::check_arguments(augment.lm)
      at test-stats-lm.R:9:2
 2. testthat::expect_true(...)
```` 
which seems to refer to the [glossary on acceptable argument names](https://www.tidymodels.org/learn/develop/broom/#glossary). It looks like `augment` does not currently accept anything related to confidence levels.

Does this mean that this issue will not be address anytime soon? How about forwarding `...` to `predict`?

**Comment by alexpghayes** [comment]
You'll need to make a second PR to `alexpghayes/modeltests` to add any new argument names to individual `augment()` methods.
