### ISSUE TITLE
augment(..., data = df) fails when df has missing data

### ISSUE THREAD

**Issue by briatte** [tidymodels/broom#956]
```r
library(dplyr)
library(broom)

df <- data.frame(x = 1:10, y = 2 * (1:10) + 5 + rnorm(10))
df[5, 2] <- NA

lm(y ~ x, df) %>% 
  augment(data = df)
```

The reprex above mimics the one [in this other issue](https://github.com/tidymodels/broom/issues/168#issuecomment-641221590).

The function works fine when there are no missing data, but as soon as 1+ row(s) get(s) excluded for missingness, `augment` fails.

This happened over the last week -- everything worked fine 8 days ago. It looks like it might be related to a change in `vctrs`.

**Comment by simonpcouch** [comment]
Thanks for the issue!

From the `?augment.lm` docs:

> We are in the process of defining behaviors for models fit with various na.action arguments, but make no guarantees about behavior when data is missing at this time.

Not a super satisfying answer, but for now, using `newdata` rather than `data` seems to do the trick.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(broom)

df <- data.frame(x = 1:10, y = 2 * (1:10) + 5 + rnorm(10))
df[5, 2] <- NA

lm(y ~ x, df) %>% 
  augment(newdata = df)
#> # A tibble: 10 x 4
#>        x     y .fitted   .resid
#>    <int> <dbl>   <dbl>    <dbl>
#>  1     1  5.02    5.34 -0.319  
#>  2     2  6.70    7.54 -0.839  
#>  3     3 10.4     9.73  0.704  
#>  4     4 12.4    11.9   0.522  
#>  5     5 NA      14.1  NA      
#>  6     6 17.5    16.3   1.20   
#>  7     7 17.5    18.5  -1.03   
#>  8     8 20.7    20.7   0.00651
#>  9     9 22.7    22.9  -0.191  
#> 10    10 25.0    25.1  -0.0509
```

<sup>Created on 2020-11-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

FWIW, this particular error arises [here](https://github.com/tidymodels/broom/blob/ccbdb20c8d920fd27fed808ffd183c371a9dab29/R/utilities.R#L420-L421).

To clarify, this is not a new issue and is not related to the newest `vctrs` release. :-)

**Comment by briatte** [comment]
Thanks @simonpcouch -- not super-satisfying indeed, but at least `newdata` works as expected.

I am 100% positive that this issue did not arise on Friday 21 November. I taught a class on that day, and the code with `augment(, data =)` ran fine. It did not exactly one week later.
