### ISSUE TITLE
spatial model support for tidy, glance, and augment

### ISSUE THREAD

**Issue by DHLocke** [tidymodels/broom#97]
Broom is fantastic, really great work! Thanks so much.

It would be great of broom's tidy(), glance() and augment() worked for spatial models. The three I have in mind are the spatial lag model created with lagsarlm(), and the spatial error model created with errorsarlm() in the spdep package. Also, gwr() models created with the spgwr package would a nice addition to broom's functionality. Although gwr() creates a new set of SpatialPolygonsDataFrame or a SpatialPointsDataFrame which is really similar to what augment() would do.

Although I've read a bunch of posts on github, this is my first github request. So please let me know if this isn't the best way to make a request, or if my etiquette stinks.

Thanks again for a great package, its so useful!

**Comment by alexpghayes** [comment]
Hey @DHLocke. Apologies for the long delay in getting back to you. These seem like great additions. I don't use spatial models much day to day, so I'm not particularly aware of what kind of information is useful. Do you have any feedback about output what you'd want to see from `tidy`, `glance` and `augment` methods for `lagsarlm`, `errorsarlm` and `gwr` models?

**Comment by DHLocke** [comment]
Now its my turn to apologize for a slow response.

For *lagsarlm*, AIC, rho and its significance test would be nice to have in
*glance*.
For, *errorsarlm*, AIC, lambda its significance test would be nice to have
in *glance*.

It would be great if tidy worked on both *lagsarlm* and *errorsarlm*.

gwr already does a version of augment naturally.

Best, Dexter

**Comment by alexpghayes** [comment]
*cough* @angela-li *cough*

**Comment by petrhrobar** [comment]
Hi guys, I have written basenline for spatial model, the main function are finished and now need pullish up. I now support lagsarlm and errorsarlm, please see here https://github.com/tidymodels/broom/issues/841

I also provided examples

**Comment by simonpcouch** [comment]
Closing this in favor of #847.🙂
