### ISSUE TITLE
allowing `conf.level` as a valid column name in `broom` conventions

### ISSUE THREAD

**Issue by IndrajeetPatil** [tidymodels/broom#984]
The document here mentions that the width of the confidence interval can be contained in the `ci.width` column (as far as I've seen, none of the `tidy` methods actually contain this column in the output):

https://github.com/tidymodels/tidymodels.org/blob/7bd4d29e30a5ddf81763c580ce65fb1d3270c2da/content/learn/develop/broom/index.markdown

But, since this width is specified by argument `conf.level` in `broom::tidy()`, I am wondering if the column name should instead be: `conf.level`.

The benefit is that the user has one less thing to learn and the column name is consistent with the argument name.

**Comment by IndrajeetPatil** [comment]
cc @simonpcouch

**Comment by simonpcouch** [comment]
Thanks for the issue! 

I'm also not seeing any tidy methods actually outputting that column. My thought here, to make sure, is to deprecate `ci.width` from `modeltests` and see if anything breaks `broom`-side. If not, we can remove mention of the column in package-level docs (like the article you've linked to)!

**Comment by simonpcouch** [comment]
After dropping that column in the modeltests glossaries and re-running checks, it looks like there is indeed a tidier that uses this convention:

```
══ Failed tests ════════════════════════════════════════════════════════════════
── Failure (test-bingroup.R:22:3): tidy.binWidth ───────────────────────────────
length(unacceptable) == 0 is not TRUE

`actual`:   FALSE
`expected`: TRUE 
Output column names not in the column glossary: ci.width
```

Won't be going through with dropping that entry from the glossaries. Thank you for bringing this up, though. :-)
