### ISSUE TITLE
return residuals from augment() with a coxph() object

### ISSUE THREAD

**Issue by mlatif71** [tidymodels/broom#986]
Fit a Cox PH model with bladder data

```{r, echo= T }
library(survival)
mod1 <- coxph(Surv(stop, event) ~ rx, data = bladder) 
```

Martingale residuals from the copy object mod1

```{r, echo = T}
bdat <- broom::augment(mod1, newdata = bladder, type.residuals = "martingale") 
bdat
```

No .resid variable is in bdat object after specifying residual type in augment function. This feature is available in for lm and glm objects.

**Comment by benwhalley** [comment]
If someone ends up working on this, be aware that the tt() function in the survival package does weird things to the model matrix and the number of rows in predict() and residuals() won't match the number of rows in the original data.

**Comment by simonpcouch** [comment]
Thanks for the issue, and apologies for the delay! Please see:

https://github.com/tidymodels/broom/blob/3000ce74c826995fff993bd28656f993dbde7456/R/utilities.R#L380-L390

In your case, if you'd like to `augment()` on your training set, supply the data as `data` rather than `newdata` and you'll get residuals as desired:

``` r
library(broom)
library(survival)
  
mod1 <- coxph(Surv(stop, event) ~ rx, data = bladder) 

augment(mod1, data = bladder, type.residuals = "martingale")
#> # A tibble: 340 × 10
#>       id    rx number  size  stop event  enum .fitted .se.fit  .resid
#>    <int> <dbl>  <int> <int> <int> <dbl> <int>   <dbl>   <dbl>   <dbl>
#>  1     1     1      1     3     1     0     1   0.199  0.0884 -0.0105
#>  2     1     1      1     3     1     0     2   0.199  0.0884 -0.0105
#>  3     1     1      1     3     1     0     3   0.199  0.0884 -0.0105
#>  4     1     1      1     3     1     0     4   0.199  0.0884 -0.0105
#>  5     2     1      2     1     4     0     1   0.199  0.0884 -0.0819
#>  6     2     1      2     1     4     0     2   0.199  0.0884 -0.0819
#>  7     2     1      2     1     4     0     3   0.199  0.0884 -0.0819
#>  8     2     1      2     1     4     0     4   0.199  0.0884 -0.0819
#>  9     3     1      1     1     7     0     1   0.199  0.0884 -0.130 
#> 10     3     1      1     1     7     0     2   0.199  0.0884 -0.130 
#> # … with 330 more rows
```

<sup>Created on 2022-06-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
