### ISSUE TITLE
Specify the confint method in tidy.glm()

### ISSUE THREAD

**Issue by anddis** [tidymodels/broom#989]
Adding the possibility to specify the desired `confint` method via an argument to `tidy.glm()` would be terrific. 
My user case is to calculate Wald confidence intervals (`confint.default()`) instead of the default profile likelihood CIs for `glm` objects (`confint.glm()`).

See also the last 3 messages in #703.

**Comment by markdanese** [comment]
I agree, and just ran into the same issue where trying to run this took took long to complete on a gym model built using 1,000,000 observations.  Just as an added piece of information, the confidence interval approach taken also depends on whether the MASS package is on the user system.  While most people will have MASS, a dependency like this could cause problems.  Hence, it would be good to be able to control the behavior, if only for testing purposes.  From confint {stats}:

> There are stub methods in package stats for classes "glm" and "nls" which call those in package MASS (if installed): if the MASS namespace has been loaded, its methods will be used directly. (Those methods are based on profile likelihood.)

**Comment by lcgodoy** [comment]
are pull requests welcomed regarding this issue?

**Comment by simonpcouch** [comment]
Thanks for the issue + patience. :-) 

Seems like there's a decent amount of interest here, so yes! I'd look to the current `conf.method` argument in `tidy.boot` for a guide re: implementation and API. I know the underlying logic there isn't directly analogous to what this PR would implement, though I think the big idea is similar enough to warrant a consistent API.

🚀

**Comment by DanChaltiel** [comment]
Hi, 

As a counterpart of this feature request, there might be a need to also specify the method to compute the p-value between Wald and LRT.

As it is brilliantly explained on https://stats.stackexchange.com/a/144608/81974, the profile likelihood CIs are linked to the likelihood ratio test.

I always find it quite uncanny that the default method for computing the pvalue is Wald's while the default method for computing the confidence interval is PL. 

As a result, the output of `tidy.glm()` contains pvalues and CI that don't match (pvalue<0.05 and 1 not inside CI).

**Comment by simonpcouch** [comment]
Closed via #1060.
