### ISSUE TITLE
broom & dplyr example fails

### ISSUE THREAD

**Issue by mk9y** [tidymodels/broom#990]
## Reproducible example

```r
data(mtcars)
mtcars <- as_tibble(mtcars)
mtcars %>%
  nest(data = -am) %>% 
  mutate(
    fit = map(data, ~ lm(wt ~ mpg + qsec + gear, data = .x)),  # S3 list-col
    tidied = map(fit, tidy)
  ) %>% 
  unnest(tidied)
```
Output:

`rlang::last_error()
█
├─<error/dplyr:::mutate_error>
│ Problem with `mutate()` input `tidied`.
│ x Can't convert a `tbl_df/tbl/data.frame` object to function
│ ℹ Input `tidied` is `map(fit, tidy)`.
└─<error/rlang_error>
  Can't convert a `tbl_df/tbl/data.frame` object to function
Backtrace:
  1. `%>%`(...)
  8. purrr::map(fit, tidy)
 10. purrr:::as_mapper.default(.f, ...)
 11. rlang::as_function(.f)
 12. rlang:::abort_coercion(x, friendly_type("function"))
`

SessionInfo:
`
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16
 
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] essentials_0.1.0 ufs_0.4.3        car_3.0-10       carData_3.0-4    janitor_2.1.0    readxl_1.3.1     broom_0.7.4     
 [8] forcats_0.5.1    stringr_1.4.0    dplyr_1.0.4      purrr_0.3.4      readr_1.4.0      tidyr_1.1.2      tibble_3.0.6    
[15] ggplot2_3.3.3    tidyverse_1.3.0 
`

**Comment by simonpcouch** [comment]
Thanks for the issue!

I'm unable to reproduce your results. Could you use the `reprex` package to create your reproducible example? Here's the code you'll need to run:

``` r
library(reprex)

reprex({
  library(broom)
  library(tidyverse)
  data(mtcars)
  mtcars <- as_tibble(mtcars)
  mtcars %>%
    nest(data = -am) %>% 
    mutate(
      fit = map(data, ~ lm(wt ~ mpg + qsec + gear, data = .x)),  # S3 list-col
      tidied = map(fit, tidy)
    ) %>% 
    unnest(tidied)
  
  sessionInfo()
})

```

Much appreciated!

**Comment by mk9y** [comment]
I tried:

> library(reprex)
> 
> reprex({
+     library(broom)
+     library(tidyverse)
+     data(mtcars)
+     mtcars <- as_tibble(mtcars)
+     mtcars %>%
+         nest(data = -am) %>% 
+         mutate(
+             fit = map(data, ~ lm(wt ~ mpg + qsec + gear, data = .x)),  # S3 list-col
+             tidied = map(fit, tidy)
+         ) %>% 
+         unnest(tidied)
+     
+     sessionInfo()
+ }
+ )
Error in fansi::nchar_ctl(wide_chars$test, type = "width") : 
  read failed on /Library/Frameworks/R.framework/Versions/4.0/Resources/library/cli/R/sysdata.rdb
In addition: Warning message:
In fansi::nchar_ctl(wide_chars$test, type = "width") :
  restarting interrupted promise evaluation

**Comment by simonpcouch** [comment]
A bit thrown by this new round of errors—looks like corrupt package installs, potentially?🤔 Are you still encountering this error?
