### ISSUE TITLE
Compatibility with upcoming version of survival package

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#994]
Just got the follow revdep email

> The following packages all have a data() statement that fails, in their tests: aftgee, broom, flexsurv, frailtyEM, mlr3viz, muhaz, pammtools.  This is due to a change, namely that all the cancer data sets have now been bundled into a single file to save space and limit the CRAN "too large" complaints.   The data() command keys off the file name, not the data set name.   The help files for all the data sets have been updated.   Since survival lazyloads the data, I actually think you don't need a data() call, but I may be incorrect if survival is under 'imports' rather than 'depends'.

Not sure where the dev version of survival lives. If survival works on old R (say >= 3.3) we can bump the version dependency for `survival`. Otherwise we'll need to special case logic to handle the various survival versions.

**Comment by simonpcouch** [comment]
Just spent a moment with this, turns out that the only `data()` call to a `survival` dataset is in the documentation for the `muhaz::muhaz` tidiers. Dev version of survival is [here](https://github.com/therneau/survival), for reference. Pushing a fix here in a bit, and then will start CRAN prep.☃️
